#!/usr/bin/env python3
"""Emit `lean/ZirenDet/ZirenDet/IsaVectors.lean` from `vectors.json`.

Each vector becomes an `example` that runs the Lean ISA model (`ZirenDet/Isa.lean`) on the same
program words and initial memory the oracle and the Rust executor saw, and checks the register
file, HI/LO and the data window with `native_decide`.  `SPEC_LEAN_PER_INSTRUCTION` (default 2)
caps the examples per instruction to keep the Lean build short; set it to 10 for all 750.
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
repo = os.path.abspath(os.path.join(here, "..", "..", "..", "..", ".."))
per = int(os.environ.get("SPEC_LEAN_PER_INSTRUCTION", "2"))
d = json.load(open(os.path.join(here, "vectors.json")))
code = d["code"]


def w(v):
    return f"0x{v:08x}#32"


out = [
    "import ZirenDet.Isa",
    "",
    "/-! Generated by `crates/core/executor/tests/spec_vectors/gen_lean.py` from `vectors.json`: the",
    "same oracle vectors the Rust executor is checked against, replayed through the Lean ISA model.",
    "Do not edit. -/",
    "",
    "namespace ZirenDet.IsaVectors",
    "open ZirenDet.Isa",
    "",
]
count = {}
n = 0
for v in d["vectors"]:
    mn = v["mnemonic"]
    count[mn] = count.get(mn, 0) + 1
    if count[mn] > per:
        continue
    words = ", ".join(w(int(x, 16)) for x in v["words"])
    image = ", ".join(f"({w(int(a, 16))}, {w(val)})" for a, val in v["image"].items())
    regs = ", ".join(w(x) for x in v["regs"])
    mem = ", ".join(f"({w(int(a, 16))}, {w(val)})" for a, val in v["mem"].items())
    trap = "true" if v["expect_trap"] else "false"
    asm = " ; ".join(v["asm"])
    out.append(f"/-- `{v['name']}`: {asm} -/")
    out.append(f"example : check {w(code)} [{words}] [{image}] [{regs}] {w(v['hi'])} {w(v['lo'])} [{mem}] {trap} = true := by")
    out.append("  native_decide")
    out.append("")
    n += 1
out.append("end ZirenDet.IsaVectors")
path = os.path.join(repo, "lean", "ZirenDet", "ZirenDet", "IsaVectors.lean")
open(path, "w").write("\n".join(out) + "\n")
print(f"wrote {n} examples to {path}")
