/-
  Generated by `cargo run -p zkm-picus -- --chip AddSub --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.AddSub

open ZirenDet

/-! ### Module `AddSub__is_add` -/
namespace AddSub_is_add

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `add_gate_2` -/
  v2 : F
  /-- `sub_gate_3` -/
  v3 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  v306 : F
  v307 : F
  v308 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v13)) = 0 ∧
  w.v3 = 0 ∧
  (w.v2 * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  w.v9 = 0 ∧
  (w.v13 * w.v18) = 0 ∧
  (w.v13 * w.v19) = 0 ∧
  (w.v13 * w.v20) = 0 ∧
  (w.v13 * w.v21) = 0 ∧
  (w.v6).val ≤ ((65535 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((511 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (2 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v35).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (1 : F)) - w.v34) - (1 : F)) - w.v35) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (3 : F)) - w.v22) - (1 : F)) - w.v23) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v306 - (((w.v8 * (65536 : F)) + w.v7) + (5 : F))) = 0 ∧
  (w.v307 - (w.v1 + (4 : F))) = 0 ∧
  (w.v308 - ((w.v8 * (65536 : F)) + w.v7)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v0 = program.pc, v9 = program.opcode, v10 = program.op_a, v11 = program.op_b[0], v12 = program.op_c[0], v13 = program.op_a_0, v24 = mem_read[0].val[0], v25 = mem_read[0].val[1], v26 = mem_read[0].val[2], v27 = mem_read[0].val[3], v30 = mem_read[1].val[0], v31 = mem_read[1].val[1], v32 = mem_read[1].val[2], v33 = mem_read[1].val[3], v14 = mem_read[2].val[0], v15 = mem_read[2].val[1], v16 = mem_read[2].val[2], v17 = mem_read[2].val[3], v6 = state_recv[0], v308 = state_recv[1], v1 = state_recv[3]
  outputs: v6 = state_send[0], v306 = state_send[1], v1 = state_send[2], v307 = state_send[3], v11 = mem_write[0].addr, v24 = mem_write[0].val[0], v25 = mem_write[0].val[1], v26 = mem_write[0].val[2], v27 = mem_write[0].val[3], v12 = mem_write[1].addr, v30 = mem_write[1].val[0], v31 = mem_write[1].val[1], v32 = mem_write[1].val[2], v33 = mem_write[1].val[3], v10 = mem_write[2].addr, v18 = mem_write[2].val[0], v19 = mem_write[2].val[1], v20 = mem_write[2].val[2], v21 = mem_write[2].val[3] -/
def input_origins : List String := ["program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_a_0", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_program_pc (w : W) : F := w.v0
def in_program_opcode (w : W) : F := w.v9
def in_program_op_a (w : W) : F := w.v10
def in_program_op_b (w : W) : F := w.v11
def in_program_op_c (w : W) : F := w.v12
def in_program_op_a_0 (w : W) : F := w.v13
def in_mem_read_0_val (w : W) : List F := [w.v24, w.v25, w.v26, w.v27]
def in_mem_read_1_val (w : W) : List F := [w.v30, w.v31, w.v32, w.v33]
def in_mem_read_2_val (w : W) : List F := [w.v14, w.v15, w.v16, w.v17]
def in_state_recv (w : W) : List F := [w.v6, w.v308, w.v1]
def out_state_send (w : W) : List F := [w.v6, w.v306, w.v1, w.v307]
def out_mem_write_0_addr (w : W) : F := w.v11
def out_mem_write_0_val (w : W) : List F := [w.v24, w.v25, w.v26, w.v27]
def out_mem_write_1_addr (w : W) : F := w.v12
def out_mem_write_1_val (w : W) : List F := [w.v30, w.v31, w.v32, w.v33]
def out_mem_write_2_addr (w : W) : F := w.v10
def out_mem_write_2_val (w : W) : List F := [w.v18, w.v19, w.v20, w.v21]

def inputs (w : W) : List F :=
  [w.v0, w.v9, w.v10, w.v11, w.v12, w.v13, w.v24, w.v25, w.v26, w.v27, w.v30, w.v31, w.v32, w.v33, w.v14, w.v15, w.v16, w.v17, w.v6, w.v308, w.v1]
def outputs (w : W) : List F :=
  [w.v6, w.v306, w.v1, w.v307, w.v11, w.v24, w.v25, w.v26, w.v27, w.v12, w.v30, w.v31, w.v32, w.v33, w.v10, w.v18, w.v19, w.v20, w.v21]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end AddSub_is_add

/-! ### Module `AddSub__is_sub` -/
namespace AddSub_is_sub

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `add_gate_2` -/
  v2 : F
  /-- `sub_gate_3` -/
  v3 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  v309 : F
  v310 : F
  v311 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  w.v2 = 0 ∧
  (w.v3 - ((1 : F) - w.v13)) = 0 ∧
  (w.v2 * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v9 - (1 : F)) = 0 ∧
  (w.v13 * w.v18) = 0 ∧
  (w.v13 * w.v19) = 0 ∧
  (w.v13 * w.v20) = 0 ∧
  (w.v13 * w.v21) = 0 ∧
  (w.v6).val ≤ ((65535 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((511 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (2 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v35).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (1 : F)) - w.v34) - (1 : F)) - w.v35) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (3 : F)) - w.v22) - (1 : F)) - w.v23) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v309 - (((w.v8 * (65536 : F)) + w.v7) + (5 : F))) = 0 ∧
  (w.v310 - (w.v1 + (4 : F))) = 0 ∧
  (w.v311 - ((w.v8 * (65536 : F)) + w.v7)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v0 = program.pc, v9 = program.opcode, v10 = program.op_a, v11 = program.op_b[0], v12 = program.op_c[0], v13 = program.op_a_0, v24 = mem_read[0].val[0], v25 = mem_read[0].val[1], v26 = mem_read[0].val[2], v27 = mem_read[0].val[3], v30 = mem_read[1].val[0], v31 = mem_read[1].val[1], v32 = mem_read[1].val[2], v33 = mem_read[1].val[3], v14 = mem_read[2].val[0], v15 = mem_read[2].val[1], v16 = mem_read[2].val[2], v17 = mem_read[2].val[3], v6 = state_recv[0], v311 = state_recv[1], v1 = state_recv[3]
  outputs: v6 = state_send[0], v309 = state_send[1], v1 = state_send[2], v310 = state_send[3], v11 = mem_write[0].addr, v24 = mem_write[0].val[0], v25 = mem_write[0].val[1], v26 = mem_write[0].val[2], v27 = mem_write[0].val[3], v12 = mem_write[1].addr, v30 = mem_write[1].val[0], v31 = mem_write[1].val[1], v32 = mem_write[1].val[2], v33 = mem_write[1].val[3], v10 = mem_write[2].addr, v18 = mem_write[2].val[0], v19 = mem_write[2].val[1], v20 = mem_write[2].val[2], v21 = mem_write[2].val[3] -/
def input_origins : List String := ["program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_a_0", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_program_pc (w : W) : F := w.v0
def in_program_opcode (w : W) : F := w.v9
def in_program_op_a (w : W) : F := w.v10
def in_program_op_b (w : W) : F := w.v11
def in_program_op_c (w : W) : F := w.v12
def in_program_op_a_0 (w : W) : F := w.v13
def in_mem_read_0_val (w : W) : List F := [w.v24, w.v25, w.v26, w.v27]
def in_mem_read_1_val (w : W) : List F := [w.v30, w.v31, w.v32, w.v33]
def in_mem_read_2_val (w : W) : List F := [w.v14, w.v15, w.v16, w.v17]
def in_state_recv (w : W) : List F := [w.v6, w.v311, w.v1]
def out_state_send (w : W) : List F := [w.v6, w.v309, w.v1, w.v310]
def out_mem_write_0_addr (w : W) : F := w.v11
def out_mem_write_0_val (w : W) : List F := [w.v24, w.v25, w.v26, w.v27]
def out_mem_write_1_addr (w : W) : F := w.v12
def out_mem_write_1_val (w : W) : List F := [w.v30, w.v31, w.v32, w.v33]
def out_mem_write_2_addr (w : W) : F := w.v10
def out_mem_write_2_val (w : W) : List F := [w.v18, w.v19, w.v20, w.v21]

def inputs (w : W) : List F :=
  [w.v0, w.v9, w.v10, w.v11, w.v12, w.v13, w.v24, w.v25, w.v26, w.v27, w.v30, w.v31, w.v32, w.v33, w.v14, w.v15, w.v16, w.v17, w.v6, w.v311, w.v1]
def outputs (w : W) : List F :=
  [w.v6, w.v309, w.v1, w.v310, w.v11, w.v24, w.v25, w.v26, w.v27, w.v12, w.v30, w.v31, w.v32, w.v33, w.v10, w.v18, w.v19, w.v20, w.v21]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end AddSub_is_sub

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `add_gate_2` -/
  v2 : F
  /-- `sub_gate_3` -/
  v3 : F
  /-- `is_add_4` -/
  v4 : F
  /-- `is_sub_5` -/
  v5 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v4 * (w.v4 - (1 : F))) = 0 ∧
  (w.v5 * (w.v5 - (1 : F))) = 0 ∧
  ((w.v4 + w.v5) * ((w.v4 + w.v5) - (1 : F))) = 0 ∧
  (w.v2 - (w.v4 * ((1 : F) - w.v13))) = 0 ∧
  (w.v3 - (w.v5 * ((1 : F) - w.v13))) = 0 ∧
  (w.v2 * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) * ((((w.v24 + w.v30) - w.v18) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v2 * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v27 + w.v33) - w.v21) + ((((w.v26 + w.v32) - w.v20) + ((((w.v25 + w.v31) - w.v19) + (((w.v24 + w.v30) - w.v18) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) * ((((w.v18 + w.v30) - w.v24) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v3 * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v21 + w.v33) - w.v27) + ((((w.v20 + w.v32) - w.v26) + ((((w.v19 + w.v31) - w.v25) + (((w.v18 + w.v30) - w.v24) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((w.v4 + w.v5) * (w.v9 - w.v5)) = 0 ∧
  ((w.v4 + w.v5) * ((w.v4 + w.v5) - (1 : F))) = 0 ∧
  ((w.v4 + w.v5) * ((w.v4 + w.v5) - (1 : F))) = 0 ∧
  (w.v13 * w.v18) = 0 ∧
  (w.v13 * w.v19) = 0 ∧
  (w.v13 * w.v20) = 0 ∧
  (w.v13 * w.v21) = 0 ∧
  ((w.v4 + w.v5) * ((w.v4 + w.v5) - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  
  outputs:  -/
def input_origins : List String := []
def output_origins : List String := []

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v4, w.v5]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v4 * (w.v4 - (1 : F))) = 0 ∧
    (w.v5 * (w.v5 - (1 : F))) = 0 ∧
    ((w.v4 + w.v5)).val < ((2 : F)).val := by
  picus_det [constraints_0]

end top

end ZirenDet.Chips.AddSub
