/-
  Generated by `cargo run -p zkm-picus -- --chip BitwiseImm --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.BitwiseImm

open ZirenDet

/-! ### Module `byte_and` -/
namespace byte_and

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_and

/-! ### Module `byte_or` -/
namespace byte_or

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_or

/-! ### Module `byte_xor` -/
namespace byte_xor

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_xor

/-! ### Module `BitwiseImm__is_and` -/
namespace BitwiseImm_is_and

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  v306 : F
  v307 : F
  v308 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v16)) = 0 ∧
  (w.v9 - (15 : F)) = 0 ∧
  (w.v16 * w.v21) = 0 ∧
  (w.v16 * w.v22) = 0 ∧
  (w.v16 * w.v23) = 0 ∧
  (w.v16 * w.v24) = 0 ∧
  (w.v6).val ≤ ((65535 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((511 : F)).val ∧
  (w.v32).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (2 : F)) - w.v31) - (1 : F)) - w.v32) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (3 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v306 - (((w.v8 * (65536 : F)) + w.v7) + (5 : F))) = 0 ∧
  (w.v307 - (w.v1 + (4 : F))) = 0 ∧
  (w.v308 - ((w.v8 * (65536 : F)) + w.v7)) = 0 ∧
  byte_and.rel [w.v27, w.v12] [w.v21] ∧
  byte_and.rel [w.v28, w.v13] [w.v22] ∧
  byte_and.rel [w.v29, w.v14] [w.v23] ∧
  byte_and.rel [w.v30, w.v15] [w.v24]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v27, w.v28, w.v29, w.v30, w.v17, w.v18, w.v19, w.v20, w.v6, w.v308, w.v1]
def outputs (w : W) : List F :=
  [w.v6, w.v306, w.v1, w.v307, w.v11, w.v27, w.v28, w.v29, w.v30, w.v10, w.v21, w.v22, w.v23, w.v24]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end BitwiseImm_is_and

/-! ### Module `BitwiseImm__is_or` -/
namespace BitwiseImm_is_or

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  v303 : F
  v304 : F
  v305 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v16)) = 0 ∧
  (w.v9 - (16 : F)) = 0 ∧
  (w.v16 * w.v21) = 0 ∧
  (w.v16 * w.v22) = 0 ∧
  (w.v16 * w.v23) = 0 ∧
  (w.v16 * w.v24) = 0 ∧
  (w.v6).val ≤ ((65535 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((511 : F)).val ∧
  (w.v32).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (2 : F)) - w.v31) - (1 : F)) - w.v32) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (3 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v303 - (((w.v8 * (65536 : F)) + w.v7) + (5 : F))) = 0 ∧
  (w.v304 - (w.v1 + (4 : F))) = 0 ∧
  (w.v305 - ((w.v8 * (65536 : F)) + w.v7)) = 0 ∧
  byte_or.rel [w.v27, w.v12] [w.v21] ∧
  byte_or.rel [w.v28, w.v13] [w.v22] ∧
  byte_or.rel [w.v29, w.v14] [w.v23] ∧
  byte_or.rel [w.v30, w.v15] [w.v24]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v27, w.v28, w.v29, w.v30, w.v17, w.v18, w.v19, w.v20, w.v6, w.v305, w.v1]
def outputs (w : W) : List F :=
  [w.v6, w.v303, w.v1, w.v304, w.v11, w.v27, w.v28, w.v29, w.v30, w.v10, w.v21, w.v22, w.v23, w.v24]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_or : ∀ i o o', byte_or.rel i o → byte_or.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end BitwiseImm_is_or

/-! ### Module `BitwiseImm__is_xor` -/
namespace BitwiseImm_is_xor

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  v300 : F
  v301 : F
  v302 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v16)) = 0 ∧
  (w.v9 - (17 : F)) = 0 ∧
  (w.v16 * w.v21) = 0 ∧
  (w.v16 * w.v22) = 0 ∧
  (w.v16 * w.v23) = 0 ∧
  (w.v16 * w.v24) = 0 ∧
  (w.v6).val ≤ ((65535 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((511 : F)).val ∧
  (w.v32).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (2 : F)) - w.v31) - (1 : F)) - w.v32) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v8 * (65536 : F)) + w.v7) + (3 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v300 - (((w.v8 * (65536 : F)) + w.v7) + (5 : F))) = 0 ∧
  (w.v301 - (w.v1 + (4 : F))) = 0 ∧
  (w.v302 - ((w.v8 * (65536 : F)) + w.v7)) = 0 ∧
  byte_xor.rel [w.v27, w.v12] [w.v21] ∧
  byte_xor.rel [w.v28, w.v13] [w.v22] ∧
  byte_xor.rel [w.v29, w.v14] [w.v23] ∧
  byte_xor.rel [w.v30, w.v15] [w.v24]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v27, w.v28, w.v29, w.v30, w.v17, w.v18, w.v19, w.v20, w.v6, w.v302, w.v1]
def outputs (w : W) : List F :=
  [w.v6, w.v300, w.v1, w.v301, w.v11, w.v27, w.v28, w.v29, w.v30, w.v10, w.v21, w.v22, w.v23, w.v24]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_xor : ∀ i o o', byte_xor.rel i o → byte_xor.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end BitwiseImm_is_xor

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `is_xor_3` -/
  v3 : F
  /-- `is_or_4` -/
  v4 : F
  /-- `is_and_5` -/
  v5 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - (((w.v3 + w.v4) + w.v5) * ((1 : F) - w.v16))) = 0 ∧
  (w.v3 * (w.v3 - (1 : F))) = 0 ∧
  (w.v4 * (w.v4 - (1 : F))) = 0 ∧
  (w.v5 * (w.v5 - (1 : F))) = 0 ∧
  (((w.v3 + w.v4) + w.v5) * (((w.v3 + w.v4) + w.v5) - (1 : F))) = 0 ∧
  (((w.v3 + w.v4) + w.v5) * (w.v9 - (((w.v3 * (17 : F)) + (w.v4 * (16 : F))) + (w.v5 * (15 : F))))) = 0 ∧
  (((w.v3 + w.v4) + w.v5) * (((w.v3 + w.v4) + w.v5) - (1 : F))) = 0 ∧
  (w.v16 * w.v21) = 0 ∧
  (w.v16 * w.v22) = 0 ∧
  (w.v16 * w.v23) = 0 ∧
  (w.v16 * w.v24) = 0 ∧
  (((w.v3 + w.v4) + w.v5) * (((w.v3 + w.v4) + w.v5) - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v3, w.v4, w.v5]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v3 * (w.v3 - (1 : F))) = 0 ∧
    (w.v4 * (w.v4 - (1 : F))) = 0 ∧
    (w.v5 * (w.v5 - (1 : F))) = 0 ∧
    (((w.v3 + w.v4) + w.v5)).val < ((2 : F)).val := by
  picus_det [constraints_0]

end top

end ZirenDet.Chips.BitwiseImm
