/-
  Generated by `cargo run -p zkm-picus -- --chip Bitwise --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.Bitwise

open ZirenDet

/-! ### Module `byte_and` -/
namespace byte_and

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_and

/-! ### Module `byte_nor` -/
namespace byte_nor

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_nor

/-! ### Module `byte_or` -/
namespace byte_or

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_or

/-! ### Module `byte_xor` -/
namespace byte_xor

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_xor

/-! ### Module `Bitwise__is_and` -/
namespace Bitwise_is_and

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  v317 : F
  v318 : F
  v319 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v14)) = 0 ∧
  (w.v10 - (15 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((65535 : F)).val ∧
  (w.v9).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (1 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v317 - (((w.v9 * (65536 : F)) + w.v8) + (5 : F))) = 0 ∧
  (w.v318 - (w.v1 + (4 : F))) = 0 ∧
  (w.v319 - ((w.v9 * (65536 : F)) + w.v8)) = 0 ∧
  byte_and.rel [w.v25, w.v31] [w.v19] ∧
  byte_and.rel [w.v26, w.v32] [w.v20] ∧
  byte_and.rel [w.v27, w.v33] [w.v21] ∧
  byte_and.rel [w.v28, w.v34] [w.v22]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v31, w.v32, w.v33, w.v34, w.v15, w.v16, w.v17, w.v18, w.v7, w.v319, w.v1]
def outputs (w : W) : List F :=
  [w.v7, w.v317, w.v1, w.v318, w.v12, w.v25, w.v26, w.v27, w.v28, w.v13, w.v31, w.v32, w.v33, w.v34, w.v11, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end Bitwise_is_and

/-! ### Module `Bitwise__is_nor` -/
namespace Bitwise_is_nor

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  v308 : F
  v309 : F
  v310 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v14)) = 0 ∧
  (w.v10 - (18 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((65535 : F)).val ∧
  (w.v9).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (1 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v308 - (((w.v9 * (65536 : F)) + w.v8) + (5 : F))) = 0 ∧
  (w.v309 - (w.v1 + (4 : F))) = 0 ∧
  (w.v310 - ((w.v9 * (65536 : F)) + w.v8)) = 0 ∧
  byte_nor.rel [w.v25, w.v31] [w.v19] ∧
  byte_nor.rel [w.v26, w.v32] [w.v20] ∧
  byte_nor.rel [w.v27, w.v33] [w.v21] ∧
  byte_nor.rel [w.v28, w.v34] [w.v22]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v31, w.v32, w.v33, w.v34, w.v15, w.v16, w.v17, w.v18, w.v7, w.v310, w.v1]
def outputs (w : W) : List F :=
  [w.v7, w.v308, w.v1, w.v309, w.v12, w.v25, w.v26, w.v27, w.v28, w.v13, w.v31, w.v32, w.v33, w.v34, w.v11, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_nor : ∀ i o o', byte_nor.rel i o → byte_nor.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end Bitwise_is_nor

/-! ### Module `Bitwise__is_or` -/
namespace Bitwise_is_or

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  v314 : F
  v315 : F
  v316 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v14)) = 0 ∧
  (w.v10 - (16 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((65535 : F)).val ∧
  (w.v9).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (1 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v314 - (((w.v9 * (65536 : F)) + w.v8) + (5 : F))) = 0 ∧
  (w.v315 - (w.v1 + (4 : F))) = 0 ∧
  (w.v316 - ((w.v9 * (65536 : F)) + w.v8)) = 0 ∧
  byte_or.rel [w.v25, w.v31] [w.v19] ∧
  byte_or.rel [w.v26, w.v32] [w.v20] ∧
  byte_or.rel [w.v27, w.v33] [w.v21] ∧
  byte_or.rel [w.v28, w.v34] [w.v22]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v31, w.v32, w.v33, w.v34, w.v15, w.v16, w.v17, w.v18, w.v7, w.v316, w.v1]
def outputs (w : W) : List F :=
  [w.v7, w.v314, w.v1, w.v315, w.v12, w.v25, w.v26, w.v27, w.v28, w.v13, w.v31, w.v32, w.v33, w.v34, w.v11, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_or : ∀ i o o', byte_or.rel i o → byte_or.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end Bitwise_is_or

/-! ### Module `Bitwise__is_xor` -/
namespace Bitwise_is_xor

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  v311 : F
  v312 : F
  v313 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((1 : F) - w.v14)) = 0 ∧
  (w.v10 - (17 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((65535 : F)).val ∧
  (w.v9).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (1 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v9 * (65536 : F)) + w.v8) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v311 - (((w.v9 * (65536 : F)) + w.v8) + (5 : F))) = 0 ∧
  (w.v312 - (w.v1 + (4 : F))) = 0 ∧
  (w.v313 - ((w.v9 * (65536 : F)) + w.v8)) = 0 ∧
  byte_xor.rel [w.v25, w.v31] [w.v19] ∧
  byte_xor.rel [w.v26, w.v32] [w.v20] ∧
  byte_xor.rel [w.v27, w.v33] [w.v21] ∧
  byte_xor.rel [w.v28, w.v34] [w.v22]

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v0, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v31, w.v32, w.v33, w.v34, w.v15, w.v16, w.v17, w.v18, w.v7, w.v313, w.v1]
def outputs (w : W) : List F :=
  [w.v7, w.v311, w.v1, w.v312, w.v12, w.v25, w.v26, w.v27, w.v28, w.v13, w.v31, w.v32, w.v33, w.v34, w.v11, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_xor : ∀ i o o', byte_xor.rel i o → byte_xor.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end Bitwise_is_xor

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `lookup_gate_2` -/
  v2 : F
  /-- `is_nor_3` -/
  v3 : F
  /-- `is_xor_4` -/
  v4 : F
  /-- `is_or_5` -/
  v5 : F
  /-- `is_and_6` -/
  v6 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v2 - ((((w.v4 + w.v5) + w.v6) + w.v3) * ((1 : F) - w.v14))) = 0 ∧
  (w.v4 * (w.v4 - (1 : F))) = 0 ∧
  (w.v5 * (w.v5 - (1 : F))) = 0 ∧
  (w.v6 * (w.v6 - (1 : F))) = 0 ∧
  (w.v3 * (w.v3 - (1 : F))) = 0 ∧
  ((((w.v4 + w.v5) + w.v6) + w.v3) * ((((w.v4 + w.v5) + w.v6) + w.v3) - (1 : F))) = 0 ∧
  ((((w.v4 + w.v5) + w.v6) + w.v3) * (w.v10 - ((((w.v4 * (17 : F)) + (w.v5 * (16 : F))) + (w.v6 * (15 : F))) + (w.v3 * (18 : F))))) = 0 ∧
  ((((w.v4 + w.v5) + w.v6) + w.v3) * ((((w.v4 + w.v5) + w.v6) + w.v3) - (1 : F))) = 0 ∧
  ((((w.v4 + w.v5) + w.v6) + w.v3) * ((((w.v4 + w.v5) + w.v6) + w.v3) - (1 : F))) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  ((((w.v4 + w.v5) + w.v6) + w.v3) * ((((w.v4 + w.v5) + w.v6) + w.v3) - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v3, w.v4, w.v5, w.v6]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v3 * (w.v3 - (1 : F))) = 0 ∧
    (w.v4 * (w.v4 - (1 : F))) = 0 ∧
    (w.v5 * (w.v5 - (1 : F))) = 0 ∧
    (w.v6 * (w.v6 - (1 : F))) = 0 ∧
    ((((w.v3 + w.v4) + w.v5) + w.v6)).val < ((2 : F)).val := by
  picus_det [constraints_0]

end top

end ZirenDet.Chips.Bitwise
