/-
  Generated by `cargo run -p zkm-picus -- --chip BooleanCircuitGarbleControl --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.BooleanCircuitGarbleControl

open ZirenDet

/-! ### Module `BooleanCircuitGarbleControl` -/
namespace BooleanCircuitGarbleControl

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `shard_0` -/
  v0 : F
  /-- `clk_1` -/
  v1 : F
  /-- `input_address_3` -/
  v3 : F
  /-- `output_address_4` -/
  v4 : F
  /-- `gates_num_5` -/
  v5 : F
  /-- `delta_6` -/
  v6 : F
  /-- `delta_7` -/
  v7 : F
  /-- `delta_8` -/
  v8 : F
  /-- `delta_9` -/
  v9 : F
  /-- `delta_10` -/
  v10 : F
  /-- `delta_11` -/
  v11 : F
  /-- `delta_12` -/
  v12 : F
  /-- `delta_13` -/
  v13 : F
  /-- `delta_14` -/
  v14 : F
  /-- `delta_15` -/
  v15 : F
  /-- `delta_16` -/
  v16 : F
  /-- `delta_17` -/
  v17 : F
  /-- `delta_18` -/
  v18 : F
  /-- `delta_19` -/
  v19 : F
  /-- `delta_20` -/
  v20 : F
  /-- `delta_21` -/
  v21 : F
  /-- `num_gates_mem_22` -/
  v22 : F
  /-- `num_gates_mem_23` -/
  v23 : F
  /-- `num_gates_mem_24` -/
  v24 : F
  /-- `num_gates_mem_25` -/
  v25 : F
  /-- `num_gates_mem_26` -/
  v26 : F
  /-- `num_gates_mem_27` -/
  v27 : F
  /-- `num_gates_mem_28` -/
  v28 : F
  /-- `num_gates_mem_29` -/
  v29 : F
  /-- `num_gates_mem_30` -/
  v30 : F
  /-- `num_gates_mem_31` -/
  v31 : F
  /-- `delta_mem_32` -/
  v32 : F
  /-- `delta_mem_33` -/
  v33 : F
  /-- `delta_mem_34` -/
  v34 : F
  /-- `delta_mem_35` -/
  v35 : F
  /-- `delta_mem_36` -/
  v36 : F
  /-- `delta_mem_37` -/
  v37 : F
  /-- `delta_mem_38` -/
  v38 : F
  /-- `delta_mem_39` -/
  v39 : F
  /-- `delta_mem_40` -/
  v40 : F
  /-- `delta_mem_41` -/
  v41 : F
  /-- `delta_mem_42` -/
  v42 : F
  /-- `delta_mem_43` -/
  v43 : F
  /-- `delta_mem_44` -/
  v44 : F
  /-- `delta_mem_45` -/
  v45 : F
  /-- `delta_mem_46` -/
  v46 : F
  /-- `delta_mem_47` -/
  v47 : F
  /-- `delta_mem_48` -/
  v48 : F
  /-- `delta_mem_49` -/
  v49 : F
  /-- `delta_mem_50` -/
  v50 : F
  /-- `delta_mem_51` -/
  v51 : F
  /-- `delta_mem_52` -/
  v52 : F
  /-- `delta_mem_53` -/
  v53 : F
  /-- `delta_mem_54` -/
  v54 : F
  /-- `delta_mem_55` -/
  v55 : F
  /-- `delta_mem_56` -/
  v56 : F
  /-- `delta_mem_57` -/
  v57 : F
  /-- `delta_mem_58` -/
  v58 : F
  /-- `delta_mem_59` -/
  v59 : F
  /-- `delta_mem_60` -/
  v60 : F
  /-- `delta_mem_61` -/
  v61 : F
  /-- `delta_mem_62` -/
  v62 : F
  /-- `delta_mem_63` -/
  v63 : F
  /-- `delta_mem_64` -/
  v64 : F
  /-- `delta_mem_65` -/
  v65 : F
  /-- `delta_mem_66` -/
  v66 : F
  /-- `delta_mem_67` -/
  v67 : F
  /-- `delta_mem_68` -/
  v68 : F
  /-- `delta_mem_69` -/
  v69 : F
  /-- `delta_mem_70` -/
  v70 : F
  /-- `delta_mem_71` -/
  v71 : F
  /-- `result_mem_72` -/
  v72 : F
  /-- `result_mem_73` -/
  v73 : F
  /-- `result_mem_74` -/
  v74 : F
  /-- `result_mem_75` -/
  v75 : F
  /-- `result_mem_76` -/
  v76 : F
  /-- `result_mem_77` -/
  v77 : F
  /-- `result_mem_78` -/
  v78 : F
  /-- `result_mem_79` -/
  v79 : F
  /-- `result_mem_80` -/
  v80 : F
  /-- `result_mem_81` -/
  v81 : F
  /-- `result_mem_82` -/
  v82 : F
  /-- `result_mem_83` -/
  v83 : F
  /-- `result_mem_84` -/
  v84 : F
  /-- `result_mem_85` -/
  v85 : F
  v406 : F
  v407 : F
  v408 : F
  v409 : F
  v410 : F
  v411 : F
  v412 : F
  v413 : F
  v414 : F
  v415 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v28 * (w.v28 - (1 : F))) = 0 ∧
  (w.v28 * (w.v0 - w.v26)) = 0 ∧
  (w.v31 * (w.v31 - (1 : F))) = 0 ∧
  (((((w.v28 * w.v1) + (((1 : F) - w.v28) * w.v0)) - ((w.v28 * w.v27) + (((1 : F) - w.v28) * w.v26))) - (1 : F)) - ((w.v29 + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v38 * (w.v38 - (1 : F))) = 0 ∧
  (w.v38 * (w.v0 - w.v36)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (((((w.v38 * w.v1) + (((1 : F) - w.v38) * w.v0)) - ((w.v38 * w.v37) + (((1 : F) - w.v38) * w.v36))) - (1 : F)) - ((w.v39 + (w.v40 * (65536 : F))) + (w.v41 * (16777216 : F)))) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v48 * (w.v0 - w.v46)) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (((((w.v48 * w.v1) + (((1 : F) - w.v48) * w.v0)) - ((w.v48 * w.v47) + (((1 : F) - w.v48) * w.v46))) - (1 : F)) - ((w.v49 + (w.v50 * (65536 : F))) + (w.v51 * (16777216 : F)))) = 0 ∧
  (w.v58 * (w.v58 - (1 : F))) = 0 ∧
  (w.v58 * (w.v0 - w.v56)) = 0 ∧
  (w.v61 * (w.v61 - (1 : F))) = 0 ∧
  (((((w.v58 * w.v1) + (((1 : F) - w.v58) * w.v0)) - ((w.v58 * w.v57) + (((1 : F) - w.v58) * w.v56))) - (1 : F)) - ((w.v59 + (w.v60 * (65536 : F))) + (w.v61 * (16777216 : F)))) = 0 ∧
  (w.v68 * (w.v68 - (1 : F))) = 0 ∧
  (w.v68 * (w.v0 - w.v66)) = 0 ∧
  (w.v71 * (w.v71 - (1 : F))) = 0 ∧
  (((((w.v68 * w.v1) + (((1 : F) - w.v68) * w.v0)) - ((w.v68 * w.v67) + (((1 : F) - w.v68) * w.v66))) - (1 : F)) - ((w.v69 + (w.v70 * (65536 : F))) + (w.v71 * (16777216 : F)))) = 0 ∧
  (w.v5 - (((w.v22 + (w.v23 * (256 : F))) + (w.v24 * (65536 : F))) + (w.v25 * (16777216 : F)))) = 0 ∧
  (w.v6 - w.v32) = 0 ∧
  (w.v7 - w.v33) = 0 ∧
  (w.v8 - w.v34) = 0 ∧
  (w.v9 - w.v35) = 0 ∧
  (w.v10 - w.v42) = 0 ∧
  (w.v11 - w.v43) = 0 ∧
  (w.v12 - w.v44) = 0 ∧
  (w.v13 - w.v45) = 0 ∧
  (w.v14 - w.v52) = 0 ∧
  (w.v15 - w.v53) = 0 ∧
  (w.v16 - w.v54) = 0 ∧
  (w.v17 - w.v55) = 0 ∧
  (w.v18 - w.v62) = 0 ∧
  (w.v19 - w.v63) = 0 ∧
  (w.v20 - w.v64) = 0 ∧
  (w.v21 - w.v65) = 0 ∧
  (w.v82 * (w.v82 - (1 : F))) = 0 ∧
  (w.v82 * (w.v0 - w.v80)) = 0 ∧
  (w.v85 * (w.v85 - (1 : F))) = 0 ∧
  (((((w.v82 * w.v1) + (((1 : F) - w.v82) * w.v0)) - ((w.v82 * w.v81) + (((1 : F) - w.v82) * w.v80))) - (1 : F)) - ((w.v83 + (w.v84 * (65536 : F))) + (w.v85 * (16777216 : F)))) = 0 ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((65535 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v35).val ≤ ((255 : F)).val ∧
  (w.v406 - (w.v3 + (4 : F))) = 0 ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v35).val ≤ ((255 : F)).val ∧
  (w.v49).val ≤ ((65535 : F)).val ∧
  (w.v50).val ≤ ((255 : F)).val ∧
  (w.v42).val ≤ ((255 : F)).val ∧
  (w.v43).val ≤ ((255 : F)).val ∧
  (w.v44).val ≤ ((255 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v407 - (w.v3 + (8 : F))) = 0 ∧
  (w.v42).val ≤ ((255 : F)).val ∧
  (w.v43).val ≤ ((255 : F)).val ∧
  (w.v44).val ≤ ((255 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v59).val ≤ ((65535 : F)).val ∧
  (w.v60).val ≤ ((255 : F)).val ∧
  (w.v52).val ≤ ((255 : F)).val ∧
  (w.v53).val ≤ ((255 : F)).val ∧
  (w.v54).val ≤ ((255 : F)).val ∧
  (w.v55).val ≤ ((255 : F)).val ∧
  (w.v408 - (w.v3 + (12 : F))) = 0 ∧
  (w.v52).val ≤ ((255 : F)).val ∧
  (w.v53).val ≤ ((255 : F)).val ∧
  (w.v54).val ≤ ((255 : F)).val ∧
  (w.v55).val ≤ ((255 : F)).val ∧
  (w.v69).val ≤ ((65535 : F)).val ∧
  (w.v70).val ≤ ((255 : F)).val ∧
  (w.v62).val ≤ ((255 : F)).val ∧
  (w.v63).val ≤ ((255 : F)).val ∧
  (w.v64).val ≤ ((255 : F)).val ∧
  (w.v65).val ≤ ((255 : F)).val ∧
  (w.v409 - (w.v3 + (16 : F))) = 0 ∧
  (w.v62).val ≤ ((255 : F)).val ∧
  (w.v63).val ≤ ((255 : F)).val ∧
  (w.v64).val ≤ ((255 : F)).val ∧
  (w.v65).val ≤ ((255 : F)).val ∧
  (w.v83).val ≤ ((65535 : F)).val

def constraints_2 (w : W) : Prop :=
  (w.v84).val ≤ ((255 : F)).val ∧
  (w.v72).val ≤ ((255 : F)).val ∧
  (w.v73).val ≤ ((255 : F)).val ∧
  (w.v74).val ≤ ((255 : F)).val ∧
  (w.v75).val ≤ ((255 : F)).val ∧
  (w.v76).val ≤ ((255 : F)).val ∧
  (w.v77).val ≤ ((255 : F)).val ∧
  (w.v78).val ≤ ((255 : F)).val ∧
  (w.v79).val ≤ ((255 : F)).val ∧
  (w.v72).val ≤ ((255 : F)).val ∧
  (w.v73).val ≤ ((255 : F)).val ∧
  (w.v74).val ≤ ((255 : F)).val ∧
  (w.v75).val ≤ ((255 : F)).val ∧
  (w.v410 - (w.v3 + (20 : F))) = 0 ∧
  (w.v411 - (w.v3 + (4 : F))) = 0 ∧
  (w.v412 - (w.v3 + (8 : F))) = 0 ∧
  (w.v413 - (w.v3 + (12 : F))) = 0 ∧
  (w.v414 - (w.v3 + (16 : F))) = 0 ∧
  (w.v415 - ((w.v3 + (20 : F)) + (w.v5 * (68 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w

def inputs (w : W) : List F :=
  [w.v3, w.v22, w.v23, w.v24, w.v25, w.v406, w.v32, w.v33, w.v34, w.v35, w.v407, w.v42, w.v43, w.v44, w.v45, w.v408, w.v52, w.v53, w.v54, w.v55, w.v409, w.v62, w.v63, w.v64, w.v65, w.v4, w.v72, w.v73, w.v74, w.v75, w.v0, w.v1, w.v5, w.v415, w.v6, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v20, w.v21]
def outputs (w : W) : List F :=
  [w.v0, w.v1, w.v5, w.v410, w.v6, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v20, w.v21, w.v3, w.v22, w.v23, w.v24, w.v25, w.v411, w.v32, w.v33, w.v34, w.v35, w.v412, w.v42, w.v43, w.v44, w.v45, w.v413, w.v52, w.v53, w.v54, w.v55, w.v414, w.v62, w.v63, w.v64, w.v65, w.v4, w.v76, w.v77, w.v78, w.v79]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2]

end BooleanCircuitGarbleControl

end ZirenDet.Chips.BooleanCircuitGarbleControl
