/-
  Generated by `cargo run -p zkm-picus -- --chip Branch --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.Branch

open ZirenDet

/-! ### Module `Branch__is_beq` -/
namespace Branch_is_beq

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  v346 : F
  v347 : F
  v348 : F
  v349 : F
  v350 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (21 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v48 * (w.v53 - (1 : F))) = 0 ∧
  ((w.v48 - (1 : F)) * w.v53) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v346 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v347 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v348 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v349 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v350 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v349, w.v350]
def outputs (w : W) : List F :=
  [w.v0, w.v346, w.v347, w.v348, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_beq

/-! ### Module `Branch__is_bgez` -/
namespace Branch_is_bgez

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  /-- `msb_a_54` -/
  v54 : F
  /-- `a_gt_0_55` -/
  v55 : F
  v374 : F
  v375 : F
  v376 : F
  v377 : F
  v378 : F
  v379 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (22 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v55 - (((1 : F) - w.v54) * ((1 : F) - w.v53))) = 0 ∧
  (w.v48 * w.v54) = 0 ∧
  ((w.v48 - (1 : F)) * (w.v54 - (1 : F))) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v374 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v375 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v376 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v377).val ≤ ((127 : F)).val ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v18 - ((w.v54 * (128 : F)) + w.v377)) = 0 ∧
  (w.v378 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v379 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v378, w.v379]
def outputs (w : W) : List F :=
  [w.v0, w.v374, w.v375, w.v376, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_bgez

/-! ### Module `Branch__is_bgtz` -/
namespace Branch_is_bgtz

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  /-- `msb_a_54` -/
  v54 : F
  /-- `a_gt_0_55` -/
  v55 : F
  v368 : F
  v369 : F
  v370 : F
  v371 : F
  v372 : F
  v373 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (23 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v55 - (((1 : F) - w.v54) * ((1 : F) - w.v53))) = 0 ∧
  (w.v48 * (w.v55 - (1 : F))) = 0 ∧
  ((w.v48 - (1 : F)) * w.v55) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v368 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v369 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v370 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v371).val ≤ ((127 : F)).val ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v18 - ((w.v54 * (128 : F)) + w.v371)) = 0 ∧
  (w.v372 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v373 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v372, w.v373]
def outputs (w : W) : List F :=
  [w.v0, w.v368, w.v369, w.v370, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_bgtz

/-! ### Module `Branch__is_blez` -/
namespace Branch_is_blez

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  /-- `msb_a_54` -/
  v54 : F
  /-- `a_gt_0_55` -/
  v55 : F
  v362 : F
  v363 : F
  v364 : F
  v365 : F
  v366 : F
  v367 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (24 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v55 - (((1 : F) - w.v54) * ((1 : F) - w.v53))) = 0 ∧
  (w.v48 * w.v55) = 0 ∧
  ((w.v48 - (1 : F)) * (w.v55 - (1 : F))) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v362 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v363 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v364 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v365).val ≤ ((127 : F)).val ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v18 - ((w.v54 * (128 : F)) + w.v365)) = 0 ∧
  (w.v366 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v367 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v366, w.v367]
def outputs (w : W) : List F :=
  [w.v0, w.v362, w.v363, w.v364, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_blez

/-! ### Module `Branch__is_bltz` -/
namespace Branch_is_bltz

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  /-- `msb_a_54` -/
  v54 : F
  /-- `a_gt_0_55` -/
  v55 : F
  v356 : F
  v357 : F
  v358 : F
  v359 : F
  v360 : F
  v361 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (25 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v55 - (((1 : F) - w.v54) * ((1 : F) - w.v53))) = 0 ∧
  (w.v48 * (w.v54 - (1 : F))) = 0 ∧
  ((w.v48 - (1 : F)) * w.v54) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v356 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v357 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v358 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v359).val ≤ ((127 : F)).val ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v18 - ((w.v54 * (128 : F)) + w.v359)) = 0 ∧
  (w.v360 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v361 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v360, w.v361]
def outputs (w : W) : List F :=
  [w.v0, w.v356, w.v357, w.v358, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_bltz

/-! ### Module `Branch__is_bne` -/
namespace Branch_is_bne

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `pc_27` -/
  v27 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  v351 : F
  v352 : F
  v353 : F
  v354 : F
  v355 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v3 - (26 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F))))) = 0 ∧
  (w.v48 * (w.v33 - w.v37)) = 0 ∧
  (w.v48 * (w.v34 - w.v38)) = 0 ∧
  (w.v48 * (w.v35 - w.v39)) = 0 ∧
  (w.v48 * (w.v36 - w.v40)) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F)))) = 0 ∧
  (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50))) = 0 ∧
  (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F)))) = 0 ∧
  (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52))) = 0 ∧
  (w.v53 - (w.v49 * w.v51)) = 0 ∧
  (w.v48 * w.v53) = 0 ∧
  ((w.v48 - (1 : F)) * (w.v53 - (1 : F))) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v351 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v352 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0 ∧
  (w.v353 - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))) = 0 ∧
  (w.v31).val < ((127 : F)).val ∧
  (w.v40).val < ((127 : F)).val ∧
  ((w.v28 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v29 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v30 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v31 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v6 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v7 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v8 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v9 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v33 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v34 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v35 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v36 * w.v48)).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v48))).val ≤ ((255 : F)).val ∧
  (w.v354 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  (w.v355 - (((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v354, w.v355]
def outputs (w : W) : List F :=
  [w.v0, w.v351, w.v352, w.v353, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Branch_is_bne

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_3` -/
  v3 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `next_pc_28` -/
  v28 : F
  /-- `next_pc_29` -/
  v29 : F
  /-- `next_pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `next_pc_range_checker_32` -/
  v32 : F
  /-- `target_add_33` -/
  v33 : F
  /-- `target_add_34` -/
  v34 : F
  /-- `target_add_35` -/
  v35 : F
  /-- `target_add_36` -/
  v36 : F
  /-- `next_next_pc_37` -/
  v37 : F
  /-- `next_next_pc_38` -/
  v38 : F
  /-- `next_next_pc_39` -/
  v39 : F
  /-- `next_next_pc_40` -/
  v40 : F
  /-- `next_next_pc_range_checker_41` -/
  v41 : F
  /-- `is_beq_42` -/
  v42 : F
  /-- `is_bne_43` -/
  v43 : F
  /-- `is_bltz_44` -/
  v44 : F
  /-- `is_blez_45` -/
  v45 : F
  /-- `is_bgtz_46` -/
  v46 : F
  /-- `is_bgez_47` -/
  v47 : F
  /-- `is_branching_48` -/
  v48 : F
  /-- `eq_lo_49` -/
  v49 : F
  /-- `eq_lo_inv_50` -/
  v50 : F
  /-- `eq_hi_51` -/
  v51 : F
  /-- `eq_hi_inv_52` -/
  v52 : F
  /-- `a_eq_b_53` -/
  v53 : F
  /-- `msb_a_54` -/
  v54 : F
  /-- `a_gt_0_55` -/
  v55 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v42 * (w.v42 - (1 : F))) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v45 * (w.v45 - (1 : F))) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v3 - ((((((w.v42 * (21 : F)) + (w.v43 * (26 : F))) + (w.v44 * (25 : F))) + (w.v47 * (22 : F))) + (w.v45 * (24 : F))) + (w.v46 * (23 : F))))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F))) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v15 - w.v11)) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v16 - w.v12)) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v17 - w.v13)) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v18 - w.v14)) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F)) * w.v32) = 0 ∧
  (w.v32 * (w.v31 - (127 : F))) = 0 ∧
  (w.v32 * ((w.v28 + w.v29) + w.v30)) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F)) * w.v41) = 0 ∧
  (w.v41 * (w.v40 - (127 : F))) = 0 ∧
  (w.v41 * ((w.v37 + w.v38) + w.v39)) = 0 ∧
  (w.v48 * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) * ((((w.v28 + w.v6) - w.v33) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v31 + w.v9) - w.v36) + ((((w.v30 + w.v8) - w.v35) + ((((w.v29 + w.v7) - w.v34) + (((w.v28 + w.v6) - w.v33) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v48 * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * ((w.v48 - (1 : F)) * (((((w.v28 + (w.v29 * (256 : F))) + (w.v30 * (65536 : F))) + (w.v31 * (16777216 : F))) + (4 : F)) - (((w.v37 + (w.v38 * (256 : F))) + (w.v39 * (65536 : F))) + (w.v40 * (16777216 : F)))))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v48 * (w.v33 - w.v37))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v48 * (w.v34 - w.v38))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v48 * (w.v35 - w.v39))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v48 * (w.v36 - w.v40))) = 0 ∧
  (((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) - (1 : F)) * w.v48) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v48 * (w.v48 - (1 : F)))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v49 * ((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v49 - ((1 : F) - (((w.v15 - w.v21) + ((w.v16 - w.v22) * (256 : F))) * w.v50)))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v51 * ((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v51 - ((1 : F) - (((w.v17 - w.v23) + ((w.v18 - w.v24) * (256 : F))) * w.v52)))) = 0 ∧
  ((((((w.v42 + w.v43) + w.v44) + w.v47) + w.v45) + w.v46) * (w.v53 - (w.v49 * w.v51))) = 0 ∧
  ((((w.v44 + w.v45) + w.v46) + w.v47) * (w.v55 - (((1 : F) - w.v54) * ((1 : F) - w.v53)))) = 0 ∧
  ((w.v42 * w.v48) * (w.v53 - (1 : F))) = 0 ∧
  (w.v42 * ((w.v48 - (1 : F)) * w.v53)) = 0 ∧
  ((w.v43 * w.v48) * w.v53) = 0 ∧
  (w.v43 * ((w.v48 - (1 : F)) * (w.v53 - (1 : F)))) = 0

def constraints_1 (w : W) : Prop :=
  ((w.v44 * w.v48) * (w.v54 - (1 : F))) = 0 ∧
  (w.v44 * ((w.v48 - (1 : F)) * w.v54)) = 0 ∧
  ((w.v45 * w.v48) * w.v55) = 0 ∧
  (w.v45 * ((w.v48 - (1 : F)) * (w.v55 - (1 : F)))) = 0 ∧
  ((w.v46 * w.v48) * (w.v55 - (1 : F))) = 0 ∧
  (w.v46 * ((w.v48 - (1 : F)) * w.v55)) = 0 ∧
  ((w.v47 * w.v48) * w.v54) = 0 ∧
  (w.v47 * ((w.v48 - (1 : F)) * (w.v54 - (1 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v42, w.v43, w.v44, w.v45, w.v46, w.v47]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v42 * (w.v42 - (1 : F))) = 0 ∧
    (w.v43 * (w.v43 - (1 : F))) = 0 ∧
    (w.v44 * (w.v44 - (1 : F))) = 0 ∧
    (w.v45 * (w.v45 - (1 : F))) = 0 ∧
    (w.v46 * (w.v46 - (1 : F))) = 0 ∧
    (w.v47 * (w.v47 - (1 : F))) = 0 ∧
    ((((((w.v42 + w.v43) + w.v44) + w.v45) + w.v46) + w.v47)).val < ((2 : F)).val := by
  picus_det [constraints_0, constraints_1]

end top

end ZirenDet.Chips.Branch
