/-
  Generated by `cargo run -p zkm-picus -- --chip Byte --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

namespace ZirenDet.Chips.Byte

open ZirenDet

/-! ### Module `Byte` -/
namespace Byte

/-- Abstract helper: 0 input(s), 0 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end Byte

end ZirenDet.Chips.Byte
