/-
  Generated by `cargo run -p zkm-picus -- --chip CloClz --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.CloClz

open ZirenDet

/-! ### Module `byte_shr_carry` -/
namespace byte_shr_carry

/-- Abstract helper: 2 input(s), 2 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_shr_carry

/-! ### Module `CloClz__is_clz` -/
namespace CloClz_is_clz

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `a_2` -/
  v2 : F
  /-- `a_3` -/
  v3 : F
  /-- `a_4` -/
  v4 : F
  /-- `a_5` -/
  v5 : F
  /-- `bb_6` -/
  v6 : F
  /-- `bb_7` -/
  v7 : F
  /-- `bb_8` -/
  v8 : F
  /-- `bb_9` -/
  v9 : F
  /-- `is_bb_zero_10` -/
  v10 : F
  /-- `srl_11` -/
  v11 : F
  /-- `srl_12` -/
  v12 : F
  /-- `srl_13` -/
  v13 : F
  /-- `srl_14` -/
  v14 : F
  /-- `srl_15` -/
  v15 : F
  /-- `srl_16` -/
  v16 : F
  /-- `srl_17` -/
  v17 : F
  /-- `srl_18` -/
  v18 : F
  /-- `srl_19` -/
  v19 : F
  /-- `srl_20` -/
  v20 : F
  /-- `srl_21` -/
  v21 : F
  /-- `srl_22` -/
  v22 : F
  /-- `srl_23` -/
  v23 : F
  /-- `srl_24` -/
  v24 : F
  /-- `srl_25` -/
  v25 : F
  /-- `srl_26` -/
  v26 : F
  /-- `srl_27` -/
  v27 : F
  /-- `srl_28` -/
  v28 : F
  /-- `srl_29` -/
  v29 : F
  /-- `srl_30` -/
  v30 : F
  /-- `srl_31` -/
  v31 : F
  /-- `srl_32` -/
  v32 : F
  /-- `srl_33` -/
  v33 : F
  /-- `srl_34` -/
  v34 : F
  /-- `srl_35` -/
  v35 : F
  /-- `srl_36` -/
  v36 : F
  /-- `srl_37` -/
  v37 : F
  /-- `srl_38` -/
  v38 : F
  /-- `srl_39` -/
  v39 : F
  /-- `srl_40` -/
  v40 : F
  /-- `srl_41` -/
  v41 : F
  /-- `srl_42` -/
  v42 : F
  /-- `srl_43` -/
  v43 : F
  /-- `srl_44` -/
  v44 : F
  /-- `srl_45` -/
  v45 : F
  /-- `srl_46` -/
  v46 : F
  /-- `srl_47` -/
  v47 : F
  /-- `srl_48` -/
  v48 : F
  /-- `srl_49` -/
  v49 : F
  /-- `srl_50` -/
  v50 : F
  /-- `srl_51` -/
  v51 : F
  /-- `srl_52` -/
  v52 : F
  /-- `srl_53` -/
  v53 : F
  /-- `srl_54` -/
  v54 : F
  /-- `srl_55` -/
  v55 : F
  /-- `srl_56` -/
  v56 : F
  /-- `srl_57` -/
  v57 : F
  /-- `srl_58` -/
  v58 : F
  /-- `srl_59` -/
  v59 : F
  /-- `srl_60` -/
  v60 : F
  /-- `srl_61` -/
  v61 : F
  /-- `srl_62` -/
  v62 : F
  /-- `srl_63` -/
  v63 : F
  /-- `frame_66` -/
  v66 : F
  /-- `frame_67` -/
  v67 : F
  /-- `frame_68` -/
  v68 : F
  /-- `frame_69` -/
  v69 : F
  /-- `frame_70` -/
  v70 : F
  /-- `frame_71` -/
  v71 : F
  /-- `frame_72` -/
  v72 : F
  /-- `frame_73` -/
  v73 : F
  /-- `frame_74` -/
  v74 : F
  /-- `frame_75` -/
  v75 : F
  /-- `frame_76` -/
  v76 : F
  /-- `frame_77` -/
  v77 : F
  /-- `frame_78` -/
  v78 : F
  /-- `frame_79` -/
  v79 : F
  /-- `frame_80` -/
  v80 : F
  /-- `frame_81` -/
  v81 : F
  /-- `frame_82` -/
  v82 : F
  /-- `frame_83` -/
  v83 : F
  /-- `frame_84` -/
  v84 : F
  /-- `frame_85` -/
  v85 : F
  /-- `frame_86` -/
  v86 : F
  /-- `frame_87` -/
  v87 : F
  /-- `frame_88` -/
  v88 : F
  /-- `frame_89` -/
  v89 : F
  /-- `frame_90` -/
  v90 : F
  /-- `frame_91` -/
  v91 : F
  /-- `frame_92` -/
  v92 : F
  v420 : F
  v421 : F
  v422 : F
  v423 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v87 - w.v6) = 0 ∧
  (w.v88 - w.v7) = 0 ∧
  (w.v89 - w.v8) = 0 ∧
  (w.v90 - w.v9) = 0 ∧
  w.v3 = 0 ∧
  w.v4 = 0 ∧
  w.v5 = 0 ∧
  ((w.v76 - (1 : F)) * (w.v2 - w.v81)) = 0 ∧
  ((w.v76 - (1 : F)) * (w.v3 - w.v82)) = 0 ∧
  ((w.v76 - (1 : F)) * (w.v4 - w.v83)) = 0 ∧
  ((w.v76 - (1 : F)) * (w.v5 - w.v84)) = 0 ∧
  (w.v69 - (19 : F)) = 0 ∧
  (w.v76 * w.v81) = 0 ∧
  (w.v76 * w.v82) = 0 ∧
  (w.v76 * w.v83) = 0 ∧
  (w.v76 * w.v84) = 0 ∧
  (w.v10 * (w.v10 - (1 : F))) = 0 ∧
  (w.v10 * (((w.v6 + (w.v7 * (256 : F))) + (w.v8 * (65536 : F))) + (w.v9 * (16777216 : F)))) = 0 ∧
  (w.v10 * w.v9) = 0 ∧
  (w.v10 * (w.v2 - (32 : F))) = 0 ∧
  (((1 : F) - w.v10) * ((((((((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) + (w.v59 * (8 : F))) + (w.v60 * (16 : F))) + (w.v61 * (32 : F))) + (w.v62 * (64 : F))) + (w.v63 * (128 : F))) - ((31 : F) - w.v2))) = 0 ∧
  (w.v11 * ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))) = 0 ∧
  (w.v12 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (1 : F))) = 0 ∧
  (w.v13 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (2 : F))) = 0 ∧
  (w.v14 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (3 : F))) = 0 ∧
  (w.v15 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (4 : F))) = 0 ∧
  (w.v16 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (5 : F))) = 0 ∧
  (w.v17 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (6 : F))) = 0 ∧
  (w.v18 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (7 : F))) = 0 ∧
  (((1 : F) - w.v10) * ((((((((w.v11 + w.v12) + w.v13) + w.v14) + w.v15) + w.v16) + w.v17) + w.v18) - (1 : F))) = 0 ∧
  (w.v19 * (w.v59 + (w.v60 * (2 : F)))) = 0 ∧
  (w.v20 * ((w.v59 + (w.v60 * (2 : F))) - (1 : F))) = 0 ∧
  (w.v21 * ((w.v59 + (w.v60 * (2 : F))) - (2 : F))) = 0 ∧
  (w.v22 * ((w.v59 + (w.v60 * (2 : F))) - (3 : F))) = 0 ∧
  (((1 : F) - w.v10) * ((((w.v19 + w.v20) + w.v21) + w.v22) - (1 : F))) = 0 ∧
  (w.v19 * (w.v23 - w.v6)) = 0 ∧
  (w.v19 * (w.v24 - w.v7)) = 0 ∧
  (w.v19 * (w.v25 - w.v8)) = 0 ∧
  (w.v19 * (w.v26 - w.v9)) = 0 ∧
  (w.v19 * w.v27) = 0 ∧
  (w.v19 * w.v28) = 0 ∧
  (w.v19 * w.v29) = 0 ∧
  (w.v19 * w.v30) = 0 ∧
  (w.v20 * (w.v23 - w.v7)) = 0 ∧
  (w.v20 * (w.v24 - w.v8)) = 0 ∧
  (w.v20 * (w.v25 - w.v9)) = 0 ∧
  (w.v20 * w.v26) = 0 ∧
  (w.v20 * w.v27) = 0

def constraints_1 (w : W) : Prop :=
  (w.v20 * w.v28) = 0 ∧
  (w.v20 * w.v29) = 0 ∧
  (w.v21 * (w.v23 - w.v8)) = 0 ∧
  (w.v21 * (w.v24 - w.v9)) = 0 ∧
  (w.v21 * w.v25) = 0 ∧
  (w.v21 * w.v26) = 0 ∧
  (w.v21 * w.v27) = 0 ∧
  (w.v21 * w.v28) = 0 ∧
  (w.v22 * (w.v23 - w.v9)) = 0 ∧
  (w.v22 * w.v24) = 0 ∧
  (w.v22 * w.v25) = 0 ∧
  (w.v22 * w.v26) = 0 ∧
  (w.v22 * w.v27) = 0 ∧
  (w.v54 - w.v38) = 0 ∧
  ((w.v53 + (w.v46 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v37) = 0 ∧
  ((w.v52 + (w.v45 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v36) = 0 ∧
  ((w.v51 + (w.v44 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v35) = 0 ∧
  ((w.v50 + (w.v43 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v34) = 0 ∧
  ((w.v49 + (w.v42 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v33) = 0 ∧
  ((w.v48 + (w.v41 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v32) = 0 ∧
  ((w.v47 + (w.v40 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v31) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v19 * (w.v19 - (1 : F))) = 0 ∧
  (w.v20 * (w.v20 - (1 : F))) = 0 ∧
  (w.v21 * (w.v21 - (1 : F))) = 0 ∧
  (w.v22 * (w.v22 - (1 : F))) = 0 ∧
  (w.v11 * (w.v11 - (1 : F))) = 0 ∧
  (w.v12 * (w.v12 - (1 : F))) = 0 ∧
  (w.v13 * (w.v13 - (1 : F))) = 0 ∧
  (w.v14 * (w.v14 - (1 : F))) = 0 ∧
  (w.v15 * (w.v15 - (1 : F))) = 0 ∧
  (w.v16 * (w.v16 - (1 : F))) = 0 ∧
  (w.v17 * (w.v17 - (1 : F))) = 0 ∧
  (w.v18 * (w.v18 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v58 * (w.v58 - (1 : F))) = 0 ∧
  (w.v59 * (w.v59 - (1 : F))) = 0 ∧
  (w.v60 * (w.v60 - (1 : F))) = 0 ∧
  (w.v61 * (w.v61 - (1 : F))) = 0 ∧
  (w.v62 * (w.v62 - (1 : F))) = 0 ∧
  (w.v63 * (w.v63 - (1 : F))) = 0 ∧
  (((1 : F) - w.v10) * (w.v31 - (1 : F))) = 0 ∧
  (((1 : F) - w.v10) * w.v32) = 0 ∧
  (((1 : F) - w.v10) * w.v33) = 0 ∧
  (((1 : F) - w.v10) * w.v34) = 0 ∧
  (w.v6).val ≤ ((255 : F)).val ∧
  (w.v7).val ≤ ((255 : F)).val

def constraints_2 (w : W) : Prop :=
  (w.v8).val ≤ ((255 : F)).val ∧
  (w.v9).val ≤ ((255 : F)).val ∧
  (w.v2).val < ((33 : F)).val ∧
  (w.v66).val ≤ ((65535 : F)).val ∧
  (w.v67).val ≤ ((65535 : F)).val ∧
  (w.v68).val ≤ ((511 : F)).val ∧
  (w.v92).val ≤ ((65535 : F)).val ∧
  ((((((((w.v68 * (65536 : F)) + w.v67) + (2 : F)) - w.v91) - (1 : F)) - w.v92) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v87).val ≤ ((255 : F)).val ∧
  (w.v88).val ≤ ((255 : F)).val ∧
  (w.v89).val ≤ ((255 : F)).val ∧
  (w.v90).val ≤ ((255 : F)).val ∧
  (w.v86).val ≤ ((65535 : F)).val ∧
  ((((((((w.v68 * (65536 : F)) + w.v67) + (3 : F)) - w.v85) - (1 : F)) - w.v86) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v77).val ≤ ((255 : F)).val ∧
  (w.v78).val ≤ ((255 : F)).val ∧
  (w.v79).val ≤ ((255 : F)).val ∧
  (w.v80).val ≤ ((255 : F)).val ∧
  (w.v81).val ≤ ((255 : F)).val ∧
  (w.v82).val ≤ ((255 : F)).val ∧
  (w.v83).val ≤ ((255 : F)).val ∧
  (w.v84).val ≤ ((255 : F)).val ∧
  (w.v420 - (((w.v68 * (65536 : F)) + w.v67) + (5 : F))) = 0 ∧
  (w.v421 - (w.v1 + (4 : F))) = 0 ∧
  ((w.v422 * ((1 : F) - w.v10))).val ≤ ((127 : F)).val ∧
  ((((1 : F) - w.v10) * w.v55) * (w.v55 - (1 : F))) = 0 ∧
  (((1 : F) - w.v10) * (w.v9 - ((w.v55 * (128 : F)) + w.v422))) = 0 ∧
  ((w.v23 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v24 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v25 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v26 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v27 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v28 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v29 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v30 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v31 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v32 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v33 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v34 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v35 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v36 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v37 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v38 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v39 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v40 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v41 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v42 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v43 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val

def constraints_3 (w : W) : Prop :=
  ((w.v44 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v45 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v46 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v47 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v48 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v49 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v50 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v51 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v52 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v53 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  ((w.v54 * ((1 : F) - w.v10))).val ≤ ((255 : F)).val ∧
  (w.v423 - ((w.v68 * (65536 : F)) + w.v67)) = 0 ∧
  byte_shr_carry.rel [w.v30, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v54, w.v46] ∧
  byte_shr_carry.rel [w.v29, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v53, w.v45] ∧
  byte_shr_carry.rel [w.v28, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v52, w.v44] ∧
  byte_shr_carry.rel [w.v27, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v51, w.v43] ∧
  byte_shr_carry.rel [w.v26, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v50, w.v42] ∧
  byte_shr_carry.rel [w.v25, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v49, w.v41] ∧
  byte_shr_carry.rel [w.v24, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v48, w.v40] ∧
  byte_shr_carry.rel [w.v23, ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))] [w.v47, w.v39]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w ∧
  constraints_3 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v0 = program.pc, v69 = program.opcode, v70 = program.op_a, v71 = program.op_b[0], v72 = program.op_c[0], v73 = program.op_c[1], v74 = program.op_c[2], v75 = program.op_c[3], v76 = program.op_a_0, v87 = mem_read[0].val[0], v88 = mem_read[0].val[1], v89 = mem_read[0].val[2], v90 = mem_read[0].val[3], v77 = mem_read[1].val[0], v78 = mem_read[1].val[1], v79 = mem_read[1].val[2], v80 = mem_read[1].val[3], v66 = state_recv[0], v423 = state_recv[1], v1 = state_recv[3]
  outputs: v66 = state_send[0], v420 = state_send[1], v1 = state_send[2], v421 = state_send[3], v71 = mem_write[0].addr, v87 = mem_write[0].val[0], v88 = mem_write[0].val[1], v89 = mem_write[0].val[2], v90 = mem_write[0].val[3], v70 = mem_write[1].addr, v81 = mem_write[1].val[0], v82 = mem_write[1].val[1], v83 = mem_write[1].val[2], v84 = mem_write[1].val[3] -/
def input_origins : List String := ["program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_c[1]", "program.op_c[2]", "program.op_c[3]", "program.op_a_0", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]"]
def in_program_pc (w : W) : F := w.v0
def in_program_opcode (w : W) : F := w.v69
def in_program_op_a (w : W) : F := w.v70
def in_program_op_b (w : W) : F := w.v71
def in_program_op_c (w : W) : List F := [w.v72, w.v73, w.v74, w.v75]
def in_program_op_a_0 (w : W) : F := w.v76
def in_mem_read_0_val (w : W) : List F := [w.v87, w.v88, w.v89, w.v90]
def in_mem_read_1_val (w : W) : List F := [w.v77, w.v78, w.v79, w.v80]
def in_state_recv (w : W) : List F := [w.v66, w.v423, w.v1]
def out_state_send (w : W) : List F := [w.v66, w.v420, w.v1, w.v421]
def out_mem_write_0_addr (w : W) : F := w.v71
def out_mem_write_0_val (w : W) : List F := [w.v87, w.v88, w.v89, w.v90]
def out_mem_write_1_addr (w : W) : F := w.v70
def out_mem_write_1_val (w : W) : List F := [w.v81, w.v82, w.v83, w.v84]

def inputs (w : W) : List F :=
  [w.v0, w.v69, w.v70, w.v71, w.v72, w.v73, w.v74, w.v75, w.v76, w.v87, w.v88, w.v89, w.v90, w.v77, w.v78, w.v79, w.v80, w.v66, w.v423, w.v1]
def outputs (w : W) : List F :=
  [w.v66, w.v420, w.v1, w.v421, w.v71, w.v87, w.v88, w.v89, w.v90, w.v70, w.v81, w.v82, w.v83, w.v84]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_shr_carry : ∀ i o o', byte_shr_carry.rel i o → byte_shr_carry.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2, constraints_3]

end CloClz_is_clz

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `a_2` -/
  v2 : F
  /-- `a_3` -/
  v3 : F
  /-- `a_4` -/
  v4 : F
  /-- `a_5` -/
  v5 : F
  /-- `bb_6` -/
  v6 : F
  /-- `bb_7` -/
  v7 : F
  /-- `bb_8` -/
  v8 : F
  /-- `bb_9` -/
  v9 : F
  /-- `is_bb_zero_10` -/
  v10 : F
  /-- `srl_11` -/
  v11 : F
  /-- `srl_12` -/
  v12 : F
  /-- `srl_13` -/
  v13 : F
  /-- `srl_14` -/
  v14 : F
  /-- `srl_15` -/
  v15 : F
  /-- `srl_16` -/
  v16 : F
  /-- `srl_17` -/
  v17 : F
  /-- `srl_18` -/
  v18 : F
  /-- `srl_19` -/
  v19 : F
  /-- `srl_20` -/
  v20 : F
  /-- `srl_21` -/
  v21 : F
  /-- `srl_22` -/
  v22 : F
  /-- `srl_23` -/
  v23 : F
  /-- `srl_24` -/
  v24 : F
  /-- `srl_25` -/
  v25 : F
  /-- `srl_26` -/
  v26 : F
  /-- `srl_27` -/
  v27 : F
  /-- `srl_28` -/
  v28 : F
  /-- `srl_29` -/
  v29 : F
  /-- `srl_30` -/
  v30 : F
  /-- `srl_31` -/
  v31 : F
  /-- `srl_32` -/
  v32 : F
  /-- `srl_33` -/
  v33 : F
  /-- `srl_34` -/
  v34 : F
  /-- `srl_35` -/
  v35 : F
  /-- `srl_36` -/
  v36 : F
  /-- `srl_37` -/
  v37 : F
  /-- `srl_38` -/
  v38 : F
  /-- `srl_40` -/
  v40 : F
  /-- `srl_41` -/
  v41 : F
  /-- `srl_42` -/
  v42 : F
  /-- `srl_43` -/
  v43 : F
  /-- `srl_44` -/
  v44 : F
  /-- `srl_45` -/
  v45 : F
  /-- `srl_46` -/
  v46 : F
  /-- `srl_47` -/
  v47 : F
  /-- `srl_48` -/
  v48 : F
  /-- `srl_49` -/
  v49 : F
  /-- `srl_50` -/
  v50 : F
  /-- `srl_51` -/
  v51 : F
  /-- `srl_52` -/
  v52 : F
  /-- `srl_53` -/
  v53 : F
  /-- `srl_54` -/
  v54 : F
  /-- `srl_55` -/
  v55 : F
  /-- `srl_56` -/
  v56 : F
  /-- `srl_57` -/
  v57 : F
  /-- `srl_58` -/
  v58 : F
  /-- `srl_59` -/
  v59 : F
  /-- `srl_60` -/
  v60 : F
  /-- `srl_61` -/
  v61 : F
  /-- `srl_62` -/
  v62 : F
  /-- `srl_63` -/
  v63 : F
  /-- `is_clz_64` -/
  v64 : F
  /-- `is_real_65` -/
  v65 : F
  /-- `frame_69` -/
  v69 : F
  /-- `frame_76` -/
  v76 : F
  /-- `frame_81` -/
  v81 : F
  /-- `frame_82` -/
  v82 : F
  /-- `frame_83` -/
  v83 : F
  /-- `frame_84` -/
  v84 : F
  /-- `frame_87` -/
  v87 : F
  /-- `frame_88` -/
  v88 : F
  /-- `frame_89` -/
  v89 : F
  /-- `frame_90` -/
  v90 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((w.v65 - w.v64) * ((w.v87 + w.v6) - (255 : F))) = 0 ∧
  (w.v64 * (w.v87 - w.v6)) = 0 ∧
  ((w.v65 - w.v64) * ((w.v88 + w.v7) - (255 : F))) = 0 ∧
  (w.v64 * (w.v88 - w.v7)) = 0 ∧
  ((w.v65 - w.v64) * ((w.v89 + w.v8) - (255 : F))) = 0 ∧
  (w.v64 * (w.v89 - w.v8)) = 0 ∧
  ((w.v65 - w.v64) * ((w.v90 + w.v9) - (255 : F))) = 0 ∧
  (w.v64 * (w.v90 - w.v9)) = 0 ∧
  (w.v65 * w.v3) = 0 ∧
  (w.v65 * w.v4) = 0 ∧
  (w.v65 * w.v5) = 0 ∧
  (w.v65 * ((w.v76 - (1 : F)) * (w.v2 - w.v81))) = 0 ∧
  (w.v65 * ((w.v76 - (1 : F)) * (w.v3 - w.v82))) = 0 ∧
  (w.v65 * ((w.v76 - (1 : F)) * (w.v4 - w.v83))) = 0 ∧
  (w.v65 * ((w.v76 - (1 : F)) * (w.v5 - w.v84))) = 0 ∧
  (w.v65 * (w.v69 - ((w.v64 * (19 : F)) + ((w.v65 - w.v64) * (20 : F))))) = 0 ∧
  (w.v65 * (w.v65 - (1 : F))) = 0 ∧
  (w.v76 * w.v81) = 0 ∧
  (w.v76 * w.v82) = 0 ∧
  (w.v76 * w.v83) = 0 ∧
  (w.v76 * w.v84) = 0 ∧
  (w.v65 * (w.v65 - (1 : F))) = 0 ∧
  (w.v10 * (w.v10 - (1 : F))) = 0 ∧
  (w.v10 * (((w.v6 + (w.v7 * (256 : F))) + (w.v8 * (65536 : F))) + (w.v9 * (16777216 : F)))) = 0 ∧
  (w.v10 * w.v9) = 0 ∧
  (w.v10 * (w.v2 - (32 : F))) = 0 ∧
  ((w.v65 - w.v10) * ((((((((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) + (w.v59 * (8 : F))) + (w.v60 * (16 : F))) + (w.v61 * (32 : F))) + (w.v62 * (64 : F))) + (w.v63 * (128 : F))) - ((31 : F) - w.v2))) = 0 ∧
  (w.v11 * ((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F)))) = 0 ∧
  (w.v12 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (1 : F))) = 0 ∧
  (w.v13 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (2 : F))) = 0 ∧
  (w.v14 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (3 : F))) = 0 ∧
  (w.v15 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (4 : F))) = 0 ∧
  (w.v16 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (5 : F))) = 0 ∧
  (w.v17 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (6 : F))) = 0 ∧
  (w.v18 * (((w.v56 + (w.v57 * (2 : F))) + (w.v58 * (4 : F))) - (7 : F))) = 0 ∧
  ((w.v65 - w.v10) * ((((((((w.v11 + w.v12) + w.v13) + w.v14) + w.v15) + w.v16) + w.v17) + w.v18) - (1 : F))) = 0 ∧
  (w.v19 * (w.v59 + (w.v60 * (2 : F)))) = 0 ∧
  (w.v20 * ((w.v59 + (w.v60 * (2 : F))) - (1 : F))) = 0 ∧
  (w.v21 * ((w.v59 + (w.v60 * (2 : F))) - (2 : F))) = 0 ∧
  (w.v22 * ((w.v59 + (w.v60 * (2 : F))) - (3 : F))) = 0 ∧
  ((w.v65 - w.v10) * ((((w.v19 + w.v20) + w.v21) + w.v22) - (1 : F))) = 0 ∧
  (w.v19 * (w.v23 - w.v6)) = 0 ∧
  (w.v19 * (w.v24 - w.v7)) = 0 ∧
  (w.v19 * (w.v25 - w.v8)) = 0 ∧
  (w.v19 * (w.v26 - w.v9)) = 0 ∧
  (w.v19 * w.v27) = 0 ∧
  (w.v19 * w.v28) = 0 ∧
  (w.v19 * w.v29) = 0

def constraints_1 (w : W) : Prop :=
  (w.v19 * w.v30) = 0 ∧
  (w.v20 * (w.v23 - w.v7)) = 0 ∧
  (w.v20 * (w.v24 - w.v8)) = 0 ∧
  (w.v20 * (w.v25 - w.v9)) = 0 ∧
  (w.v20 * w.v26) = 0 ∧
  (w.v20 * w.v27) = 0 ∧
  (w.v20 * w.v28) = 0 ∧
  (w.v20 * w.v29) = 0 ∧
  (w.v21 * (w.v23 - w.v8)) = 0 ∧
  (w.v21 * (w.v24 - w.v9)) = 0 ∧
  (w.v21 * w.v25) = 0 ∧
  (w.v21 * w.v26) = 0 ∧
  (w.v21 * w.v27) = 0 ∧
  (w.v21 * w.v28) = 0 ∧
  (w.v22 * (w.v23 - w.v9)) = 0 ∧
  (w.v22 * w.v24) = 0 ∧
  (w.v22 * w.v25) = 0 ∧
  (w.v22 * w.v26) = 0 ∧
  (w.v22 * w.v27) = 0 ∧
  (w.v54 - w.v38) = 0 ∧
  ((w.v53 + (w.v46 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v37) = 0 ∧
  ((w.v52 + (w.v45 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v36) = 0 ∧
  ((w.v51 + (w.v44 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v35) = 0 ∧
  ((w.v50 + (w.v43 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v34) = 0 ∧
  ((w.v49 + (w.v42 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v33) = 0 ∧
  ((w.v48 + (w.v41 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v32) = 0 ∧
  ((w.v47 + (w.v40 * ((((((((w.v11 * (256 : F)) + (w.v12 * (128 : F))) + (w.v13 * (64 : F))) + (w.v14 * (32 : F))) + (w.v15 * (16 : F))) + (w.v16 * (8 : F))) + (w.v17 * (4 : F))) + (w.v18 * (2 : F))))) - w.v31) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v19 * (w.v19 - (1 : F))) = 0 ∧
  (w.v20 * (w.v20 - (1 : F))) = 0 ∧
  (w.v21 * (w.v21 - (1 : F))) = 0 ∧
  (w.v22 * (w.v22 - (1 : F))) = 0 ∧
  (w.v11 * (w.v11 - (1 : F))) = 0 ∧
  (w.v12 * (w.v12 - (1 : F))) = 0 ∧
  (w.v13 * (w.v13 - (1 : F))) = 0 ∧
  (w.v14 * (w.v14 - (1 : F))) = 0 ∧
  (w.v15 * (w.v15 - (1 : F))) = 0 ∧
  (w.v16 * (w.v16 - (1 : F))) = 0 ∧
  (w.v17 * (w.v17 - (1 : F))) = 0 ∧
  (w.v18 * (w.v18 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v58 * (w.v58 - (1 : F))) = 0 ∧
  (w.v59 * (w.v59 - (1 : F))) = 0 ∧
  (w.v60 * (w.v60 - (1 : F))) = 0 ∧
  (w.v61 * (w.v61 - (1 : F))) = 0 ∧
  (w.v62 * (w.v62 - (1 : F))) = 0 ∧
  (w.v63 * (w.v63 - (1 : F))) = 0

def constraints_2 (w : W) : Prop :=
  ((w.v65 - w.v10) * (w.v31 - (1 : F))) = 0 ∧
  ((w.v65 - w.v10) * w.v32) = 0 ∧
  ((w.v65 - w.v10) * w.v33) = 0 ∧
  ((w.v65 - w.v10) * w.v34) = 0 ∧
  (w.v64 * (w.v64 - (1 : F))) = 0 ∧
  (w.v65 * (w.v65 - (1 : F))) = 0 ∧
  (w.v64 * (w.v65 - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  
  outputs:  -/
def input_origins : List String := []
def output_origins : List String := []

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v64]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v64 * (w.v64 - (1 : F))) = 0 ∧
    (w.v64).val < ((2 : F)).val := by
  picus_det [constraints_0, constraints_1, constraints_2]

end top

end ZirenDet.Chips.CloClz
