/-
  Generated by `cargo run -p zkm-picus -- --chip Jump --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.Jump

open ZirenDet

/-! ### Module `Jump__is_jump` -/
namespace Jump_is_jump

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `pc_42` -/
  v42 : F
  /-- `next_pc_43` -/
  v43 : F
  /-- `next_pc_44` -/
  v44 : F
  /-- `next_pc_45` -/
  v45 : F
  /-- `next_pc_46` -/
  v46 : F
  /-- `next_pc_range_checker_47` -/
  v47 : F
  /-- `next_next_pc_48` -/
  v48 : F
  /-- `next_next_pc_49` -/
  v49 : F
  /-- `next_next_pc_50` -/
  v50 : F
  /-- `next_next_pc_51` -/
  v51 : F
  /-- `next_next_pc_range_checker_52` -/
  v52 : F
  /-- `op_a_range_checker_56` -/
  v56 : F
  v348 : F
  v349 : F
  v350 : F
  v351 : F
  v352 : F
  v353 : F
  v354 : F
  v355 : F
  v356 : F
  v357 : F
  v358 : F
  v359 : F
  v360 : F
  v361 : F
  v362 : F
  v363 : F
  v364 : F
  v365 : F
  v366 : F
  v367 : F
  v368 : F
  v369 : F
  v370 : F
  v371 : F
  v372 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v7 - (27 : F)) = 0 ∧
  (w.v18 * (w.v30 - w.v9)) = 0 ∧
  (w.v18 * (w.v31 - w.v10)) = 0 ∧
  (w.v18 * (w.v32 - w.v11)) = 0 ∧
  (w.v18 * (w.v33 - w.v12)) = 0 ∧
  (w.v19 * (w.v36 - w.v13)) = 0 ∧
  (w.v19 * (w.v37 - w.v14)) = 0 ∧
  (w.v19 * (w.v38 - w.v15)) = 0 ∧
  (w.v19 * (w.v39 - w.v16)) = 0 ∧
  (((1 : F) - w.v18) * (((1 : F) - w.v18) - (1 : F))) = 0 ∧
  (((1 : F) - w.v19) * (((1 : F) - w.v19) - (1 : F))) = 0 ∧
  (w.v17 * w.v24) = 0 ∧
  (w.v17 * w.v25) = 0 ∧
  (w.v17 * w.v26) = 0 ∧
  (w.v17 * w.v27) = 0 ∧
  ((w.v17 - (1 : F)) * ((((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))) - ((((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F))) + (4 : F)))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v56 * (w.v27 - (127 : F))) = 0 ∧
  (w.v56 * ((w.v24 + w.v25) + w.v26)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v46 - (127 : F))) = 0 ∧
  (w.v47 * ((w.v43 + w.v44) + w.v45)) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v52 * (w.v51 - (127 : F))) = 0 ∧
  (w.v52 * ((w.v48 + w.v49) + w.v50)) = 0 ∧
  (w.v48 - w.v30) = 0 ∧
  (w.v49 - w.v31) = 0 ∧
  (w.v50 - w.v32) = 0 ∧
  (w.v51 - w.v33) = 0 ∧
  (w.v4).val ≤ ((65535 : F)).val ∧
  (w.v5).val ≤ ((65535 : F)).val ∧
  (w.v6).val ≤ ((511 : F)).val ∧
  ((w.v35 * ((1 : F) - w.v18))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v6 * (65536 : F)) + w.v5) + (2 : F)) - w.v34) - (1 : F)) - w.v35) * (2130673921 : F)) * ((1 : F) - w.v18))).val ≤ ((511 : F)).val ∧
  (w.v348 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v349 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v30 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v350 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v31 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v351 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v32 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v352 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v33 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  ((w.v41 * ((1 : F) - w.v19))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v6 * (65536 : F)) + w.v5) + (1 : F)) - w.v40) - (1 : F)) - w.v41) * (2130673921 : F)) * ((1 : F) - w.v19))).val ≤ ((511 : F)).val ∧
  (w.v353 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v354 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v36 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v355 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v356 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v357 - (w.v39 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (3 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v358 - (((w.v6 * (65536 : F)) + w.v5) + (5 : F))) = 0 ∧
  (w.v359 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v360 - (((w.v48 + (w.v49 * (256 : F))) + (w.v50 * (65536 : F))) + (w.v51 * (16777216 : F)))) = 0 ∧
  (w.v27).val < ((127 : F)).val ∧
  (w.v46).val < ((127 : F)).val ∧
  (w.v51).val < ((127 : F)).val ∧
  (w.v361 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v362 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  (w.v363 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  (w.v364 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  (w.v365 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  (w.v366 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v367 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  (w.v368 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  (w.v369 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  (w.v370 - (w.v39 * ((1 : F) - w.v19))) = 0 ∧
  (w.v371 - ((w.v6 * (65536 : F)) + w.v5)) = 0 ∧
  (w.v372 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v42, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v348, w.v349, w.v350, w.v351, w.v352, w.v353, w.v354, w.v355, w.v356, w.v357, w.v20, w.v21, w.v22, w.v23, w.v4, w.v371, w.v372]
def outputs (w : W) : List F :=
  [w.v4, w.v358, w.v359, w.v360, w.v361, w.v362, w.v363, w.v364, w.v365, w.v366, w.v367, w.v368, w.v369, w.v370, w.v8, w.v24, w.v25, w.v26, w.v27]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Jump_is_jump

/-! ### Module `Jump__is_jumpdirect` -/
namespace Jump_is_jumpdirect

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `target_add_0` -/
  v0 : F
  /-- `target_add_1` -/
  v1 : F
  /-- `target_add_2` -/
  v2 : F
  /-- `target_add_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `pc_42` -/
  v42 : F
  /-- `next_pc_43` -/
  v43 : F
  /-- `next_pc_44` -/
  v44 : F
  /-- `next_pc_45` -/
  v45 : F
  /-- `next_pc_46` -/
  v46 : F
  /-- `next_pc_range_checker_47` -/
  v47 : F
  /-- `next_next_pc_48` -/
  v48 : F
  /-- `next_next_pc_49` -/
  v49 : F
  /-- `next_next_pc_50` -/
  v50 : F
  /-- `next_next_pc_51` -/
  v51 : F
  /-- `next_next_pc_range_checker_52` -/
  v52 : F
  /-- `op_a_range_checker_56` -/
  v56 : F
  v398 : F
  v399 : F
  v400 : F
  v401 : F
  v402 : F
  v403 : F
  v404 : F
  v405 : F
  v406 : F
  v407 : F
  v408 : F
  v409 : F
  v410 : F
  v411 : F
  v412 : F
  v413 : F
  v414 : F
  v415 : F
  v416 : F
  v417 : F
  v418 : F
  v419 : F
  v420 : F
  v421 : F
  v422 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v7 - (29 : F)) = 0 ∧
  (w.v18 * (w.v30 - w.v9)) = 0 ∧
  (w.v18 * (w.v31 - w.v10)) = 0 ∧
  (w.v18 * (w.v32 - w.v11)) = 0 ∧
  (w.v18 * (w.v33 - w.v12)) = 0 ∧
  (w.v19 * (w.v36 - w.v13)) = 0 ∧
  (w.v19 * (w.v37 - w.v14)) = 0 ∧
  (w.v19 * (w.v38 - w.v15)) = 0 ∧
  (w.v19 * (w.v39 - w.v16)) = 0 ∧
  (((1 : F) - w.v18) * (((1 : F) - w.v18) - (1 : F))) = 0 ∧
  (((1 : F) - w.v19) * (((1 : F) - w.v19) - (1 : F))) = 0 ∧
  (w.v17 * w.v24) = 0 ∧
  (w.v17 * w.v25) = 0 ∧
  (w.v17 * w.v26) = 0 ∧
  (w.v17 * w.v27) = 0 ∧
  ((w.v17 - (1 : F)) * ((((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))) - ((((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F))) + (4 : F)))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v56 * (w.v27 - (127 : F))) = 0 ∧
  (w.v56 * ((w.v24 + w.v25) + w.v26)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v46 - (127 : F))) = 0 ∧
  (w.v47 * ((w.v43 + w.v44) + w.v45)) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v52 * (w.v51 - (127 : F))) = 0 ∧
  (w.v52 * ((w.v48 + w.v49) + w.v50)) = 0 ∧
  ((((w.v43 + w.v30) - w.v0) * (2122383361 : F)) * ((((w.v43 + w.v30) - w.v0) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v46 + w.v33) - w.v3) + ((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v46 + w.v33) - w.v3) + ((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v0 - w.v48) = 0 ∧
  (w.v1 - w.v49) = 0 ∧
  (w.v2 - w.v50) = 0 ∧
  (w.v3 - w.v51) = 0 ∧
  (w.v4).val ≤ ((65535 : F)).val ∧
  (w.v5).val ≤ ((65535 : F)).val ∧
  (w.v6).val ≤ ((511 : F)).val ∧
  ((w.v35 * ((1 : F) - w.v18))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v6 * (65536 : F)) + w.v5) + (2 : F)) - w.v34) - (1 : F)) - w.v35) * (2130673921 : F)) * ((1 : F) - w.v18))).val ≤ ((511 : F)).val ∧
  (w.v398 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v399 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v30 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v400 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v31 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v401 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v32 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v402 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v33 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  ((w.v41 * ((1 : F) - w.v19))).val ≤ ((65535 : F)).val

def constraints_1 (w : W) : Prop :=
  (((((((((w.v6 * (65536 : F)) + w.v5) + (1 : F)) - w.v40) - (1 : F)) - w.v41) * (2130673921 : F)) * ((1 : F) - w.v19))).val ≤ ((511 : F)).val ∧
  (w.v403 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v404 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v36 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v405 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v406 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v407 - (w.v39 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (3 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v408 - (((w.v6 * (65536 : F)) + w.v5) + (5 : F))) = 0 ∧
  (w.v409 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v410 - (((w.v48 + (w.v49 * (256 : F))) + (w.v50 * (65536 : F))) + (w.v51 * (16777216 : F)))) = 0 ∧
  (w.v27).val < ((127 : F)).val ∧
  (w.v46).val < ((127 : F)).val ∧
  (w.v51).val < ((127 : F)).val ∧
  (w.v43).val ≤ ((255 : F)).val ∧
  (w.v44).val ≤ ((255 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v46).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((255 : F)).val ∧
  (w.v1).val ≤ ((255 : F)).val ∧
  (w.v2).val ≤ ((255 : F)).val ∧
  (w.v3).val ≤ ((255 : F)).val ∧
  (w.v411 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v412 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  (w.v413 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  (w.v414 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  (w.v415 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  (w.v416 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v417 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  (w.v418 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  (w.v419 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  (w.v420 - (w.v39 * ((1 : F) - w.v19))) = 0

def constraints_2 (w : W) : Prop :=
  (w.v421 - ((w.v6 * (65536 : F)) + w.v5)) = 0 ∧
  (w.v422 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w

def inputs (w : W) : List F :=
  [w.v42, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v398, w.v399, w.v400, w.v401, w.v402, w.v403, w.v404, w.v405, w.v406, w.v407, w.v20, w.v21, w.v22, w.v23, w.v4, w.v421, w.v422]
def outputs (w : W) : List F :=
  [w.v4, w.v408, w.v409, w.v410, w.v411, w.v412, w.v413, w.v414, w.v415, w.v416, w.v417, w.v418, w.v419, w.v420, w.v8, w.v24, w.v25, w.v26, w.v27]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2]

end Jump_is_jumpdirect

/-! ### Module `Jump__is_jumpi` -/
namespace Jump_is_jumpi

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `pc_42` -/
  v42 : F
  /-- `next_pc_43` -/
  v43 : F
  /-- `next_pc_44` -/
  v44 : F
  /-- `next_pc_45` -/
  v45 : F
  /-- `next_pc_46` -/
  v46 : F
  /-- `next_pc_range_checker_47` -/
  v47 : F
  /-- `next_next_pc_48` -/
  v48 : F
  /-- `next_next_pc_49` -/
  v49 : F
  /-- `next_next_pc_50` -/
  v50 : F
  /-- `next_next_pc_51` -/
  v51 : F
  /-- `next_next_pc_range_checker_52` -/
  v52 : F
  /-- `op_a_range_checker_56` -/
  v56 : F
  v373 : F
  v374 : F
  v375 : F
  v376 : F
  v377 : F
  v378 : F
  v379 : F
  v380 : F
  v381 : F
  v382 : F
  v383 : F
  v384 : F
  v385 : F
  v386 : F
  v387 : F
  v388 : F
  v389 : F
  v390 : F
  v391 : F
  v392 : F
  v393 : F
  v394 : F
  v395 : F
  v396 : F
  v397 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v7 - (28 : F)) = 0 ∧
  (w.v18 * (w.v30 - w.v9)) = 0 ∧
  (w.v18 * (w.v31 - w.v10)) = 0 ∧
  (w.v18 * (w.v32 - w.v11)) = 0 ∧
  (w.v18 * (w.v33 - w.v12)) = 0 ∧
  (w.v19 * (w.v36 - w.v13)) = 0 ∧
  (w.v19 * (w.v37 - w.v14)) = 0 ∧
  (w.v19 * (w.v38 - w.v15)) = 0 ∧
  (w.v19 * (w.v39 - w.v16)) = 0 ∧
  (((1 : F) - w.v18) * (((1 : F) - w.v18) - (1 : F))) = 0 ∧
  (((1 : F) - w.v19) * (((1 : F) - w.v19) - (1 : F))) = 0 ∧
  (w.v17 * w.v24) = 0 ∧
  (w.v17 * w.v25) = 0 ∧
  (w.v17 * w.v26) = 0 ∧
  (w.v17 * w.v27) = 0 ∧
  ((w.v17 - (1 : F)) * ((((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))) - ((((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F))) + (4 : F)))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v56 * (w.v27 - (127 : F))) = 0 ∧
  (w.v56 * ((w.v24 + w.v25) + w.v26)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v46 - (127 : F))) = 0 ∧
  (w.v47 * ((w.v43 + w.v44) + w.v45)) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v52 * (w.v51 - (127 : F))) = 0 ∧
  (w.v52 * ((w.v48 + w.v49) + w.v50)) = 0 ∧
  (w.v48 - w.v30) = 0 ∧
  (w.v49 - w.v31) = 0 ∧
  (w.v50 - w.v32) = 0 ∧
  (w.v51 - w.v33) = 0 ∧
  (w.v4).val ≤ ((65535 : F)).val ∧
  (w.v5).val ≤ ((65535 : F)).val ∧
  (w.v6).val ≤ ((511 : F)).val ∧
  ((w.v35 * ((1 : F) - w.v18))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v6 * (65536 : F)) + w.v5) + (2 : F)) - w.v34) - (1 : F)) - w.v35) * (2130673921 : F)) * ((1 : F) - w.v18))).val ≤ ((511 : F)).val ∧
  (w.v373 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v374 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v30 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v375 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v31 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v376 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v32 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  (w.v377 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  ((w.v33 * ((1 : F) - w.v18))).val ≤ ((255 : F)).val ∧
  ((w.v41 * ((1 : F) - w.v19))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v6 * (65536 : F)) + w.v5) + (1 : F)) - w.v40) - (1 : F)) - w.v41) * (2130673921 : F)) * ((1 : F) - w.v19))).val ≤ ((511 : F)).val ∧
  (w.v378 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v379 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v36 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v380 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v381 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v382 - (w.v39 * ((1 : F) - w.v19))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v19))).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (3 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v383 - (((w.v6 * (65536 : F)) + w.v5) + (5 : F))) = 0 ∧
  (w.v384 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v385 - (((w.v48 + (w.v49 * (256 : F))) + (w.v50 * (65536 : F))) + (w.v51 * (16777216 : F)))) = 0 ∧
  (w.v27).val < ((127 : F)).val ∧
  (w.v46).val < ((127 : F)).val ∧
  (w.v51).val < ((127 : F)).val ∧
  (w.v386 - (w.v9 * ((1 : F) - w.v18))) = 0 ∧
  (w.v387 - (w.v30 * ((1 : F) - w.v18))) = 0 ∧
  (w.v388 - (w.v31 * ((1 : F) - w.v18))) = 0 ∧
  (w.v389 - (w.v32 * ((1 : F) - w.v18))) = 0 ∧
  (w.v390 - (w.v33 * ((1 : F) - w.v18))) = 0 ∧
  (w.v391 - (w.v13 * ((1 : F) - w.v19))) = 0 ∧
  (w.v392 - (w.v36 * ((1 : F) - w.v19))) = 0 ∧
  (w.v393 - (w.v37 * ((1 : F) - w.v19))) = 0 ∧
  (w.v394 - (w.v38 * ((1 : F) - w.v19))) = 0 ∧
  (w.v395 - (w.v39 * ((1 : F) - w.v19))) = 0 ∧
  (w.v396 - ((w.v6 * (65536 : F)) + w.v5)) = 0 ∧
  (w.v397 - (((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v42, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v373, w.v374, w.v375, w.v376, w.v377, w.v378, w.v379, w.v380, w.v381, w.v382, w.v20, w.v21, w.v22, w.v23, w.v4, w.v396, w.v397]
def outputs (w : W) : List F :=
  [w.v4, w.v383, w.v384, w.v385, w.v386, w.v387, w.v388, w.v389, w.v390, w.v391, w.v392, w.v393, w.v394, w.v395, w.v8, w.v24, w.v25, w.v26, w.v27]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end Jump_is_jumpi

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `target_add_0` -/
  v0 : F
  /-- `target_add_1` -/
  v1 : F
  /-- `target_add_2` -/
  v2 : F
  /-- `target_add_3` -/
  v3 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `next_pc_43` -/
  v43 : F
  /-- `next_pc_44` -/
  v44 : F
  /-- `next_pc_45` -/
  v45 : F
  /-- `next_pc_46` -/
  v46 : F
  /-- `next_pc_range_checker_47` -/
  v47 : F
  /-- `next_next_pc_48` -/
  v48 : F
  /-- `next_next_pc_49` -/
  v49 : F
  /-- `next_next_pc_50` -/
  v50 : F
  /-- `next_next_pc_51` -/
  v51 : F
  /-- `next_next_pc_range_checker_52` -/
  v52 : F
  /-- `is_jump_53` -/
  v53 : F
  /-- `is_jumpi_54` -/
  v54 : F
  /-- `is_jumpdirect_55` -/
  v55 : F
  /-- `op_a_range_checker_56` -/
  v56 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (((w.v53 + w.v54) + w.v55) * (((w.v53 + w.v54) + w.v55) - (1 : F))) = 0 ∧
  (((1 : F) - ((w.v53 + w.v54) + w.v55)) * ((1 : F) - w.v18)) = 0 ∧
  (((1 : F) - ((w.v53 + w.v54) + w.v55)) * ((1 : F) - w.v19)) = 0 ∧
  (((w.v53 + w.v54) + w.v55) * (w.v7 - (((w.v53 * (27 : F)) + (w.v54 * (28 : F))) + (w.v55 * (29 : F))))) = 0 ∧
  (w.v18 * (w.v30 - w.v9)) = 0 ∧
  (w.v18 * (w.v31 - w.v10)) = 0 ∧
  (w.v18 * (w.v32 - w.v11)) = 0 ∧
  (w.v18 * (w.v33 - w.v12)) = 0 ∧
  (w.v19 * (w.v36 - w.v13)) = 0 ∧
  (w.v19 * (w.v37 - w.v14)) = 0 ∧
  (w.v19 * (w.v38 - w.v15)) = 0 ∧
  (w.v19 * (w.v39 - w.v16)) = 0 ∧
  (((1 : F) - w.v18) * (((1 : F) - w.v18) - (1 : F))) = 0 ∧
  (((1 : F) - w.v19) * (((1 : F) - w.v19) - (1 : F))) = 0 ∧
  (w.v17 * w.v24) = 0 ∧
  (w.v17 * w.v25) = 0 ∧
  (w.v17 * w.v26) = 0 ∧
  (w.v17 * w.v27) = 0 ∧
  (((w.v53 + w.v54) + w.v55) * (((w.v53 + w.v54) + w.v55) - (1 : F))) = 0 ∧
  (((w.v53 + w.v54) + w.v55) * ((w.v17 - (1 : F)) * ((((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))) - ((((w.v43 + (w.v44 * (256 : F))) + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F))) + (4 : F))))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  ((((w.v53 + w.v54) + w.v55) - (1 : F)) * w.v56) = 0 ∧
  (w.v56 * (w.v27 - (127 : F))) = 0 ∧
  (w.v56 * ((w.v24 + w.v25) + w.v26)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  ((((w.v53 + w.v54) + w.v55) - (1 : F)) * w.v47) = 0 ∧
  (w.v47 * (w.v46 - (127 : F))) = 0 ∧
  (w.v47 * ((w.v43 + w.v44) + w.v45)) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  ((((w.v53 + w.v54) + w.v55) - (1 : F)) * w.v52) = 0 ∧
  (w.v52 * (w.v51 - (127 : F))) = 0 ∧
  (w.v52 * ((w.v48 + w.v49) + w.v50)) = 0 ∧
  ((w.v53 + w.v54) * (w.v48 - w.v30)) = 0 ∧
  ((w.v53 + w.v54) * (w.v49 - w.v31)) = 0 ∧
  ((w.v53 + w.v54) * (w.v50 - w.v32)) = 0 ∧
  ((w.v53 + w.v54) * (w.v51 - w.v33)) = 0 ∧
  (w.v55 * ((((w.v43 + w.v30) - w.v0) * (2122383361 : F)) * ((((w.v43 + w.v30) - w.v0) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v55 * (((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v55 * (((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v55 * (((((w.v46 + w.v33) - w.v3) + ((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v46 + w.v33) - w.v3) + ((((w.v45 + w.v32) - w.v2) + ((((w.v44 + w.v31) - w.v1) + (((w.v43 + w.v30) - w.v0) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  (w.v55 * (w.v55 * (w.v55 - (1 : F)))) = 0 ∧
  (w.v55 * (w.v0 - w.v48)) = 0 ∧
  (w.v55 * (w.v1 - w.v49)) = 0 ∧
  (w.v55 * (w.v2 - w.v50)) = 0 ∧
  (w.v55 * (w.v3 - w.v51)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v53, w.v54, w.v55]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v53 * (w.v53 - (1 : F))) = 0 ∧
    (w.v54 * (w.v54 - (1 : F))) = 0 ∧
    (w.v55 * (w.v55 - (1 : F))) = 0 ∧
    (((w.v53 + w.v54) + w.v55)).val < ((2 : F)).val := by
  picus_det [constraints_0]

end top

end ZirenDet.Chips.Jump
