/-
  Generated by `cargo run -p zkm-picus -- --chip LoadNarrow --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.LoadNarrow

open ZirenDet

/-! ### Module `byte_and` -/
namespace byte_and

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_and

/-! ### Module `LoadNarrow__is_lb` -/
namespace LoadNarrow_is_lb

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `ls_bits_is_one_51` -/
  v51 : F
  /-- `ls_bits_is_two_52` -/
  v52 : F
  /-- `ls_bits_is_three_53` -/
  v53 : F
  /-- `val_lo_54` -/
  v54 : F
  /-- `val_hi_55` -/
  v55 : F
  /-- `most_sig_byte_56` -/
  v56 : F
  /-- `most_sig_bit_57` -/
  v57 : F
  /-- `sign_fill_byte_58` -/
  v58 : F
  /-- `sign_fill_59` -/
  v59 : F
  v354 : F
  v355 : F
  v356 : F
  v357 : F
  v358 : F
  v359 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  (w.v43 * (w.v0 - w.v41)) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (((((w.v43 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v43) * w.v0)) - ((w.v43 * w.v42) + (((1 : F) - w.v43) * w.v41))) - (1 : F)) - ((w.v44 + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * (((((1 : F) - w.v51) - w.v52) - w.v53) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * w.v33) = 0 ∧
  (w.v51 * (w.v33 - (1 : F))) = 0 ∧
  (w.v52 * (w.v33 - (2 : F))) = 0 ∧
  (w.v53 * (w.v33 - (3 : F))) = 0 ∧
  (w.v54 - ((((w.v37 * ((((1 : F) - w.v51) - w.v52) - w.v53)) + (w.v38 * w.v51)) + (w.v39 * w.v52)) + (w.v40 * w.v53))) = 0 ∧
  w.v55 = 0 ∧
  (w.v56 - w.v54) = 0 ∧
  (w.v58 - (w.v57 * (255 : F))) = 0 ∧
  (w.v59 - (w.v57 * (255 : F))) = 0 ∧
  (w.v15 - (((1 : F) - w.v10) * w.v54)) = 0 ∧
  (w.v16 - (((1 : F) - w.v10) * (w.v55 + w.v58))) = 0 ∧
  (w.v17 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v18 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v3 - (31 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v44).val ≤ ((65535 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v354 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v355).val ≤ ((127 : F)).val ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v56 - ((w.v57 * (128 : F)) + w.v355)) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v356 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v357 - (w.v28 + (4 : F))) = 0 ∧
  (w.v358 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v359 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v354 = mem_read[0].addr, v37 = mem_read[0].val[0], v38 = mem_read[0].val[1], v39 = mem_read[0].val[2], v40 = mem_read[0].val[3], v27 = program.pc, v3 = program.opcode, v4 = program.op_a, v5 = program.op_b[0], v6 = program.op_c[0], v7 = program.op_c[1], v8 = program.op_c[2], v9 = program.op_c[3], v10 = program.op_a_0, v21 = mem_read[1].val[0], v22 = mem_read[1].val[1], v23 = mem_read[1].val[2], v24 = mem_read[1].val[3], v11 = mem_read[2].val[0], v12 = mem_read[2].val[1], v13 = mem_read[2].val[2], v14 = mem_read[2].val[3], v0 = state_recv[0], v359 = state_recv[1], v28 = state_recv[3]
  outputs: v0 = state_send[0], v356 = state_send[1], v28 = state_send[2], v357 = state_send[3], v358 = mem_write[0].addr, v37 = mem_write[0].val[0], v38 = mem_write[0].val[1], v39 = mem_write[0].val[2], v40 = mem_write[0].val[3], v5 = mem_write[1].addr, v21 = mem_write[1].val[0], v22 = mem_write[1].val[1], v23 = mem_write[1].val[2], v24 = mem_write[1].val[3], v4 = mem_write[2].addr, v15 = mem_write[2].val[0], v16 = mem_write[2].val[1], v17 = mem_write[2].val[2], v18 = mem_write[2].val[3] -/
def input_origins : List String := ["mem_read[0].addr", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_c[1]", "program.op_c[2]", "program.op_c[3]", "program.op_a_0", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_mem_read_0_addr (w : W) : F := w.v354
def in_mem_read_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def in_program_pc (w : W) : F := w.v27
def in_program_opcode (w : W) : F := w.v3
def in_program_op_a (w : W) : F := w.v4
def in_program_op_b (w : W) : F := w.v5
def in_program_op_c (w : W) : List F := [w.v6, w.v7, w.v8, w.v9]
def in_program_op_a_0 (w : W) : F := w.v10
def in_mem_read_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def in_mem_read_2_val (w : W) : List F := [w.v11, w.v12, w.v13, w.v14]
def in_state_recv (w : W) : List F := [w.v0, w.v359, w.v28]
def out_state_send (w : W) : List F := [w.v0, w.v356, w.v28, w.v357]
def out_mem_write_0_addr (w : W) : F := w.v358
def out_mem_write_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def out_mem_write_1_addr (w : W) : F := w.v5
def out_mem_write_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def out_mem_write_2_addr (w : W) : F := w.v4
def out_mem_write_2_val (w : W) : List F := [w.v15, w.v16, w.v17, w.v18]

def inputs (w : W) : List F :=
  [w.v354, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v359, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v356, w.v28, w.v357, w.v358, w.v37, w.v38, w.v39, w.v40, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LoadNarrow_is_lb

/-! ### Module `LoadNarrow__is_lbu` -/
namespace LoadNarrow_is_lbu

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `ls_bits_is_one_51` -/
  v51 : F
  /-- `ls_bits_is_two_52` -/
  v52 : F
  /-- `ls_bits_is_three_53` -/
  v53 : F
  /-- `val_lo_54` -/
  v54 : F
  /-- `val_hi_55` -/
  v55 : F
  /-- `most_sig_byte_56` -/
  v56 : F
  /-- `sign_fill_byte_58` -/
  v58 : F
  /-- `sign_fill_59` -/
  v59 : F
  v360 : F
  v361 : F
  v362 : F
  v363 : F
  v364 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  (w.v43 * (w.v0 - w.v41)) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (((((w.v43 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v43) * w.v0)) - ((w.v43 * w.v42) + (((1 : F) - w.v43) * w.v41))) - (1 : F)) - ((w.v44 + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * (((((1 : F) - w.v51) - w.v52) - w.v53) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * w.v33) = 0 ∧
  (w.v51 * (w.v33 - (1 : F))) = 0 ∧
  (w.v52 * (w.v33 - (2 : F))) = 0 ∧
  (w.v53 * (w.v33 - (3 : F))) = 0 ∧
  (w.v54 - ((((w.v37 * ((((1 : F) - w.v51) - w.v52) - w.v53)) + (w.v38 * w.v51)) + (w.v39 * w.v52)) + (w.v40 * w.v53))) = 0 ∧
  w.v55 = 0 ∧
  w.v56 = 0 ∧
  w.v58 = 0 ∧
  w.v59 = 0 ∧
  (w.v15 - (((1 : F) - w.v10) * w.v54)) = 0 ∧
  (w.v16 - (((1 : F) - w.v10) * (w.v55 + w.v58))) = 0 ∧
  (w.v17 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v18 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v3 - (32 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v44).val ≤ ((65535 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v360 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v361 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v362 - (w.v28 + (4 : F))) = 0 ∧
  (w.v363 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v364 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v360 = mem_read[0].addr, v37 = mem_read[0].val[0], v38 = mem_read[0].val[1], v39 = mem_read[0].val[2], v40 = mem_read[0].val[3], v27 = program.pc, v3 = program.opcode, v4 = program.op_a, v5 = program.op_b[0], v6 = program.op_c[0], v7 = program.op_c[1], v8 = program.op_c[2], v9 = program.op_c[3], v10 = program.op_a_0, v21 = mem_read[1].val[0], v22 = mem_read[1].val[1], v23 = mem_read[1].val[2], v24 = mem_read[1].val[3], v11 = mem_read[2].val[0], v12 = mem_read[2].val[1], v13 = mem_read[2].val[2], v14 = mem_read[2].val[3], v0 = state_recv[0], v364 = state_recv[1], v28 = state_recv[3]
  outputs: v0 = state_send[0], v361 = state_send[1], v28 = state_send[2], v362 = state_send[3], v363 = mem_write[0].addr, v37 = mem_write[0].val[0], v38 = mem_write[0].val[1], v39 = mem_write[0].val[2], v40 = mem_write[0].val[3], v5 = mem_write[1].addr, v21 = mem_write[1].val[0], v22 = mem_write[1].val[1], v23 = mem_write[1].val[2], v24 = mem_write[1].val[3], v4 = mem_write[2].addr, v15 = mem_write[2].val[0], v16 = mem_write[2].val[1], v17 = mem_write[2].val[2], v18 = mem_write[2].val[3] -/
def input_origins : List String := ["mem_read[0].addr", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_c[1]", "program.op_c[2]", "program.op_c[3]", "program.op_a_0", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_mem_read_0_addr (w : W) : F := w.v360
def in_mem_read_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def in_program_pc (w : W) : F := w.v27
def in_program_opcode (w : W) : F := w.v3
def in_program_op_a (w : W) : F := w.v4
def in_program_op_b (w : W) : F := w.v5
def in_program_op_c (w : W) : List F := [w.v6, w.v7, w.v8, w.v9]
def in_program_op_a_0 (w : W) : F := w.v10
def in_mem_read_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def in_mem_read_2_val (w : W) : List F := [w.v11, w.v12, w.v13, w.v14]
def in_state_recv (w : W) : List F := [w.v0, w.v364, w.v28]
def out_state_send (w : W) : List F := [w.v0, w.v361, w.v28, w.v362]
def out_mem_write_0_addr (w : W) : F := w.v363
def out_mem_write_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def out_mem_write_1_addr (w : W) : F := w.v5
def out_mem_write_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def out_mem_write_2_addr (w : W) : F := w.v4
def out_mem_write_2_val (w : W) : List F := [w.v15, w.v16, w.v17, w.v18]

def inputs (w : W) : List F :=
  [w.v360, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v364, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v361, w.v28, w.v362, w.v363, w.v37, w.v38, w.v39, w.v40, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LoadNarrow_is_lbu

/-! ### Module `LoadNarrow__is_lh` -/
namespace LoadNarrow_is_lh

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `ls_bits_is_one_51` -/
  v51 : F
  /-- `ls_bits_is_two_52` -/
  v52 : F
  /-- `ls_bits_is_three_53` -/
  v53 : F
  /-- `val_lo_54` -/
  v54 : F
  /-- `val_hi_55` -/
  v55 : F
  /-- `most_sig_byte_56` -/
  v56 : F
  /-- `most_sig_bit_57` -/
  v57 : F
  /-- `sign_fill_byte_58` -/
  v58 : F
  /-- `sign_fill_59` -/
  v59 : F
  v365 : F
  v366 : F
  v367 : F
  v368 : F
  v369 : F
  v370 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  (w.v43 * (w.v0 - w.v41)) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (((((w.v43 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v43) * w.v0)) - ((w.v43 * w.v42) + (((1 : F) - w.v43) * w.v41))) - (1 : F)) - ((w.v44 + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * (((((1 : F) - w.v51) - w.v52) - w.v53) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * w.v33) = 0 ∧
  (w.v51 * (w.v33 - (1 : F))) = 0 ∧
  (w.v52 * (w.v33 - (2 : F))) = 0 ∧
  (w.v53 * (w.v33 - (3 : F))) = 0 ∧
  (w.v51 + w.v53) = 0 ∧
  (w.v54 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v37) + (w.v52 * w.v39))) = 0 ∧
  (w.v55 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v38) + (w.v52 * w.v40))) = 0 ∧
  (w.v56 - w.v55) = 0 ∧
  w.v58 = 0 ∧
  (w.v59 - (w.v57 * (255 : F))) = 0 ∧
  (w.v15 - (((1 : F) - w.v10) * w.v54)) = 0 ∧
  (w.v16 - (((1 : F) - w.v10) * (w.v55 + w.v58))) = 0 ∧
  (w.v17 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v18 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v3 - (33 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v44).val ≤ ((65535 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v365 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v366).val ≤ ((127 : F)).val ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v56 - ((w.v57 * (128 : F)) + w.v366)) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v367 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v368 - (w.v28 + (4 : F))) = 0 ∧
  (w.v369 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v370 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v365 = mem_read[0].addr, v37 = mem_read[0].val[0], v38 = mem_read[0].val[1], v39 = mem_read[0].val[2], v40 = mem_read[0].val[3], v27 = program.pc, v3 = program.opcode, v4 = program.op_a, v5 = program.op_b[0], v6 = program.op_c[0], v7 = program.op_c[1], v8 = program.op_c[2], v9 = program.op_c[3], v10 = program.op_a_0, v21 = mem_read[1].val[0], v22 = mem_read[1].val[1], v23 = mem_read[1].val[2], v24 = mem_read[1].val[3], v11 = mem_read[2].val[0], v12 = mem_read[2].val[1], v13 = mem_read[2].val[2], v14 = mem_read[2].val[3], v0 = state_recv[0], v370 = state_recv[1], v28 = state_recv[3]
  outputs: v0 = state_send[0], v367 = state_send[1], v28 = state_send[2], v368 = state_send[3], v369 = mem_write[0].addr, v37 = mem_write[0].val[0], v38 = mem_write[0].val[1], v39 = mem_write[0].val[2], v40 = mem_write[0].val[3], v5 = mem_write[1].addr, v21 = mem_write[1].val[0], v22 = mem_write[1].val[1], v23 = mem_write[1].val[2], v24 = mem_write[1].val[3], v4 = mem_write[2].addr, v15 = mem_write[2].val[0], v16 = mem_write[2].val[1], v17 = mem_write[2].val[2], v18 = mem_write[2].val[3] -/
def input_origins : List String := ["mem_read[0].addr", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_c[1]", "program.op_c[2]", "program.op_c[3]", "program.op_a_0", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_mem_read_0_addr (w : W) : F := w.v365
def in_mem_read_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def in_program_pc (w : W) : F := w.v27
def in_program_opcode (w : W) : F := w.v3
def in_program_op_a (w : W) : F := w.v4
def in_program_op_b (w : W) : F := w.v5
def in_program_op_c (w : W) : List F := [w.v6, w.v7, w.v8, w.v9]
def in_program_op_a_0 (w : W) : F := w.v10
def in_mem_read_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def in_mem_read_2_val (w : W) : List F := [w.v11, w.v12, w.v13, w.v14]
def in_state_recv (w : W) : List F := [w.v0, w.v370, w.v28]
def out_state_send (w : W) : List F := [w.v0, w.v367, w.v28, w.v368]
def out_mem_write_0_addr (w : W) : F := w.v369
def out_mem_write_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def out_mem_write_1_addr (w : W) : F := w.v5
def out_mem_write_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def out_mem_write_2_addr (w : W) : F := w.v4
def out_mem_write_2_val (w : W) : List F := [w.v15, w.v16, w.v17, w.v18]

def inputs (w : W) : List F :=
  [w.v365, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v370, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v367, w.v28, w.v368, w.v369, w.v37, w.v38, w.v39, w.v40, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LoadNarrow_is_lh

/-! ### Module `LoadNarrow__is_lhu` -/
namespace LoadNarrow_is_lhu

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `ls_bits_is_one_51` -/
  v51 : F
  /-- `ls_bits_is_two_52` -/
  v52 : F
  /-- `ls_bits_is_three_53` -/
  v53 : F
  /-- `val_lo_54` -/
  v54 : F
  /-- `val_hi_55` -/
  v55 : F
  /-- `most_sig_byte_56` -/
  v56 : F
  /-- `sign_fill_byte_58` -/
  v58 : F
  /-- `sign_fill_59` -/
  v59 : F
  v371 : F
  v372 : F
  v373 : F
  v374 : F
  v375 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  (w.v43 * (w.v0 - w.v41)) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (((((w.v43 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v43) * w.v0)) - ((w.v43 * w.v42) + (((1 : F) - w.v43) * w.v41))) - (1 : F)) - ((w.v44 + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F)))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * (((((1 : F) - w.v51) - w.v52) - w.v53) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * w.v33) = 0 ∧
  (w.v51 * (w.v33 - (1 : F))) = 0 ∧
  (w.v52 * (w.v33 - (2 : F))) = 0 ∧
  (w.v53 * (w.v33 - (3 : F))) = 0 ∧
  (w.v51 + w.v53) = 0 ∧
  (w.v54 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v37) + (w.v52 * w.v39))) = 0 ∧
  (w.v55 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v38) + (w.v52 * w.v40))) = 0 ∧
  w.v56 = 0 ∧
  w.v58 = 0 ∧
  w.v59 = 0 ∧
  (w.v15 - (((1 : F) - w.v10) * w.v54)) = 0 ∧
  (w.v16 - (((1 : F) - w.v10) * (w.v55 + w.v58))) = 0 ∧
  (w.v17 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v18 - (((1 : F) - w.v10) * w.v59)) = 0 ∧
  (w.v3 - (34 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v44).val ≤ ((65535 : F)).val ∧
  (w.v45).val ≤ ((255 : F)).val ∧
  (w.v371 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v372 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v373 - (w.v28 + (4 : F))) = 0 ∧
  (w.v374 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v375 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v371 = mem_read[0].addr, v37 = mem_read[0].val[0], v38 = mem_read[0].val[1], v39 = mem_read[0].val[2], v40 = mem_read[0].val[3], v27 = program.pc, v3 = program.opcode, v4 = program.op_a, v5 = program.op_b[0], v6 = program.op_c[0], v7 = program.op_c[1], v8 = program.op_c[2], v9 = program.op_c[3], v10 = program.op_a_0, v21 = mem_read[1].val[0], v22 = mem_read[1].val[1], v23 = mem_read[1].val[2], v24 = mem_read[1].val[3], v11 = mem_read[2].val[0], v12 = mem_read[2].val[1], v13 = mem_read[2].val[2], v14 = mem_read[2].val[3], v0 = state_recv[0], v375 = state_recv[1], v28 = state_recv[3]
  outputs: v0 = state_send[0], v372 = state_send[1], v28 = state_send[2], v373 = state_send[3], v374 = mem_write[0].addr, v37 = mem_write[0].val[0], v38 = mem_write[0].val[1], v39 = mem_write[0].val[2], v40 = mem_write[0].val[3], v5 = mem_write[1].addr, v21 = mem_write[1].val[0], v22 = mem_write[1].val[1], v23 = mem_write[1].val[2], v24 = mem_write[1].val[3], v4 = mem_write[2].addr, v15 = mem_write[2].val[0], v16 = mem_write[2].val[1], v17 = mem_write[2].val[2], v18 = mem_write[2].val[3] -/
def input_origins : List String := ["mem_read[0].addr", "mem_read[0].val[0]", "mem_read[0].val[1]", "mem_read[0].val[2]", "mem_read[0].val[3]", "program.pc", "program.opcode", "program.op_a", "program.op_b[0]", "program.op_c[0]", "program.op_c[1]", "program.op_c[2]", "program.op_c[3]", "program.op_a_0", "mem_read[1].val[0]", "mem_read[1].val[1]", "mem_read[1].val[2]", "mem_read[1].val[3]", "mem_read[2].val[0]", "mem_read[2].val[1]", "mem_read[2].val[2]", "mem_read[2].val[3]", "state_recv[0]", "state_recv[1]", "state_recv[3]"]
def output_origins : List String := ["state_send[0]", "state_send[1]", "state_send[2]", "state_send[3]", "mem_write[0].addr", "mem_write[0].val[0]", "mem_write[0].val[1]", "mem_write[0].val[2]", "mem_write[0].val[3]", "mem_write[1].addr", "mem_write[1].val[0]", "mem_write[1].val[1]", "mem_write[1].val[2]", "mem_write[1].val[3]", "mem_write[2].addr", "mem_write[2].val[0]", "mem_write[2].val[1]", "mem_write[2].val[2]", "mem_write[2].val[3]"]
def in_mem_read_0_addr (w : W) : F := w.v371
def in_mem_read_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def in_program_pc (w : W) : F := w.v27
def in_program_opcode (w : W) : F := w.v3
def in_program_op_a (w : W) : F := w.v4
def in_program_op_b (w : W) : F := w.v5
def in_program_op_c (w : W) : List F := [w.v6, w.v7, w.v8, w.v9]
def in_program_op_a_0 (w : W) : F := w.v10
def in_mem_read_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def in_mem_read_2_val (w : W) : List F := [w.v11, w.v12, w.v13, w.v14]
def in_state_recv (w : W) : List F := [w.v0, w.v375, w.v28]
def out_state_send (w : W) : List F := [w.v0, w.v372, w.v28, w.v373]
def out_mem_write_0_addr (w : W) : F := w.v374
def out_mem_write_0_val (w : W) : List F := [w.v37, w.v38, w.v39, w.v40]
def out_mem_write_1_addr (w : W) : F := w.v5
def out_mem_write_1_val (w : W) : List F := [w.v21, w.v22, w.v23, w.v24]
def out_mem_write_2_addr (w : W) : F := w.v4
def out_mem_write_2_val (w : W) : List F := [w.v15, w.v16, w.v17, w.v18]

def inputs (w : W) : List F :=
  [w.v371, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v375, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v372, w.v28, w.v373, w.v374, w.v37, w.v38, w.v39, w.v40, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LoadNarrow_is_lhu

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `is_lb_47` -/
  v47 : F
  /-- `is_lbu_48` -/
  v48 : F
  /-- `is_lh_49` -/
  v49 : F
  /-- `is_lhu_50` -/
  v50 : F
  /-- `ls_bits_is_one_51` -/
  v51 : F
  /-- `ls_bits_is_two_52` -/
  v52 : F
  /-- `ls_bits_is_three_53` -/
  v53 : F
  /-- `val_lo_54` -/
  v54 : F
  /-- `val_hi_55` -/
  v55 : F
  /-- `most_sig_byte_56` -/
  v56 : F
  /-- `most_sig_bit_57` -/
  v57 : F
  /-- `sign_fill_byte_58` -/
  v58 : F
  /-- `sign_fill_59` -/
  v59 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * (w.v49 - (1 : F))) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F)))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F)) * w.v34) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (w.v36 * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36)) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v36 * (w.v36 - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v36 * ((w.v30 + w.v31) + w.v32))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v43 * (w.v43 - (1 : F)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v43 * (w.v0 - w.v41))) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (((((w.v43 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v43) * w.v0)) - ((w.v43 * w.v42) + (((1 : F) - w.v43) * w.v41))) - (1 : F)) - ((w.v44 + (w.v45 * (65536 : F))) + (w.v46 * (16777216 : F))))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * (((((1 : F) - w.v51) - w.v52) - w.v53) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v51) - w.v52) - w.v53) * w.v33) = 0 ∧
  (w.v51 * (w.v33 - (1 : F))) = 0 ∧
  (w.v52 * (w.v33 - (2 : F))) = 0 ∧
  (w.v53 * (w.v33 - (3 : F))) = 0 ∧
  ((w.v49 + w.v50) * (w.v51 + w.v53)) = 0 ∧
  ((w.v47 + w.v48) * (w.v54 - ((((w.v37 * ((((1 : F) - w.v51) - w.v52) - w.v53)) + (w.v38 * w.v51)) + (w.v39 * w.v52)) + (w.v40 * w.v53)))) = 0 ∧
  ((w.v47 + w.v48) * w.v55) = 0 ∧
  ((w.v49 + w.v50) * (w.v54 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v37) + (w.v52 * w.v39)))) = 0 ∧
  ((w.v49 + w.v50) * (w.v55 - ((((((1 : F) - w.v51) - w.v52) - w.v53) * w.v38) + (w.v52 * w.v40)))) = 0 ∧
  (w.v56 - ((w.v47 * w.v54) + (w.v49 * w.v55))) = 0 ∧
  (w.v58 - ((w.v47 * w.v57) * (255 : F))) = 0 ∧
  (w.v59 - (((w.v47 + w.v49) * w.v57) * (255 : F))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v15 - (((1 : F) - w.v10) * w.v54))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v16 - (((1 : F) - w.v10) * (w.v55 + w.v58)))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v17 - (((1 : F) - w.v10) * w.v59))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v18 - (((1 : F) - w.v10) * w.v59))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * (w.v3 - ((((w.v47 * (31 : F)) + (w.v48 * (32 : F))) + (w.v49 * (33 : F))) + (w.v50 * (34 : F))))) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F))) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0

def constraints_1 (w : W) : Prop :=
  (w.v10 * w.v18) = 0 ∧
  ((((w.v47 + w.v48) + w.v49) + w.v50) * ((((w.v47 + w.v48) + w.v49) + w.v50) - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  
  outputs:  -/
def input_origins : List String := []
def output_origins : List String := []

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v47, w.v48, w.v49, w.v50]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v47 * (w.v47 - (1 : F))) = 0 ∧
    (w.v48 * (w.v48 - (1 : F))) = 0 ∧
    (w.v49 * (w.v49 - (1 : F))) = 0 ∧
    (w.v50 * (w.v50 - (1 : F))) = 0 ∧
    ((((w.v47 + w.v48) + w.v49) + w.v50)).val < ((2 : F)).val := by
  picus_det [constraints_0, constraints_1]

end top

end ZirenDet.Chips.LoadNarrow
