/-
  Generated by `cargo run -p zkm-picus -- --chip LtImm --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.LtImm

open ZirenDet

/-! ### Module `LtImm__is_slt` -/
namespace LtImm_is_slt

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `byte_flags_31` -/
  v31 : F
  /-- `byte_flags_32` -/
  v32 : F
  /-- `byte_flags_33` -/
  v33 : F
  /-- `byte_flags_34` -/
  v34 : F
  /-- `b_masked_35` -/
  v35 : F
  /-- `c_masked_36` -/
  v36 : F
  /-- `not_eq_inv_37` -/
  v37 : F
  /-- `msb_b_38` -/
  v38 : F
  /-- `msb_c_39` -/
  v39 : F
  /-- `bit_b_40` -/
  v40 : F
  /-- `bit_c_41` -/
  v41 : F
  /-- `sltu_42` -/
  v42 : F
  /-- `is_comp_eq_43` -/
  v43 : F
  /-- `is_sign_eq_44` -/
  v44 : F
  /-- `comparison_bytes_45` -/
  v45 : F
  /-- `comparison_bytes_46` -/
  v46 : F
  v328 : F
  v329 : F
  v330 : F
  v331 : F
  v332 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v40 - w.v38) = 0 ∧
  (w.v41 - w.v39) = 0 ∧
  (w.v38 - ((w.v28 - w.v35) * (2114060289 : F))) = 0 ∧
  (w.v39 - ((w.v13 - w.v36) * (2114060289 : F))) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v44 * (w.v40 - w.v41)) = 0 ∧
  ((w.v44 - (1 : F)) * ((w.v40 + w.v41) - (1 : F))) = 0 ∧
  (w.v19 - (((1 : F) - w.v14) * ((w.v40 * ((1 : F) - w.v41)) + (w.v44 * w.v42)))) = 0 ∧
  w.v20 = 0 ∧
  w.v21 = 0 ∧
  w.v22 = 0 ∧
  (w.v31 * (w.v31 - (1 : F))) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v33 * (w.v33 - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  ((((w.v31 + w.v32) + w.v33) + w.v34) * ((((w.v31 + w.v32) + w.v33) + w.v34) - (1 : F))) = 0 ∧
  (((1 : F) - w.v43) - (((w.v31 + w.v32) + w.v33) + w.v34)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  ((w.v34 - (1 : F)) * (w.v35 - w.v36)) = 0 ∧
  (w.v43 * w.v34) = 0 ∧
  (((w.v34 + w.v33) - (1 : F)) * (w.v27 - w.v12)) = 0 ∧
  (w.v43 * (w.v34 + w.v33)) = 0 ∧
  ((((w.v34 + w.v33) + w.v32) - (1 : F)) * (w.v26 - w.v11)) = 0 ∧
  (w.v43 * ((w.v34 + w.v33) + w.v32)) = 0 ∧
  (((((w.v34 + w.v33) + w.v32) + w.v31) - (1 : F)) * (w.v25 - w.v10)) = 0 ∧
  (w.v43 * (((w.v34 + w.v33) + w.v32) + w.v31)) = 0 ∧
  (w.v45 - ((((w.v35 * w.v34) + (w.v27 * w.v33)) + (w.v26 * w.v32)) + (w.v25 * w.v31))) = 0 ∧
  (w.v46 - ((((w.v36 * w.v34) + (w.v12 * w.v33)) + (w.v11 * w.v32)) + (w.v10 * w.v31))) = 0 ∧
  ((w.v43 - (1 : F)) * ((w.v37 * (w.v45 - w.v46)) - (1 : F))) = 0 ∧
  (w.v7 - (13 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v35).val < ((128 : F)).val ∧
  (w.v328 * (w.v328 - (1 : F))) = 0 ∧
  (w.v28 - ((w.v328 * (128 : F)) + w.v35)) = 0 ∧
  (w.v36).val < ((128 : F)).val ∧
  (w.v329 * (w.v329 - (1 : F))) = 0 ∧
  (w.v13 - ((w.v329 * (128 : F)) + w.v36)) = 0 ∧
  (w.v42 * (w.v42 - (1 : F))) = 0 ∧
  ((w.v42 - (1 : F)) = 0 ↔ (w.v45).val < (w.v46).val) ∧
  (w.v4).val ≤ ((65535 : F)).val ∧
  (w.v5).val ≤ ((65535 : F)).val ∧
  (w.v6).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v330 - (((w.v6 * (65536 : F)) + w.v5) + (5 : F))) = 0 ∧
  (w.v331 - (w.v1 + (4 : F))) = 0 ∧
  (w.v332 - ((w.v6 * (65536 : F)) + w.v5)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v0, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v15, w.v16, w.v17, w.v18, w.v4, w.v332, w.v1]
def outputs (w : W) : List F :=
  [w.v4, w.v330, w.v1, w.v331, w.v9, w.v25, w.v26, w.v27, w.v28, w.v8, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LtImm_is_slt

/-! ### Module `LtImm__is_sltu` -/
namespace LtImm_is_sltu

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `byte_flags_31` -/
  v31 : F
  /-- `byte_flags_32` -/
  v32 : F
  /-- `byte_flags_33` -/
  v33 : F
  /-- `byte_flags_34` -/
  v34 : F
  /-- `b_masked_35` -/
  v35 : F
  /-- `c_masked_36` -/
  v36 : F
  /-- `not_eq_inv_37` -/
  v37 : F
  /-- `msb_b_38` -/
  v38 : F
  /-- `msb_c_39` -/
  v39 : F
  /-- `bit_b_40` -/
  v40 : F
  /-- `bit_c_41` -/
  v41 : F
  /-- `sltu_42` -/
  v42 : F
  /-- `is_comp_eq_43` -/
  v43 : F
  /-- `is_sign_eq_44` -/
  v44 : F
  /-- `comparison_bytes_45` -/
  v45 : F
  /-- `comparison_bytes_46` -/
  v46 : F
  v333 : F
  v334 : F
  v335 : F
  v336 : F
  v337 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  w.v40 = 0 ∧
  w.v41 = 0 ∧
  (w.v38 - ((w.v28 - w.v35) * (2114060289 : F))) = 0 ∧
  (w.v39 - ((w.v13 - w.v36) * (2114060289 : F))) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v44 * (w.v40 - w.v41)) = 0 ∧
  ((w.v44 - (1 : F)) * ((w.v40 + w.v41) - (1 : F))) = 0 ∧
  (w.v19 - (((1 : F) - w.v14) * ((w.v40 * ((1 : F) - w.v41)) + (w.v44 * w.v42)))) = 0 ∧
  w.v20 = 0 ∧
  w.v21 = 0 ∧
  w.v22 = 0 ∧
  (w.v31 * (w.v31 - (1 : F))) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v33 * (w.v33 - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  ((((w.v31 + w.v32) + w.v33) + w.v34) * ((((w.v31 + w.v32) + w.v33) + w.v34) - (1 : F))) = 0 ∧
  (((1 : F) - w.v43) - (((w.v31 + w.v32) + w.v33) + w.v34)) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  ((w.v34 - (1 : F)) * (w.v28 - w.v13)) = 0 ∧
  (w.v43 * w.v34) = 0 ∧
  (((w.v34 + w.v33) - (1 : F)) * (w.v27 - w.v12)) = 0 ∧
  (w.v43 * (w.v34 + w.v33)) = 0 ∧
  ((((w.v34 + w.v33) + w.v32) - (1 : F)) * (w.v26 - w.v11)) = 0 ∧
  (w.v43 * ((w.v34 + w.v33) + w.v32)) = 0 ∧
  (((((w.v34 + w.v33) + w.v32) + w.v31) - (1 : F)) * (w.v25 - w.v10)) = 0 ∧
  (w.v43 * (((w.v34 + w.v33) + w.v32) + w.v31)) = 0 ∧
  (w.v45 - ((((w.v28 * w.v34) + (w.v27 * w.v33)) + (w.v26 * w.v32)) + (w.v25 * w.v31))) = 0 ∧
  (w.v46 - ((((w.v13 * w.v34) + (w.v12 * w.v33)) + (w.v11 * w.v32)) + (w.v10 * w.v31))) = 0 ∧
  ((w.v43 - (1 : F)) * ((w.v37 * (w.v45 - w.v46)) - (1 : F))) = 0 ∧
  (w.v7 - (14 : F)) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  (w.v35).val < ((128 : F)).val ∧
  (w.v333 * (w.v333 - (1 : F))) = 0 ∧
  (w.v28 - ((w.v333 * (128 : F)) + w.v35)) = 0 ∧
  (w.v36).val < ((128 : F)).val ∧
  (w.v334 * (w.v334 - (1 : F))) = 0 ∧
  (w.v13 - ((w.v334 * (128 : F)) + w.v36)) = 0 ∧
  (w.v42 * (w.v42 - (1 : F))) = 0 ∧
  ((w.v42 - (1 : F)) = 0 ↔ (w.v45).val < (w.v46).val) ∧
  (w.v4).val ≤ ((65535 : F)).val ∧
  (w.v5).val ≤ ((65535 : F)).val ∧
  (w.v6).val ≤ ((511 : F)).val ∧
  (w.v30).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (2 : F)) - w.v29) - (1 : F)) - w.v30) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((65535 : F)).val ∧
  ((((((((w.v6 * (65536 : F)) + w.v5) + (3 : F)) - w.v23) - (1 : F)) - w.v24) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v335 - (((w.v6 * (65536 : F)) + w.v5) + (5 : F))) = 0 ∧
  (w.v336 - (w.v1 + (4 : F))) = 0 ∧
  (w.v337 - ((w.v6 * (65536 : F)) + w.v5)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v0, w.v7, w.v8, w.v9, w.v10, w.v11, w.v12, w.v13, w.v14, w.v25, w.v26, w.v27, w.v28, w.v15, w.v16, w.v17, w.v18, w.v4, w.v337, w.v1]
def outputs (w : W) : List F :=
  [w.v4, w.v335, w.v1, w.v336, w.v9, w.v25, w.v26, w.v27, w.v28, w.v8, w.v19, w.v20, w.v21, w.v22]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end LtImm_is_sltu

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `is_slt_2` -/
  v2 : F
  /-- `is_sltu_3` -/
  v3 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `byte_flags_31` -/
  v31 : F
  /-- `byte_flags_32` -/
  v32 : F
  /-- `byte_flags_33` -/
  v33 : F
  /-- `byte_flags_34` -/
  v34 : F
  /-- `b_masked_35` -/
  v35 : F
  /-- `c_masked_36` -/
  v36 : F
  /-- `not_eq_inv_37` -/
  v37 : F
  /-- `msb_b_38` -/
  v38 : F
  /-- `msb_c_39` -/
  v39 : F
  /-- `bit_b_40` -/
  v40 : F
  /-- `bit_c_41` -/
  v41 : F
  /-- `sltu_42` -/
  v42 : F
  /-- `is_comp_eq_43` -/
  v43 : F
  /-- `is_sign_eq_44` -/
  v44 : F
  /-- `comparison_bytes_45` -/
  v45 : F
  /-- `comparison_bytes_46` -/
  v46 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v40 - (w.v38 * w.v2)) = 0 ∧
  (w.v41 - (w.v39 * w.v2)) = 0 ∧
  (w.v38 - ((w.v28 - w.v35) * (2114060289 : F))) = 0 ∧
  (w.v39 - ((w.v13 - w.v36) * (2114060289 : F))) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v44 * (w.v40 - w.v41)) = 0 ∧
  ((w.v2 + w.v3) * ((w.v44 - (1 : F)) * ((w.v40 + w.v41) - (1 : F)))) = 0 ∧
  (w.v19 - (((1 : F) - w.v14) * ((w.v40 * ((1 : F) - w.v41)) + (w.v44 * w.v42)))) = 0 ∧
  w.v20 = 0 ∧
  w.v21 = 0 ∧
  w.v22 = 0 ∧
  (w.v31 * (w.v31 - (1 : F))) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v33 * (w.v33 - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  ((((w.v31 + w.v32) + w.v33) + w.v34) * ((((w.v31 + w.v32) + w.v33) + w.v34) - (1 : F))) = 0 ∧
  ((w.v2 + w.v3) * (((1 : F) - w.v43) - (((w.v31 + w.v32) + w.v33) + w.v34))) = 0 ∧
  (w.v43 * (w.v43 - (1 : F))) = 0 ∧
  ((w.v34 - (1 : F)) * (((w.v28 * w.v3) + (w.v35 * w.v2)) - ((w.v13 * w.v3) + (w.v36 * w.v2)))) = 0 ∧
  (w.v43 * w.v34) = 0 ∧
  (((w.v34 + w.v33) - (1 : F)) * (w.v27 - w.v12)) = 0 ∧
  (w.v43 * (w.v34 + w.v33)) = 0 ∧
  ((((w.v34 + w.v33) + w.v32) - (1 : F)) * (w.v26 - w.v11)) = 0 ∧
  (w.v43 * ((w.v34 + w.v33) + w.v32)) = 0 ∧
  (((((w.v34 + w.v33) + w.v32) + w.v31) - (1 : F)) * (w.v25 - w.v10)) = 0 ∧
  (w.v43 * (((w.v34 + w.v33) + w.v32) + w.v31)) = 0 ∧
  (w.v45 - ((((((w.v28 * w.v3) + (w.v35 * w.v2)) * w.v34) + (w.v27 * w.v33)) + (w.v26 * w.v32)) + (w.v25 * w.v31))) = 0 ∧
  (w.v46 - ((((((w.v13 * w.v3) + (w.v36 * w.v2)) * w.v34) + (w.v12 * w.v33)) + (w.v11 * w.v32)) + (w.v10 * w.v31))) = 0 ∧
  ((w.v43 - (1 : F)) * ((w.v37 * (w.v45 - w.v46)) - (w.v2 + w.v3))) = 0 ∧
  (w.v2 * (w.v2 - (1 : F))) = 0 ∧
  (w.v3 * (w.v3 - (1 : F))) = 0 ∧
  ((w.v2 + w.v3) * ((w.v2 + w.v3) - (1 : F))) = 0 ∧
  ((w.v2 + w.v3) * (w.v7 - ((w.v2 * (13 : F)) + (w.v3 * (14 : F))))) = 0 ∧
  ((w.v2 + w.v3) * ((w.v2 + w.v3) - (1 : F))) = 0 ∧
  (w.v14 * w.v19) = 0 ∧
  (w.v14 * w.v20) = 0 ∧
  (w.v14 * w.v21) = 0 ∧
  (w.v14 * w.v22) = 0 ∧
  ((w.v2 + w.v3) * ((w.v2 + w.v3) - (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v2, w.v3]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v2 * (w.v2 - (1 : F))) = 0 ∧
    (w.v3 * (w.v3 - (1 : F))) = 0 ∧
    ((w.v2 + w.v3)).val < ((2 : F)).val := by
  picus_det [constraints_0]

end top

end ZirenDet.Chips.LtImm
