/-
  Generated by `cargo run -p zkm-picus -- --chip MemoryBump --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.MemoryBump

open ZirenDet

/-! ### Module `MemoryBump` -/
namespace MemoryBump

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `access_0` -/
  v0 : F
  /-- `access_1` -/
  v1 : F
  /-- `access_2` -/
  v2 : F
  /-- `access_3` -/
  v3 : F
  /-- `access_4` -/
  v4 : F
  /-- `access_5` -/
  v5 : F
  /-- `access_6` -/
  v6 : F
  /-- `access_7` -/
  v7 : F
  /-- `access_8` -/
  v8 : F
  /-- `access_9` -/
  v9 : F
  /-- `shard_10` -/
  v10 : F
  /-- `addr_11` -/
  v11 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v6 * (w.v6 - (1 : F))) = 0 ∧
  (w.v6 * (w.v10 - w.v4)) = 0 ∧
  (w.v9 * (w.v9 - (1 : F))) = 0 ∧
  ((((((1 : F) - w.v6) * w.v10) - ((w.v6 * w.v5) + (((1 : F) - w.v6) * w.v4))) - (1 : F)) - ((w.v7 + (w.v8 * (65536 : F))) + (w.v9 * (16777216 : F)))) = 0 ∧
  (w.v10).val ≤ ((65535 : F)).val ∧
  (w.v11).val < ((36 : F)).val ∧
  (w.v7).val ≤ ((65535 : F)).val ∧
  (w.v8).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((255 : F)).val ∧
  (w.v1).val ≤ ((255 : F)).val ∧
  (w.v2).val ≤ ((255 : F)).val ∧
  (w.v3).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((255 : F)).val ∧
  (w.v1).val ≤ ((255 : F)).val ∧
  (w.v2).val ≤ ((255 : F)).val ∧
  (w.v3).val ≤ ((255 : F)).val

def constraints (w : W) : Prop :=
  constraints_0 w

def inputs (w : W) : List F :=
  [w.v11, w.v0, w.v1, w.v2, w.v3]
def outputs (w : W) : List F :=
  [w.v11, w.v0, w.v1, w.v2, w.v3]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0]

end MemoryBump

end ZirenDet.Chips.MemoryBump
