/-
  Generated by `cargo run -p zkm-picus -- --chip MemoryLocal --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.MemoryLocal

open ZirenDet

/-! ### Module `MemoryLocal` -/
namespace MemoryLocal

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `memory_local_entries_0` -/
  v0 : F
  /-- `memory_local_entries_1` -/
  v1 : F
  /-- `memory_local_entries_2` -/
  v2 : F
  /-- `memory_local_entries_3` -/
  v3 : F
  /-- `memory_local_entries_4` -/
  v4 : F
  /-- `memory_local_entries_5` -/
  v5 : F
  /-- `memory_local_entries_6` -/
  v6 : F
  /-- `memory_local_entries_7` -/
  v7 : F
  /-- `memory_local_entries_8` -/
  v8 : F
  /-- `memory_local_entries_9` -/
  v9 : F
  /-- `memory_local_entries_10` -/
  v10 : F
  /-- `memory_local_entries_11` -/
  v11 : F
  /-- `memory_local_entries_12` -/
  v12 : F
  /-- `memory_local_entries_13` -/
  v13 : F
  /-- `memory_local_entries_14` -/
  v14 : F
  /-- `memory_local_entries_15` -/
  v15 : F
  /-- `memory_local_entries_16` -/
  v16 : F
  /-- `memory_local_entries_17` -/
  v17 : F
  /-- `memory_local_entries_18` -/
  v18 : F
  /-- `memory_local_entries_19` -/
  v19 : F
  /-- `memory_local_entries_20` -/
  v20 : F
  /-- `memory_local_entries_21` -/
  v21 : F
  /-- `memory_local_entries_22` -/
  v22 : F
  /-- `memory_local_entries_23` -/
  v23 : F
  /-- `memory_local_entries_24` -/
  v24 : F
  /-- `memory_local_entries_25` -/
  v25 : F
  /-- `memory_local_entries_26` -/
  v26 : F
  /-- `memory_local_entries_27` -/
  v27 : F
  /-- `memory_local_entries_28` -/
  v28 : F
  /-- `memory_local_entries_29` -/
  v29 : F
  /-- `memory_local_entries_30` -/
  v30 : F
  /-- `memory_local_entries_31` -/
  v31 : F
  /-- `memory_local_entries_32` -/
  v32 : F
  /-- `memory_local_entries_33` -/
  v33 : F
  /-- `memory_local_entries_34` -/
  v34 : F
  /-- `memory_local_entries_35` -/
  v35 : F
  /-- `memory_local_entries_36` -/
  v36 : F
  /-- `memory_local_entries_37` -/
  v37 : F
  /-- `memory_local_entries_38` -/
  v38 : F
  /-- `memory_local_entries_39` -/
  v39 : F
  /-- `memory_local_entries_40` -/
  v40 : F
  /-- `memory_local_entries_41` -/
  v41 : F
  /-- `memory_local_entries_42` -/
  v42 : F
  /-- `memory_local_entries_43` -/
  v43 : F
  /-- `memory_local_entries_44` -/
  v44 : F
  /-- `memory_local_entries_45` -/
  v45 : F
  /-- `memory_local_entries_46` -/
  v46 : F
  /-- `memory_local_entries_47` -/
  v47 : F
  /-- `memory_local_entries_48` -/
  v48 : F
  /-- `memory_local_entries_49` -/
  v49 : F
  /-- `memory_local_entries_50` -/
  v50 : F
  /-- `memory_local_entries_51` -/
  v51 : F
  /-- `memory_local_entries_52` -/
  v52 : F
  /-- `memory_local_entries_53` -/
  v53 : F
  /-- `memory_local_entries_54` -/
  v54 : F
  /-- `memory_local_entries_55` -/
  v55 : F
  v346 : F
  v347 : F
  v348 : F
  v349 : F
  v350 : F
  v351 : F
  v352 : F
  v353 : F
  v354 : F
  v355 : F
  v356 : F
  v357 : F
  v358 : F
  v359 : F
  v360 : F
  v361 : F
  v362 : F
  v363 : F
  v364 : F
  v365 : F
  v366 : F
  v367 : F
  v368 : F
  v369 : F
  v370 : F
  v371 : F
  v372 : F
  v373 : F
  v374 : F
  v375 : F
  v376 : F
  v377 : F
  v378 : F
  v379 : F
  v380 : F
  v381 : F
  v382 : F
  v383 : F
  v384 : F
  v385 : F
  v386 : F
  v387 : F
  v388 : F
  v389 : F
  v390 : F
  v391 : F
  v392 : F
  v393 : F
  v394 : F
  v395 : F
  v396 : F
  v397 : F
  v398 : F
  v399 : F
  v400 : F
  v401 : F
  v402 : F
  v403 : F
  v404 : F
  v405 : F
  v406 : F
  v407 : F
  v408 : F
  v409 : F
  v410 : F
  v411 : F
  v412 : F
  v413 : F
  v414 : F
  v415 : F
  v416 : F
  v417 : F
  v418 : F
  v419 : F
  v420 : F
  v421 : F
  v422 : F
  v423 : F
  v424 : F
  v425 : F
  v426 : F
  v427 : F
  v428 : F
  v429 : F
  v430 : F
  v431 : F
  v432 : F
  v433 : F
  v434 : F
  v435 : F
  v436 : F
  v437 : F
  v438 : F
  v439 : F
  v440 : F
  v441 : F
  v442 : F
  v443 : F
  v444 : F
  v445 : F
  v446 : F
  v447 : F
  v448 : F
  v449 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v13 * (w.v13 - (1 : F))) = 0 ∧
  (w.v27 * (w.v27 - (1 : F))) = 0 ∧
  (w.v41 * (w.v41 - (1 : F))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v346 - (w.v1 * w.v13)) = 0 ∧
  (w.v347 - (w.v3 * w.v13)) = 0 ∧
  (w.v348 - (w.v0 * w.v13)) = 0 ∧
  (w.v349 - (w.v5 * w.v13)) = 0 ∧
  (w.v350 - (w.v6 * w.v13)) = 0 ∧
  (w.v351 - (w.v7 * w.v13)) = 0 ∧
  (w.v352 - (w.v8 * w.v13)) = 0 ∧
  (w.v353 - (w.v13 * w.v13)) = 0 ∧
  (w.v354 - (w.v2 * w.v13)) = 0 ∧
  (w.v355 - (w.v4 * w.v13)) = 0 ∧
  (w.v356 - (w.v0 * w.v13)) = 0 ∧
  (w.v357 - (w.v9 * w.v13)) = 0 ∧
  (w.v358 - (w.v10 * w.v13)) = 0 ∧
  (w.v359 - (w.v11 * w.v13)) = 0 ∧
  (w.v360 - (w.v12 * w.v13)) = 0 ∧
  (w.v361 - (w.v13 * w.v13)) = 0 ∧
  (w.v362 - (w.v0 * w.v13)) = 0 ∧
  (w.v363 - (w.v9 * w.v13)) = 0 ∧
  ((w.v9 * w.v13)).val ≤ ((255 : F)).val ∧
  (w.v364 - (w.v10 * w.v13)) = 0 ∧
  ((w.v10 * w.v13)).val ≤ ((255 : F)).val ∧
  (w.v365 - (w.v11 * w.v13)) = 0 ∧
  ((w.v11 * w.v13)).val ≤ ((255 : F)).val ∧
  (w.v366 - (w.v12 * w.v13)) = 0 ∧
  ((w.v12 * w.v13)).val ≤ ((255 : F)).val ∧
  (w.v367 - (w.v15 * w.v27)) = 0 ∧
  (w.v368 - (w.v17 * w.v27)) = 0 ∧
  (w.v369 - (w.v14 * w.v27)) = 0 ∧
  (w.v370 - (w.v19 * w.v27)) = 0 ∧
  (w.v371 - (w.v20 * w.v27)) = 0 ∧
  (w.v372 - (w.v21 * w.v27)) = 0 ∧
  (w.v373 - (w.v22 * w.v27)) = 0 ∧
  (w.v374 - (w.v27 * w.v27)) = 0 ∧
  (w.v375 - (w.v16 * w.v27)) = 0 ∧
  (w.v376 - (w.v18 * w.v27)) = 0 ∧
  (w.v377 - (w.v14 * w.v27)) = 0 ∧
  (w.v378 - (w.v23 * w.v27)) = 0 ∧
  (w.v379 - (w.v24 * w.v27)) = 0 ∧
  (w.v380 - (w.v25 * w.v27)) = 0 ∧
  (w.v381 - (w.v26 * w.v27)) = 0 ∧
  (w.v382 - (w.v27 * w.v27)) = 0 ∧
  (w.v383 - (w.v14 * w.v27)) = 0 ∧
  (w.v384 - (w.v23 * w.v27)) = 0 ∧
  ((w.v23 * w.v27)).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v385 - (w.v24 * w.v27)) = 0 ∧
  ((w.v24 * w.v27)).val ≤ ((255 : F)).val ∧
  (w.v386 - (w.v25 * w.v27)) = 0 ∧
  ((w.v25 * w.v27)).val ≤ ((255 : F)).val ∧
  (w.v387 - (w.v26 * w.v27)) = 0 ∧
  ((w.v26 * w.v27)).val ≤ ((255 : F)).val ∧
  (w.v388 - (w.v29 * w.v41)) = 0 ∧
  (w.v389 - (w.v31 * w.v41)) = 0 ∧
  (w.v390 - (w.v28 * w.v41)) = 0 ∧
  (w.v391 - (w.v33 * w.v41)) = 0 ∧
  (w.v392 - (w.v34 * w.v41)) = 0 ∧
  (w.v393 - (w.v35 * w.v41)) = 0 ∧
  (w.v394 - (w.v36 * w.v41)) = 0 ∧
  (w.v395 - (w.v41 * w.v41)) = 0 ∧
  (w.v396 - (w.v30 * w.v41)) = 0 ∧
  (w.v397 - (w.v32 * w.v41)) = 0 ∧
  (w.v398 - (w.v28 * w.v41)) = 0 ∧
  (w.v399 - (w.v37 * w.v41)) = 0 ∧
  (w.v400 - (w.v38 * w.v41)) = 0 ∧
  (w.v401 - (w.v39 * w.v41)) = 0 ∧
  (w.v402 - (w.v40 * w.v41)) = 0 ∧
  (w.v403 - (w.v41 * w.v41)) = 0 ∧
  (w.v404 - (w.v28 * w.v41)) = 0 ∧
  (w.v405 - (w.v37 * w.v41)) = 0 ∧
  ((w.v37 * w.v41)).val ≤ ((255 : F)).val ∧
  (w.v406 - (w.v38 * w.v41)) = 0 ∧
  ((w.v38 * w.v41)).val ≤ ((255 : F)).val ∧
  (w.v407 - (w.v39 * w.v41)) = 0 ∧
  ((w.v39 * w.v41)).val ≤ ((255 : F)).val ∧
  (w.v408 - (w.v40 * w.v41)) = 0 ∧
  ((w.v40 * w.v41)).val ≤ ((255 : F)).val ∧
  (w.v409 - (w.v43 * w.v55)) = 0 ∧
  (w.v410 - (w.v45 * w.v55)) = 0 ∧
  (w.v411 - (w.v42 * w.v55)) = 0 ∧
  (w.v412 - (w.v47 * w.v55)) = 0 ∧
  (w.v413 - (w.v48 * w.v55)) = 0 ∧
  (w.v414 - (w.v49 * w.v55)) = 0 ∧
  (w.v415 - (w.v50 * w.v55)) = 0 ∧
  (w.v416 - (w.v55 * w.v55)) = 0 ∧
  (w.v417 - (w.v44 * w.v55)) = 0 ∧
  (w.v418 - (w.v46 * w.v55)) = 0 ∧
  (w.v419 - (w.v42 * w.v55)) = 0 ∧
  (w.v420 - (w.v51 * w.v55)) = 0 ∧
  (w.v421 - (w.v52 * w.v55)) = 0 ∧
  (w.v422 - (w.v53 * w.v55)) = 0 ∧
  (w.v423 - (w.v54 * w.v55)) = 0 ∧
  (w.v424 - (w.v55 * w.v55)) = 0 ∧
  (w.v425 - (w.v42 * w.v55)) = 0

def constraints_2 (w : W) : Prop :=
  (w.v426 - (w.v51 * w.v55)) = 0 ∧
  ((w.v51 * w.v55)).val ≤ ((255 : F)).val ∧
  (w.v427 - (w.v52 * w.v55)) = 0 ∧
  ((w.v52 * w.v55)).val ≤ ((255 : F)).val ∧
  (w.v428 - (w.v53 * w.v55)) = 0 ∧
  ((w.v53 * w.v55)).val ≤ ((255 : F)).val ∧
  (w.v429 - (w.v54 * w.v55)) = 0 ∧
  ((w.v54 * w.v55)).val ≤ ((255 : F)).val ∧
  (w.v430 - (w.v0 * w.v13)) = 0 ∧
  (w.v431 - (w.v5 * w.v13)) = 0 ∧
  (w.v432 - (w.v6 * w.v13)) = 0 ∧
  (w.v433 - (w.v7 * w.v13)) = 0 ∧
  (w.v434 - (w.v8 * w.v13)) = 0 ∧
  (w.v435 - (w.v14 * w.v27)) = 0 ∧
  (w.v436 - (w.v19 * w.v27)) = 0 ∧
  (w.v437 - (w.v20 * w.v27)) = 0 ∧
  (w.v438 - (w.v21 * w.v27)) = 0 ∧
  (w.v439 - (w.v22 * w.v27)) = 0 ∧
  (w.v440 - (w.v28 * w.v41)) = 0 ∧
  (w.v441 - (w.v33 * w.v41)) = 0 ∧
  (w.v442 - (w.v34 * w.v41)) = 0 ∧
  (w.v443 - (w.v35 * w.v41)) = 0 ∧
  (w.v444 - (w.v36 * w.v41)) = 0 ∧
  (w.v445 - (w.v42 * w.v55)) = 0 ∧
  (w.v446 - (w.v47 * w.v55)) = 0 ∧
  (w.v447 - (w.v48 * w.v55)) = 0 ∧
  (w.v448 - (w.v49 * w.v55)) = 0 ∧
  (w.v449 - (w.v50 * w.v55)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w

def inputs (w : W) : List F :=
  [w.v362, w.v363, w.v364, w.v365, w.v366, w.v383, w.v384, w.v385, w.v386, w.v387, w.v404, w.v405, w.v406, w.v407, w.v408, w.v425, w.v426, w.v427, w.v428, w.v429]
def outputs (w : W) : List F :=
  [w.v346, w.v347, w.v348, w.v349, w.v350, w.v351, w.v352, w.v353, w.v354, w.v355, w.v356, w.v357, w.v358, w.v359, w.v360, w.v361, w.v367, w.v368, w.v369, w.v370, w.v371, w.v372, w.v373, w.v374, w.v375, w.v376, w.v377, w.v378, w.v379, w.v380, w.v381, w.v382, w.v388, w.v389, w.v390, w.v391, w.v392, w.v393, w.v394, w.v395, w.v396, w.v397, w.v398, w.v399, w.v400, w.v401, w.v402, w.v403, w.v409, w.v410, w.v411, w.v412, w.v413, w.v414, w.v415, w.v416, w.v417, w.v418, w.v419, w.v420, w.v421, w.v422, w.v423, w.v424, w.v430, w.v431, w.v432, w.v433, w.v434, w.v435, w.v436, w.v437, w.v438, w.v439, w.v440, w.v441, w.v442, w.v443, w.v444, w.v445, w.v446, w.v447, w.v448, w.v449]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2]

end MemoryLocal

end ZirenDet.Chips.MemoryLocal
