/-
  Generated by `cargo run -p zkm-picus -- --chip MemoryUnaligned --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.MemoryUnaligned

open ZirenDet

/-! ### Module `byte_and` -/
namespace byte_and

/-- Abstract helper: 2 input(s), 1 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end byte_and

/-! ### Module `MemoryUnaligned__is_lwl` -/
namespace MemoryUnaligned_is_lwl

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `memory_access_47` -/
  v47 : F
  /-- `memory_access_48` -/
  v48 : F
  /-- `memory_access_49` -/
  v49 : F
  /-- `memory_access_50` -/
  v50 : F
  /-- `ls_bits_is_one_55` -/
  v55 : F
  /-- `ls_bits_is_two_56` -/
  v56 : F
  /-- `ls_bits_is_three_57` -/
  v57 : F
  /-- `lwl_gate_58` -/
  v58 : F
  /-- `lwr_gate_59` -/
  v59 : F
  v354 : F
  v355 : F
  v356 : F
  v357 : F
  v358 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v0 - w.v45)) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (((((w.v47 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v47) * w.v0)) - ((w.v47 * w.v46) + (((1 : F) - w.v47) * w.v45))) - (1 : F)) - ((w.v48 + (w.v49 * (65536 : F))) + (w.v50 * (16777216 : F)))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * (((((1 : F) - w.v55) - w.v56) - w.v57) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * w.v33) = 0 ∧
  (w.v55 * (w.v33 - (1 : F))) = 0 ∧
  (w.v56 * (w.v33 - (2 : F))) = 0 ∧
  (w.v57 * (w.v33 - (3 : F))) = 0 ∧
  (w.v41 - w.v37) = 0 ∧
  (w.v42 - w.v38) = 0 ∧
  (w.v43 - w.v39) = 0 ∧
  (w.v44 - w.v40) = 0 ∧
  (w.v58 - ((1 : F) - w.v10)) = 0 ∧
  w.v59 = 0 ∧
  (w.v59 * (w.v15 - ((((w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v42 * w.v55)) + (w.v43 * w.v56)) + (w.v44 * w.v57)))) = 0 ∧
  (w.v59 * (w.v16 - ((((w.v42 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v43 * w.v55)) + (w.v44 * w.v56)) + (w.v12 * w.v57)))) = 0 ∧
  (w.v59 * (w.v17 - (((w.v43 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v44 * w.v55)) + (w.v13 * (((1 : F) - w.v55) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v59 * (w.v18 - ((w.v44 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v14 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v58 * (w.v15 - ((w.v41 * w.v57) + (w.v11 * ((1 : F) - w.v57))))) = 0 ∧
  (w.v58 * (w.v16 - ((((w.v42 * w.v57) + (w.v41 * w.v56)) + (w.v12 * w.v55)) + (w.v12 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v17 - ((((w.v43 * w.v57) + (w.v42 * w.v56)) + (w.v41 * w.v55)) + (w.v13 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v18 - ((((w.v44 * w.v57) + (w.v43 * w.v56)) + (w.v42 * w.v55)) + (w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v3 - (36 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v48).val ≤ ((65535 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v49).val ≤ ((255 : F)).val ∧
  (w.v354 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v355 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v356 - (w.v28 + (4 : F))) = 0 ∧
  (w.v357 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v358 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v354, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v358, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v355, w.v28, w.v356, w.v357, w.v41, w.v42, w.v43, w.v44, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end MemoryUnaligned_is_lwl

/-! ### Module `MemoryUnaligned__is_lwr` -/
namespace MemoryUnaligned_is_lwr

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `memory_access_47` -/
  v47 : F
  /-- `memory_access_48` -/
  v48 : F
  /-- `memory_access_49` -/
  v49 : F
  /-- `memory_access_50` -/
  v50 : F
  /-- `ls_bits_is_one_55` -/
  v55 : F
  /-- `ls_bits_is_two_56` -/
  v56 : F
  /-- `ls_bits_is_three_57` -/
  v57 : F
  /-- `lwl_gate_58` -/
  v58 : F
  /-- `lwr_gate_59` -/
  v59 : F
  v359 : F
  v360 : F
  v361 : F
  v362 : F
  v363 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v0 - w.v45)) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (((((w.v47 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v47) * w.v0)) - ((w.v47 * w.v46) + (((1 : F) - w.v47) * w.v45))) - (1 : F)) - ((w.v48 + (w.v49 * (65536 : F))) + (w.v50 * (16777216 : F)))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * (((((1 : F) - w.v55) - w.v56) - w.v57) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * w.v33) = 0 ∧
  (w.v55 * (w.v33 - (1 : F))) = 0 ∧
  (w.v56 * (w.v33 - (2 : F))) = 0 ∧
  (w.v57 * (w.v33 - (3 : F))) = 0 ∧
  (w.v41 - w.v37) = 0 ∧
  (w.v42 - w.v38) = 0 ∧
  (w.v43 - w.v39) = 0 ∧
  (w.v44 - w.v40) = 0 ∧
  w.v58 = 0 ∧
  (w.v59 - ((1 : F) - w.v10)) = 0 ∧
  (w.v59 * (w.v15 - ((((w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v42 * w.v55)) + (w.v43 * w.v56)) + (w.v44 * w.v57)))) = 0 ∧
  (w.v59 * (w.v16 - ((((w.v42 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v43 * w.v55)) + (w.v44 * w.v56)) + (w.v12 * w.v57)))) = 0 ∧
  (w.v59 * (w.v17 - (((w.v43 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v44 * w.v55)) + (w.v13 * (((1 : F) - w.v55) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v59 * (w.v18 - ((w.v44 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v14 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v58 * (w.v15 - ((w.v41 * w.v57) + (w.v11 * ((1 : F) - w.v57))))) = 0 ∧
  (w.v58 * (w.v16 - ((((w.v42 * w.v57) + (w.v41 * w.v56)) + (w.v12 * w.v55)) + (w.v12 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v17 - ((((w.v43 * w.v57) + (w.v42 * w.v56)) + (w.v41 * w.v55)) + (w.v13 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v18 - ((((w.v44 * w.v57) + (w.v43 * w.v56)) + (w.v42 * w.v55)) + (w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v3 - (37 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v48).val ≤ ((65535 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v49).val ≤ ((255 : F)).val ∧
  (w.v359 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v360 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v361 - (w.v28 + (4 : F))) = 0 ∧
  (w.v362 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v363 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v359, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v363, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v360, w.v28, w.v361, w.v362, w.v41, w.v42, w.v43, w.v44, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end MemoryUnaligned_is_lwr

/-! ### Module `MemoryUnaligned__is_swl` -/
namespace MemoryUnaligned_is_swl

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `memory_access_47` -/
  v47 : F
  /-- `memory_access_48` -/
  v48 : F
  /-- `memory_access_49` -/
  v49 : F
  /-- `memory_access_50` -/
  v50 : F
  /-- `ls_bits_is_one_55` -/
  v55 : F
  /-- `ls_bits_is_two_56` -/
  v56 : F
  /-- `ls_bits_is_three_57` -/
  v57 : F
  /-- `lwl_gate_58` -/
  v58 : F
  /-- `lwr_gate_59` -/
  v59 : F
  v364 : F
  v365 : F
  v366 : F
  v367 : F
  v368 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v0 - w.v45)) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (((((w.v47 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v47) * w.v0)) - ((w.v47 * w.v46) + (((1 : F) - w.v47) * w.v45))) - (1 : F)) - ((w.v48 + (w.v49 * (65536 : F))) + (w.v50 * (16777216 : F)))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * (((((1 : F) - w.v55) - w.v56) - w.v57) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * w.v33) = 0 ∧
  (w.v55 * (w.v33 - (1 : F))) = 0 ∧
  (w.v56 * (w.v33 - (2 : F))) = 0 ∧
  (w.v57 * (w.v33 - (3 : F))) = 0 ∧
  w.v58 = 0 ∧
  w.v59 = 0 ∧
  (w.v59 * (w.v15 - ((((w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v42 * w.v55)) + (w.v43 * w.v56)) + (w.v44 * w.v57)))) = 0 ∧
  (w.v59 * (w.v16 - ((((w.v42 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v43 * w.v55)) + (w.v44 * w.v56)) + (w.v12 * w.v57)))) = 0 ∧
  (w.v59 * (w.v17 - (((w.v43 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v44 * w.v55)) + (w.v13 * (((1 : F) - w.v55) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v59 * (w.v18 - ((w.v44 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v14 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v58 * (w.v15 - ((w.v41 * w.v57) + (w.v11 * ((1 : F) - w.v57))))) = 0 ∧
  (w.v58 * (w.v16 - ((((w.v42 * w.v57) + (w.v41 * w.v56)) + (w.v12 * w.v55)) + (w.v12 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v17 - ((((w.v43 * w.v57) + (w.v42 * w.v56)) + (w.v41 * w.v55)) + (w.v13 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v18 - ((((w.v44 * w.v57) + (w.v43 * w.v56)) + (w.v42 * w.v55)) + (w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v41 - ((((w.v18 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v17 * w.v55)) + (w.v16 * w.v56)) + (w.v15 * w.v57))) = 0 ∧
  (w.v42 - ((((w.v38 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v18 * w.v55)) + (w.v17 * w.v56)) + (w.v16 * w.v57))) = 0 ∧
  (w.v43 - (((w.v39 * (((((1 : F) - w.v55) - w.v56) - w.v57) + w.v55)) + (w.v18 * w.v56)) + (w.v17 * w.v57))) = 0 ∧
  (w.v44 - ((w.v40 * ((1 : F) - w.v57)) + (w.v18 * w.v57))) = 0 ∧
  (w.v3 - (42 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v48).val ≤ ((65535 : F)).val ∧
  (w.v49).val ≤ ((255 : F)).val ∧
  (w.v364 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v365 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v366 - (w.v28 + (4 : F))) = 0 ∧
  (w.v367 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v368 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v364, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v368, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v365, w.v28, w.v366, w.v367, w.v41, w.v42, w.v43, w.v44, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end MemoryUnaligned_is_swl

/-! ### Module `MemoryUnaligned__is_swr` -/
namespace MemoryUnaligned_is_swr

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_4` -/
  v4 : F
  /-- `common_5` -/
  v5 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_19` -/
  v19 : F
  /-- `common_20` -/
  v20 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_25` -/
  v25 : F
  /-- `common_26` -/
  v26 : F
  /-- `common_27` -/
  v27 : F
  /-- `common_28` -/
  v28 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `memory_access_47` -/
  v47 : F
  /-- `memory_access_48` -/
  v48 : F
  /-- `memory_access_49` -/
  v49 : F
  /-- `memory_access_50` -/
  v50 : F
  /-- `ls_bits_is_one_55` -/
  v55 : F
  /-- `ls_bits_is_two_56` -/
  v56 : F
  /-- `ls_bits_is_three_57` -/
  v57 : F
  /-- `lwl_gate_58` -/
  v58 : F
  /-- `lwr_gate_59` -/
  v59 : F
  v369 : F
  v370 : F
  v371 : F
  v372 : F
  v373 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  (w.v36 * ((w.v30 + w.v31) + w.v32)) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v47 * (w.v0 - w.v45)) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (((((w.v47 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v47) * w.v0)) - ((w.v47 * w.v46) + (((1 : F) - w.v47) * w.v45))) - (1 : F)) - ((w.v48 + (w.v49 * (65536 : F))) + (w.v50 * (16777216 : F)))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * (((((1 : F) - w.v55) - w.v56) - w.v57) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * w.v33) = 0 ∧
  (w.v55 * (w.v33 - (1 : F))) = 0 ∧
  (w.v56 * (w.v33 - (2 : F))) = 0 ∧
  (w.v57 * (w.v33 - (3 : F))) = 0 ∧
  w.v58 = 0 ∧
  w.v59 = 0 ∧
  (w.v59 * (w.v15 - ((((w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v42 * w.v55)) + (w.v43 * w.v56)) + (w.v44 * w.v57)))) = 0 ∧
  (w.v59 * (w.v16 - ((((w.v42 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v43 * w.v55)) + (w.v44 * w.v56)) + (w.v12 * w.v57)))) = 0 ∧
  (w.v59 * (w.v17 - (((w.v43 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v44 * w.v55)) + (w.v13 * (((1 : F) - w.v55) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v59 * (w.v18 - ((w.v44 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v14 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v58 * (w.v15 - ((w.v41 * w.v57) + (w.v11 * ((1 : F) - w.v57))))) = 0 ∧
  (w.v58 * (w.v16 - ((((w.v42 * w.v57) + (w.v41 * w.v56)) + (w.v12 * w.v55)) + (w.v12 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v17 - ((((w.v43 * w.v57) + (w.v42 * w.v56)) + (w.v41 * w.v55)) + (w.v13 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v18 - ((((w.v44 * w.v57) + (w.v43 * w.v56)) + (w.v42 * w.v55)) + (w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v41 - ((w.v15 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v37 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v42 - (((w.v16 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v15 * w.v55)) + (w.v38 * (w.v56 + w.v57)))) = 0 ∧
  (w.v43 - ((((w.v17 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v16 * w.v55)) + (w.v15 * w.v56)) + (w.v39 * w.v57))) = 0 ∧
  (w.v44 - ((((w.v18 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v17 * w.v55)) + (w.v16 * w.v56)) + (w.v15 * w.v57))) = 0 ∧
  (w.v3 - (43 : F)) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  (w.v15 - w.v11) = 0 ∧
  (w.v16 - w.v12) = 0 ∧
  (w.v17 - w.v13) = 0 ∧
  (w.v18 - w.v14) = 0 ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v32).val < ((127 : F)).val ∧
  ((35 : F)).val < (w.v29).val ∧
  (w.v48).val ≤ ((65535 : F)).val ∧
  (w.v49).val ≤ ((255 : F)).val ∧
  (w.v369 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v37).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((255 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v26).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v25) - (1 : F)) - w.v26) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v22).val ≤ ((255 : F)).val ∧
  (w.v23).val ≤ ((255 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v19) - (1 : F)) - w.v20) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v16).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((255 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v370 - (((w.v2 * (65536 : F)) + w.v1) + (5 : F))) = 0 ∧
  (w.v371 - (w.v28 + (4 : F))) = 0 ∧
  (w.v372 - ((((w.v29 + (w.v30 * (256 : F))) + (w.v31 * (65536 : F))) + (w.v32 * (16777216 : F))) - w.v33)) = 0 ∧
  (w.v373 - ((w.v2 * (65536 : F)) + w.v1)) = 0 ∧
  byte_and.rel [w.v29, (3 : F)] [w.v33]

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v369, w.v37, w.v38, w.v39, w.v40, w.v27, w.v3, w.v4, w.v5, w.v6, w.v7, w.v8, w.v9, w.v10, w.v21, w.v22, w.v23, w.v24, w.v11, w.v12, w.v13, w.v14, w.v0, w.v373, w.v28]
def outputs (w : W) : List F :=
  [w.v0, w.v370, w.v28, w.v371, w.v372, w.v41, w.v42, w.v43, w.v44, w.v5, w.v21, w.v22, w.v23, w.v24, w.v4, w.v15, w.v16, w.v17, w.v18]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (h_byte_and : ∀ i o o', byte_and.rel i o → byte_and.rel i o' → o = o') -- abstract helper: assumed
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end MemoryUnaligned_is_swr

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `common_0` -/
  v0 : F
  /-- `common_1` -/
  v1 : F
  /-- `common_2` -/
  v2 : F
  /-- `common_3` -/
  v3 : F
  /-- `common_6` -/
  v6 : F
  /-- `common_7` -/
  v7 : F
  /-- `common_8` -/
  v8 : F
  /-- `common_9` -/
  v9 : F
  /-- `common_10` -/
  v10 : F
  /-- `common_11` -/
  v11 : F
  /-- `common_12` -/
  v12 : F
  /-- `common_13` -/
  v13 : F
  /-- `common_14` -/
  v14 : F
  /-- `common_15` -/
  v15 : F
  /-- `common_16` -/
  v16 : F
  /-- `common_17` -/
  v17 : F
  /-- `common_18` -/
  v18 : F
  /-- `common_21` -/
  v21 : F
  /-- `common_22` -/
  v22 : F
  /-- `common_23` -/
  v23 : F
  /-- `common_24` -/
  v24 : F
  /-- `common_29` -/
  v29 : F
  /-- `common_30` -/
  v30 : F
  /-- `common_31` -/
  v31 : F
  /-- `common_32` -/
  v32 : F
  /-- `common_33` -/
  v33 : F
  /-- `common_34` -/
  v34 : F
  /-- `common_35` -/
  v35 : F
  /-- `common_36` -/
  v36 : F
  /-- `memory_access_37` -/
  v37 : F
  /-- `memory_access_38` -/
  v38 : F
  /-- `memory_access_39` -/
  v39 : F
  /-- `memory_access_40` -/
  v40 : F
  /-- `memory_access_41` -/
  v41 : F
  /-- `memory_access_42` -/
  v42 : F
  /-- `memory_access_43` -/
  v43 : F
  /-- `memory_access_44` -/
  v44 : F
  /-- `memory_access_45` -/
  v45 : F
  /-- `memory_access_46` -/
  v46 : F
  /-- `memory_access_47` -/
  v47 : F
  /-- `memory_access_48` -/
  v48 : F
  /-- `memory_access_49` -/
  v49 : F
  /-- `memory_access_50` -/
  v50 : F
  /-- `is_lwl_51` -/
  v51 : F
  /-- `is_lwr_52` -/
  v52 : F
  /-- `is_swl_53` -/
  v53 : F
  /-- `is_swr_54` -/
  v54 : F
  /-- `ls_bits_is_one_55` -/
  v55 : F
  /-- `ls_bits_is_two_56` -/
  v56 : F
  /-- `ls_bits_is_three_57` -/
  v57 : F
  /-- `lwl_gate_58` -/
  v58 : F
  /-- `lwr_gate_59` -/
  v59 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) * ((((w.v21 + w.v6) - w.v29) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) * (((((w.v24 + w.v9) - w.v32) + ((((w.v23 + w.v8) - w.v31) + ((((w.v22 + w.v7) - w.v30) + (((w.v21 + w.v6) - w.v29) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F))) * (2122383361 : F)) - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F)))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F)) * w.v34) = 0 ∧
  (w.v34 * (w.v32 - (127 : F))) = 0 ∧
  (w.v34 * ((w.v29 + w.v30) + w.v31)) = 0 ∧
  (w.v36 * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (((1 : F) - (w.v35 * ((w.v30 + w.v31) + w.v32))) - w.v36)) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (w.v36 * (w.v36 - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (w.v36 * ((w.v30 + w.v31) + w.v32))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (w.v47 * (w.v47 - (1 : F)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (w.v47 * (w.v0 - w.v45))) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (((((w.v47 * ((w.v2 * (65536 : F)) + w.v1)) + (((1 : F) - w.v47) * w.v0)) - ((w.v47 * w.v46) + (((1 : F) - w.v47) * w.v45))) - (1 : F)) - ((w.v48 + (w.v49 * (65536 : F))) + (w.v50 * (16777216 : F))))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * (((((1 : F) - w.v55) - w.v56) - w.v57) - (1 : F))) = 0 ∧
  (((((1 : F) - w.v55) - w.v56) - w.v57) * w.v33) = 0 ∧
  (w.v55 * (w.v33 - (1 : F))) = 0 ∧
  (w.v56 * (w.v33 - (2 : F))) = 0 ∧
  (w.v57 * (w.v33 - (3 : F))) = 0 ∧
  ((w.v51 + w.v52) * (w.v41 - w.v37)) = 0 ∧
  ((w.v51 + w.v52) * (w.v42 - w.v38)) = 0 ∧
  ((w.v51 + w.v52) * (w.v43 - w.v39)) = 0 ∧
  ((w.v51 + w.v52) * (w.v44 - w.v40)) = 0 ∧
  (w.v58 - (w.v51 * ((1 : F) - w.v10))) = 0 ∧
  (w.v59 - (w.v52 * ((1 : F) - w.v10))) = 0 ∧
  (w.v59 * (w.v15 - ((((w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v42 * w.v55)) + (w.v43 * w.v56)) + (w.v44 * w.v57)))) = 0 ∧
  (w.v59 * (w.v16 - ((((w.v42 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v43 * w.v55)) + (w.v44 * w.v56)) + (w.v12 * w.v57)))) = 0 ∧
  (w.v59 * (w.v17 - (((w.v43 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v44 * w.v55)) + (w.v13 * (((1 : F) - w.v55) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v59 * (w.v18 - ((w.v44 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v14 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v58 * (w.v15 - ((w.v41 * w.v57) + (w.v11 * ((1 : F) - w.v57))))) = 0 ∧
  (w.v58 * (w.v16 - ((((w.v42 * w.v57) + (w.v41 * w.v56)) + (w.v12 * w.v55)) + (w.v12 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v17 - ((((w.v43 * w.v57) + (w.v42 * w.v56)) + (w.v41 * w.v55)) + (w.v13 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v58 * (w.v18 - ((((w.v44 * w.v57) + (w.v43 * w.v56)) + (w.v42 * w.v55)) + (w.v41 * ((((1 : F) - w.v55) - w.v56) - w.v57))))) = 0 ∧
  (w.v53 * (w.v41 - ((((w.v18 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v17 * w.v55)) + (w.v16 * w.v56)) + (w.v15 * w.v57)))) = 0 ∧
  (w.v53 * (w.v42 - ((((w.v38 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v18 * w.v55)) + (w.v17 * w.v56)) + (w.v16 * w.v57)))) = 0 ∧
  (w.v53 * (w.v43 - (((w.v39 * (((((1 : F) - w.v55) - w.v56) - w.v57) + w.v55)) + (w.v18 * w.v56)) + (w.v17 * w.v57)))) = 0

def constraints_1 (w : W) : Prop :=
  (w.v53 * (w.v44 - ((w.v40 * ((1 : F) - w.v57)) + (w.v18 * w.v57)))) = 0 ∧
  (w.v54 * (w.v41 - ((w.v15 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v37 * ((1 : F) - ((((1 : F) - w.v55) - w.v56) - w.v57)))))) = 0 ∧
  (w.v54 * (w.v42 - (((w.v16 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v15 * w.v55)) + (w.v38 * (w.v56 + w.v57))))) = 0 ∧
  (w.v54 * (w.v43 - ((((w.v17 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v16 * w.v55)) + (w.v15 * w.v56)) + (w.v39 * w.v57)))) = 0 ∧
  (w.v54 * (w.v44 - ((((w.v18 * ((((1 : F) - w.v55) - w.v56) - w.v57)) + (w.v17 * w.v55)) + (w.v16 * w.v56)) + (w.v15 * w.v57)))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * (w.v3 - ((((w.v51 * (36 : F)) + (w.v52 * (37 : F))) + (w.v53 * (42 : F))) + (w.v54 * (43 : F))))) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F))) = 0 ∧
  (w.v10 * w.v15) = 0 ∧
  (w.v10 * w.v16) = 0 ∧
  (w.v10 * w.v17) = 0 ∧
  (w.v10 * w.v18) = 0 ∧
  ((((w.v51 + w.v52) + w.v53) + w.v54) * ((((w.v51 + w.v52) + w.v53) + w.v54) - (1 : F))) = 0 ∧
  (((w.v53 + w.v54) * (((w.v51 + w.v52) + w.v53) + w.v54)) * (w.v15 - w.v11)) = 0 ∧
  (((w.v53 + w.v54) * (((w.v51 + w.v52) + w.v53) + w.v54)) * (w.v16 - w.v12)) = 0 ∧
  (((w.v53 + w.v54) * (((w.v51 + w.v52) + w.v53) + w.v54)) * (w.v17 - w.v13)) = 0 ∧
  (((w.v53 + w.v54) * (((w.v51 + w.v52) + w.v53) + w.v54)) * (w.v18 - w.v14)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v51, w.v52, w.v53, w.v54]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v51 * (w.v51 - (1 : F))) = 0 ∧
    (w.v52 * (w.v52 - (1 : F))) = 0 ∧
    (w.v53 * (w.v53 - (1 : F))) = 0 ∧
    (w.v54 * (w.v54 - (1 : F))) = 0 ∧
    ((((w.v51 + w.v52) + w.v53) + w.v54)).val < ((2 : F)).val := by
  picus_det [constraints_0, constraints_1]

end top

end ZirenDet.Chips.MemoryUnaligned
