/-
  Generated by `cargo run -p zkm-picus -- --chip MemoryGlobalFinalize --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.MemoryGlobalFinalize

open ZirenDet

/-! ### Module `MemoryGlobalFinalize` -/
namespace MemoryGlobalFinalize

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `shard_0` -/
  v0 : F
  /-- `timestamp_1` -/
  v1 : F
  /-- `addr_2` -/
  v2 : F
  /-- `index_3` -/
  v3 : F
  /-- `prev_addr_4` -/
  v4 : F
  /-- `prev_addr_bits_5` -/
  v5 : F
  /-- `prev_addr_bits_6` -/
  v6 : F
  /-- `prev_addr_bits_7` -/
  v7 : F
  /-- `prev_addr_bits_8` -/
  v8 : F
  /-- `prev_addr_bits_9` -/
  v9 : F
  /-- `prev_addr_bits_10` -/
  v10 : F
  /-- `prev_addr_bits_11` -/
  v11 : F
  /-- `prev_addr_bits_12` -/
  v12 : F
  /-- `prev_addr_bits_13` -/
  v13 : F
  /-- `prev_addr_bits_14` -/
  v14 : F
  /-- `prev_addr_bits_15` -/
  v15 : F
  /-- `prev_addr_bits_16` -/
  v16 : F
  /-- `prev_addr_bits_17` -/
  v17 : F
  /-- `prev_addr_bits_18` -/
  v18 : F
  /-- `prev_addr_bits_19` -/
  v19 : F
  /-- `prev_addr_bits_20` -/
  v20 : F
  /-- `prev_addr_bits_21` -/
  v21 : F
  /-- `prev_addr_bits_22` -/
  v22 : F
  /-- `prev_addr_bits_23` -/
  v23 : F
  /-- `prev_addr_bits_24` -/
  v24 : F
  /-- `prev_addr_bits_25` -/
  v25 : F
  /-- `prev_addr_bits_26` -/
  v26 : F
  /-- `prev_addr_bits_27` -/
  v27 : F
  /-- `prev_addr_bits_28` -/
  v28 : F
  /-- `prev_addr_bits_29` -/
  v29 : F
  /-- `prev_addr_bits_30` -/
  v30 : F
  /-- `prev_addr_bits_31` -/
  v31 : F
  /-- `prev_addr_bits_32` -/
  v32 : F
  /-- `prev_addr_bits_33` -/
  v33 : F
  /-- `prev_addr_bits_34` -/
  v34 : F
  /-- `prev_addr_bits_35` -/
  v35 : F
  /-- `prev_addr_bits_36` -/
  v36 : F
  /-- `prev_addr_bits_37` -/
  v37 : F
  /-- `prev_addr_bits_38` -/
  v38 : F
  /-- `prev_addr_bits_39` -/
  v39 : F
  /-- `prev_addr_bits_40` -/
  v40 : F
  /-- `prev_addr_bits_41` -/
  v41 : F
  /-- `prev_addr_bits_42` -/
  v42 : F
  /-- `prev_valid_43` -/
  v43 : F
  /-- `lt_cols_44` -/
  v44 : F
  /-- `lt_cols_45` -/
  v45 : F
  /-- `lt_cols_46` -/
  v46 : F
  /-- `lt_cols_47` -/
  v47 : F
  /-- `lt_cols_48` -/
  v48 : F
  /-- `lt_cols_49` -/
  v49 : F
  /-- `lt_cols_50` -/
  v50 : F
  /-- `lt_cols_51` -/
  v51 : F
  /-- `lt_cols_52` -/
  v52 : F
  /-- `lt_cols_53` -/
  v53 : F
  /-- `lt_cols_54` -/
  v54 : F
  /-- `lt_cols_55` -/
  v55 : F
  /-- `lt_cols_56` -/
  v56 : F
  /-- `lt_cols_57` -/
  v57 : F
  /-- `lt_cols_58` -/
  v58 : F
  /-- `lt_cols_59` -/
  v59 : F
  /-- `lt_cols_60` -/
  v60 : F
  /-- `lt_cols_61` -/
  v61 : F
  /-- `lt_cols_62` -/
  v62 : F
  /-- `lt_cols_63` -/
  v63 : F
  /-- `lt_cols_64` -/
  v64 : F
  /-- `lt_cols_65` -/
  v65 : F
  /-- `lt_cols_66` -/
  v66 : F
  /-- `lt_cols_67` -/
  v67 : F
  /-- `lt_cols_68` -/
  v68 : F
  /-- `lt_cols_69` -/
  v69 : F
  /-- `lt_cols_70` -/
  v70 : F
  /-- `lt_cols_71` -/
  v71 : F
  /-- `lt_cols_72` -/
  v72 : F
  /-- `lt_cols_73` -/
  v73 : F
  /-- `lt_cols_74` -/
  v74 : F
  /-- `lt_cols_75` -/
  v75 : F
  /-- `addr_bits_76` -/
  v76 : F
  /-- `addr_bits_77` -/
  v77 : F
  /-- `addr_bits_78` -/
  v78 : F
  /-- `addr_bits_79` -/
  v79 : F
  /-- `addr_bits_80` -/
  v80 : F
  /-- `addr_bits_81` -/
  v81 : F
  /-- `addr_bits_82` -/
  v82 : F
  /-- `addr_bits_83` -/
  v83 : F
  /-- `addr_bits_84` -/
  v84 : F
  /-- `addr_bits_85` -/
  v85 : F
  /-- `addr_bits_86` -/
  v86 : F
  /-- `addr_bits_87` -/
  v87 : F
  /-- `addr_bits_88` -/
  v88 : F
  /-- `addr_bits_89` -/
  v89 : F
  /-- `addr_bits_90` -/
  v90 : F
  /-- `addr_bits_91` -/
  v91 : F
  /-- `addr_bits_92` -/
  v92 : F
  /-- `addr_bits_93` -/
  v93 : F
  /-- `addr_bits_94` -/
  v94 : F
  /-- `addr_bits_95` -/
  v95 : F
  /-- `addr_bits_96` -/
  v96 : F
  /-- `addr_bits_97` -/
  v97 : F
  /-- `addr_bits_98` -/
  v98 : F
  /-- `addr_bits_99` -/
  v99 : F
  /-- `addr_bits_100` -/
  v100 : F
  /-- `addr_bits_101` -/
  v101 : F
  /-- `addr_bits_102` -/
  v102 : F
  /-- `addr_bits_103` -/
  v103 : F
  /-- `addr_bits_104` -/
  v104 : F
  /-- `addr_bits_105` -/
  v105 : F
  /-- `addr_bits_106` -/
  v106 : F
  /-- `addr_bits_107` -/
  v107 : F
  /-- `addr_bits_108` -/
  v108 : F
  /-- `addr_bits_109` -/
  v109 : F
  /-- `addr_bits_110` -/
  v110 : F
  /-- `addr_bits_111` -/
  v111 : F
  /-- `addr_bits_112` -/
  v112 : F
  /-- `addr_bits_113` -/
  v113 : F
  /-- `value_114` -/
  v114 : F
  /-- `value_115` -/
  v115 : F
  /-- `value_116` -/
  v116 : F
  /-- `value_117` -/
  v117 : F
  /-- `value_118` -/
  v118 : F
  /-- `value_119` -/
  v119 : F
  /-- `value_120` -/
  v120 : F
  /-- `value_121` -/
  v121 : F
  /-- `value_122` -/
  v122 : F
  /-- `value_123` -/
  v123 : F
  /-- `value_124` -/
  v124 : F
  /-- `value_125` -/
  v125 : F
  /-- `value_126` -/
  v126 : F
  /-- `value_127` -/
  v127 : F
  /-- `value_128` -/
  v128 : F
  /-- `value_129` -/
  v129 : F
  /-- `value_130` -/
  v130 : F
  /-- `value_131` -/
  v131 : F
  /-- `value_132` -/
  v132 : F
  /-- `value_133` -/
  v133 : F
  /-- `value_134` -/
  v134 : F
  /-- `value_135` -/
  v135 : F
  /-- `value_136` -/
  v136 : F
  /-- `value_137` -/
  v137 : F
  /-- `value_138` -/
  v138 : F
  /-- `value_139` -/
  v139 : F
  /-- `value_140` -/
  v140 : F
  /-- `value_141` -/
  v141 : F
  /-- `value_142` -/
  v142 : F
  /-- `value_143` -/
  v143 : F
  /-- `value_144` -/
  v144 : F
  /-- `value_145` -/
  v145 : F
  /-- `is_comp_147` -/
  v147 : F
  /-- `is_prev_addr_zero_148` -/
  v148 : F
  /-- `is_prev_addr_zero_149` -/
  v149 : F
  /-- `is_index_zero_150` -/
  v150 : F
  /-- `is_index_zero_151` -/
  v151 : F
  v538 : F
  v539 : F
  v540 : F
  v541 : F
  v542 : F
  v543 : F
  v544 : F
  v545 : F
  v546 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (w.v114 * (w.v114 - (1 : F))) = 0 ∧
  (w.v115 * (w.v115 - (1 : F))) = 0 ∧
  (w.v116 * (w.v116 - (1 : F))) = 0 ∧
  (w.v117 * (w.v117 - (1 : F))) = 0 ∧
  (w.v118 * (w.v118 - (1 : F))) = 0 ∧
  (w.v119 * (w.v119 - (1 : F))) = 0 ∧
  (w.v120 * (w.v120 - (1 : F))) = 0 ∧
  (w.v121 * (w.v121 - (1 : F))) = 0 ∧
  (w.v122 * (w.v122 - (1 : F))) = 0 ∧
  (w.v123 * (w.v123 - (1 : F))) = 0 ∧
  (w.v124 * (w.v124 - (1 : F))) = 0 ∧
  (w.v125 * (w.v125 - (1 : F))) = 0 ∧
  (w.v126 * (w.v126 - (1 : F))) = 0 ∧
  (w.v127 * (w.v127 - (1 : F))) = 0 ∧
  (w.v128 * (w.v128 - (1 : F))) = 0 ∧
  (w.v129 * (w.v129 - (1 : F))) = 0 ∧
  (w.v130 * (w.v130 - (1 : F))) = 0 ∧
  (w.v131 * (w.v131 - (1 : F))) = 0 ∧
  (w.v132 * (w.v132 - (1 : F))) = 0 ∧
  (w.v133 * (w.v133 - (1 : F))) = 0 ∧
  (w.v134 * (w.v134 - (1 : F))) = 0 ∧
  (w.v135 * (w.v135 - (1 : F))) = 0 ∧
  (w.v136 * (w.v136 - (1 : F))) = 0 ∧
  (w.v137 * (w.v137 - (1 : F))) = 0 ∧
  (w.v138 * (w.v138 - (1 : F))) = 0 ∧
  (w.v139 * (w.v139 - (1 : F))) = 0 ∧
  (w.v140 * (w.v140 - (1 : F))) = 0 ∧
  (w.v141 * (w.v141 - (1 : F))) = 0 ∧
  (w.v142 * (w.v142 - (1 : F))) = 0 ∧
  (w.v143 * (w.v143 - (1 : F))) = 0 ∧
  (w.v144 * (w.v144 - (1 : F))) = 0 ∧
  (w.v145 * (w.v145 - (1 : F))) = 0 ∧
  (w.v76 * (w.v76 - (1 : F))) = 0 ∧
  (w.v77 * (w.v77 - (1 : F))) = 0 ∧
  (w.v78 * (w.v78 - (1 : F))) = 0 ∧
  (w.v79 * (w.v79 - (1 : F))) = 0 ∧
  (w.v80 * (w.v80 - (1 : F))) = 0 ∧
  (w.v81 * (w.v81 - (1 : F))) = 0 ∧
  (w.v82 * (w.v82 - (1 : F))) = 0 ∧
  (w.v83 * (w.v83 - (1 : F))) = 0 ∧
  (w.v84 * (w.v84 - (1 : F))) = 0 ∧
  (w.v85 * (w.v85 - (1 : F))) = 0 ∧
  (w.v86 * (w.v86 - (1 : F))) = 0 ∧
  (w.v87 * (w.v87 - (1 : F))) = 0 ∧
  (w.v88 * (w.v88 - (1 : F))) = 0 ∧
  (w.v89 * (w.v89 - (1 : F))) = 0 ∧
  (w.v90 * (w.v90 - (1 : F))) = 0 ∧
  (w.v91 * (w.v91 - (1 : F))) = 0

def constraints_1 (w : W) : Prop :=
  (w.v92 * (w.v92 - (1 : F))) = 0 ∧
  (w.v93 * (w.v93 - (1 : F))) = 0 ∧
  (w.v94 * (w.v94 - (1 : F))) = 0 ∧
  (w.v95 * (w.v95 - (1 : F))) = 0 ∧
  (w.v96 * (w.v96 - (1 : F))) = 0 ∧
  (w.v97 * (w.v97 - (1 : F))) = 0 ∧
  (w.v98 * (w.v98 - (1 : F))) = 0 ∧
  (w.v99 * (w.v99 - (1 : F))) = 0 ∧
  (w.v100 * (w.v100 - (1 : F))) = 0 ∧
  (w.v101 * (w.v101 - (1 : F))) = 0 ∧
  (w.v102 * (w.v102 - (1 : F))) = 0 ∧
  (w.v103 * (w.v103 - (1 : F))) = 0 ∧
  (w.v104 * (w.v104 - (1 : F))) = 0 ∧
  (w.v105 * (w.v105 - (1 : F))) = 0 ∧
  (w.v106 * (w.v106 - (1 : F))) = 0 ∧
  (w.v107 * (w.v107 - (1 : F))) = 0 ∧
  w.v538 = 0 ∧
  w.v107 = 0 ∧
  (w.v108 - (w.v100 * w.v101)) = 0 ∧
  (w.v109 - (w.v108 * w.v102)) = 0 ∧
  (w.v110 - (w.v109 * w.v103)) = 0 ∧
  (w.v111 - (w.v110 * w.v104)) = 0 ∧
  (w.v112 - (w.v111 * w.v105)) = 0 ∧
  (w.v113 - (w.v112 * w.v106)) = 0 ∧
  (w.v113 * (((((((((((((((((((((((w.v76 + w.v77) + w.v78) + w.v79) + w.v80) + w.v81) + w.v82) + w.v83) + w.v84) + w.v85) + w.v86) + w.v87) + w.v88) + w.v89) + w.v90) + w.v91) + w.v92) + w.v93) + w.v94) + w.v95) + w.v96) + w.v97) + w.v98) + w.v99)) = 0 ∧
  (w.v5 * (w.v5 - (1 : F))) = 0 ∧
  (w.v6 * (w.v6 - (1 : F))) = 0 ∧
  (w.v7 * (w.v7 - (1 : F))) = 0 ∧
  (w.v8 * (w.v8 - (1 : F))) = 0 ∧
  (w.v9 * (w.v9 - (1 : F))) = 0 ∧
  (w.v10 * (w.v10 - (1 : F))) = 0 ∧
  (w.v11 * (w.v11 - (1 : F))) = 0 ∧
  (w.v12 * (w.v12 - (1 : F))) = 0 ∧
  (w.v13 * (w.v13 - (1 : F))) = 0 ∧
  (w.v14 * (w.v14 - (1 : F))) = 0 ∧
  (w.v15 * (w.v15 - (1 : F))) = 0 ∧
  (w.v16 * (w.v16 - (1 : F))) = 0 ∧
  (w.v17 * (w.v17 - (1 : F))) = 0 ∧
  (w.v18 * (w.v18 - (1 : F))) = 0 ∧
  (w.v19 * (w.v19 - (1 : F))) = 0 ∧
  (w.v20 * (w.v20 - (1 : F))) = 0 ∧
  (w.v21 * (w.v21 - (1 : F))) = 0 ∧
  (w.v22 * (w.v22 - (1 : F))) = 0 ∧
  (w.v23 * (w.v23 - (1 : F))) = 0 ∧
  (w.v24 * (w.v24 - (1 : F))) = 0 ∧
  (w.v25 * (w.v25 - (1 : F))) = 0 ∧
  (w.v26 * (w.v26 - (1 : F))) = 0 ∧
  (w.v27 * (w.v27 - (1 : F))) = 0

def constraints_2 (w : W) : Prop :=
  (w.v28 * (w.v28 - (1 : F))) = 0 ∧
  (w.v29 * (w.v29 - (1 : F))) = 0 ∧
  (w.v30 * (w.v30 - (1 : F))) = 0 ∧
  (w.v31 * (w.v31 - (1 : F))) = 0 ∧
  (w.v32 * (w.v32 - (1 : F))) = 0 ∧
  (w.v33 * (w.v33 - (1 : F))) = 0 ∧
  (w.v34 * (w.v34 - (1 : F))) = 0 ∧
  (w.v35 * (w.v35 - (1 : F))) = 0 ∧
  (w.v36 * (w.v36 - (1 : F))) = 0 ∧
  w.v539 = 0 ∧
  w.v36 = 0 ∧
  (w.v37 - (w.v29 * w.v30)) = 0 ∧
  (w.v38 - (w.v37 * w.v31)) = 0 ∧
  (w.v39 - (w.v38 * w.v32)) = 0 ∧
  (w.v40 - (w.v39 * w.v33)) = 0 ∧
  (w.v41 - (w.v40 * w.v34)) = 0 ∧
  (w.v42 - (w.v41 * w.v35)) = 0 ∧
  (w.v42 * (((((((((((((((((((((((w.v5 + w.v6) + w.v7) + w.v8) + w.v9) + w.v10) + w.v11) + w.v12) + w.v13) + w.v14) + w.v15) + w.v16) + w.v17) + w.v18) + w.v19) + w.v20) + w.v21) + w.v22) + w.v23) + w.v24) + w.v25) + w.v26) + w.v27) + w.v28)) = 0 ∧
  (((1 : F) - (w.v148 * w.v4)) - w.v149) = 0 ∧
  (w.v149 * (w.v149 - (1 : F))) = 0 ∧
  (w.v149 * w.v4) = 0 ∧
  (((1 : F) - (w.v150 * w.v3)) - w.v151) = 0 ∧
  (w.v151 * (w.v151 - (1 : F))) = 0 ∧
  (w.v151 * w.v3) = 0 ∧
  (w.v147 * (w.v147 - (1 : F))) = 0 ∧
  (w.v147 - ((1 : F) - (w.v149 * w.v151))) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v45 * (w.v45 - (1 : F))) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (w.v47 * (w.v47 - (1 : F))) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v49 * (w.v49 - (1 : F))) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (w.v51 * (w.v51 - (1 : F))) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v53 * (w.v53 - (1 : F))) = 0 ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v58 * (w.v58 - (1 : F))) = 0 ∧
  (w.v59 * (w.v59 - (1 : F))) = 0 ∧
  (w.v60 * (w.v60 - (1 : F))) = 0 ∧
  (w.v61 * (w.v61 - (1 : F))) = 0 ∧
  (w.v62 * (w.v62 - (1 : F))) = 0 ∧
  (w.v63 * (w.v63 - (1 : F))) = 0 ∧
  (w.v64 * (w.v64 - (1 : F))) = 0 ∧
  (w.v65 * (w.v65 - (1 : F))) = 0

def constraints_3 (w : W) : Prop :=
  (w.v66 * (w.v66 - (1 : F))) = 0 ∧
  (w.v67 * (w.v67 - (1 : F))) = 0 ∧
  (w.v68 * (w.v68 - (1 : F))) = 0 ∧
  (w.v69 * (w.v69 - (1 : F))) = 0 ∧
  (w.v70 * (w.v70 - (1 : F))) = 0 ∧
  (w.v71 * (w.v71 - (1 : F))) = 0 ∧
  (w.v72 * (w.v72 - (1 : F))) = 0 ∧
  (w.v73 * (w.v73 - (1 : F))) = 0 ∧
  (w.v74 * (w.v74 - (1 : F))) = 0 ∧
  (w.v75 * (w.v75 - (1 : F))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((((((((((w.v44 + w.v45) + w.v46) + w.v47) + w.v48) + w.v49) + w.v50) + w.v51) + w.v52) + w.v53) + w.v54) + w.v55) + w.v56) + w.v57) + w.v58) + w.v59) + w.v60) + w.v61) + w.v62) + w.v63) + w.v64) + w.v65) + w.v66) + w.v67) + w.v68) + w.v69) + w.v70) + w.v71) + w.v72) + w.v73) + w.v74) + w.v75) - (1 : F))) = 0 ∧
  (w.v147 * ((w.v75 - (1 : F)) * (w.v36 - w.v107))) = 0 ∧
  (w.v147 * (((w.v75 + w.v74) - (1 : F)) * (w.v35 - w.v106))) = 0 ∧
  (w.v147 * ((((w.v75 + w.v74) + w.v73) - (1 : F)) * (w.v34 - w.v105))) = 0 ∧
  (w.v147 * (((((w.v75 + w.v74) + w.v73) + w.v72) - (1 : F)) * (w.v33 - w.v104))) = 0 ∧
  (w.v147 * ((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) - (1 : F)) * (w.v32 - w.v103))) = 0 ∧
  (w.v147 * (((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) - (1 : F)) * (w.v31 - w.v102))) = 0 ∧
  (w.v147 * ((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) - (1 : F)) * (w.v30 - w.v101))) = 0 ∧
  (w.v147 * (((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) - (1 : F)) * (w.v29 - w.v100))) = 0 ∧
  (w.v147 * ((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) - (1 : F)) * (w.v28 - w.v99))) = 0 ∧
  (w.v147 * (((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) - (1 : F)) * (w.v27 - w.v98))) = 0 ∧
  (w.v147 * ((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) - (1 : F)) * (w.v26 - w.v97))) = 0 ∧
  (w.v147 * (((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) - (1 : F)) * (w.v25 - w.v96))) = 0 ∧
  (w.v147 * ((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) - (1 : F)) * (w.v24 - w.v95))) = 0 ∧
  (w.v147 * (((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) - (1 : F)) * (w.v23 - w.v94))) = 0 ∧
  (w.v147 * ((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) - (1 : F)) * (w.v22 - w.v93))) = 0 ∧
  (w.v147 * (((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) - (1 : F)) * (w.v21 - w.v92))) = 0 ∧
  (w.v147 * ((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) - (1 : F)) * (w.v20 - w.v91))) = 0 ∧
  (w.v147 * (((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) - (1 : F)) * (w.v19 - w.v90))) = 0 ∧
  (w.v147 * ((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) - (1 : F)) * (w.v18 - w.v89))) = 0 ∧
  (w.v147 * (((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) - (1 : F)) * (w.v17 - w.v88))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) - (1 : F)) * (w.v16 - w.v87))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) - (1 : F)) * (w.v15 - w.v86))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) - (1 : F)) * (w.v14 - w.v85))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) - (1 : F)) * (w.v13 - w.v84))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) - (1 : F)) * (w.v12 - w.v83))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) - (1 : F)) * (w.v11 - w.v82))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) - (1 : F)) * (w.v10 - w.v81))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) + w.v48) - (1 : F)) * (w.v9 - w.v80))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) + w.v48) + w.v47) - (1 : F)) * (w.v8 - w.v79))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) + w.v48) + w.v47) + w.v46) - (1 : F)) * (w.v7 - w.v78))) = 0 ∧
  (w.v147 * ((((((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) + w.v48) + w.v47) + w.v46) + w.v45) - (1 : F)) * (w.v6 - w.v77))) = 0 ∧
  (w.v147 * (((((((((((((((((((((((((((((((((w.v75 + w.v74) + w.v73) + w.v72) + w.v71) + w.v70) + w.v69) + w.v68) + w.v67) + w.v66) + w.v65) + w.v64) + w.v63) + w.v62) + w.v61) + w.v60) + w.v59) + w.v58) + w.v57) + w.v56) + w.v55) + w.v54) + w.v53) + w.v52) + w.v51) + w.v50) + w.v49) + w.v48) + w.v47) + w.v46) + w.v45) + w.v44) - (1 : F)) * (w.v5 - w.v76))) = 0 ∧
  w.v540 = 0 ∧
  (w.v147 * w.v541) = 0 ∧
  (((1 : F) - w.v147) * w.v2) = 0 ∧
  (((1 : F) - w.v147) * w.v114) = 0 ∧
  (((1 : F) - w.v147) * w.v115) = 0

def constraints_4 (w : W) : Prop :=
  (((1 : F) - w.v147) * w.v116) = 0 ∧
  (((1 : F) - w.v147) * w.v117) = 0 ∧
  (((1 : F) - w.v147) * w.v118) = 0 ∧
  (((1 : F) - w.v147) * w.v119) = 0 ∧
  (((1 : F) - w.v147) * w.v120) = 0 ∧
  (((1 : F) - w.v147) * w.v121) = 0 ∧
  (((1 : F) - w.v147) * w.v122) = 0 ∧
  (((1 : F) - w.v147) * w.v123) = 0 ∧
  (((1 : F) - w.v147) * w.v124) = 0 ∧
  (((1 : F) - w.v147) * w.v125) = 0 ∧
  (((1 : F) - w.v147) * w.v126) = 0 ∧
  (((1 : F) - w.v147) * w.v127) = 0 ∧
  (((1 : F) - w.v147) * w.v128) = 0 ∧
  (((1 : F) - w.v147) * w.v129) = 0 ∧
  (((1 : F) - w.v147) * w.v130) = 0 ∧
  (((1 : F) - w.v147) * w.v131) = 0 ∧
  (((1 : F) - w.v147) * w.v132) = 0 ∧
  (((1 : F) - w.v147) * w.v133) = 0 ∧
  (((1 : F) - w.v147) * w.v134) = 0 ∧
  (((1 : F) - w.v147) * w.v135) = 0 ∧
  (((1 : F) - w.v147) * w.v136) = 0 ∧
  (((1 : F) - w.v147) * w.v137) = 0 ∧
  (((1 : F) - w.v147) * w.v138) = 0 ∧
  (((1 : F) - w.v147) * w.v139) = 0 ∧
  (((1 : F) - w.v147) * w.v140) = 0 ∧
  (((1 : F) - w.v147) * w.v141) = 0 ∧
  (((1 : F) - w.v147) * w.v142) = 0 ∧
  (((1 : F) - w.v147) * w.v143) = 0 ∧
  (((1 : F) - w.v147) * w.v144) = 0 ∧
  (((1 : F) - w.v147) * w.v145) = 0 ∧
  (w.v538 - ((((((((((((((((((((((((((((((((w.v76 + (w.v77 * (2 : F))) + (w.v78 * (4 : F))) + (w.v79 * (8 : F))) + (w.v80 * (16 : F))) + (w.v81 * (32 : F))) + (w.v82 * (64 : F))) + (w.v83 * (128 : F))) + (w.v84 * (256 : F))) + (w.v85 * (512 : F))) + (w.v86 * (1024 : F))) + (w.v87 * (2048 : F))) + (w.v88 * (4096 : F))) + (w.v89 * (8192 : F))) + (w.v90 * (16384 : F))) + (w.v91 * (32768 : F))) + (w.v92 * (65536 : F))) + (w.v93 * (131072 : F))) + (w.v94 * (262144 : F))) + (w.v95 * (524288 : F))) + (w.v96 * (1048576 : F))) + (w.v97 * (2097152 : F))) + (w.v98 * (4194304 : F))) + (w.v99 * (8388608 : F))) + (w.v100 * (16777216 : F))) + (w.v101 * (33554432 : F))) + (w.v102 * (67108864 : F))) + (w.v103 * (134217728 : F))) + (w.v104 * (268435456 : F))) + (w.v105 * (536870912 : F))) + (w.v106 * (1073741824 : F))) + (w.v107 * (16777215 : F))) - w.v2)) = 0 ∧
  (w.v539 - ((((((((((((((((((((((((((((((((w.v5 + (w.v6 * (2 : F))) + (w.v7 * (4 : F))) + (w.v8 * (8 : F))) + (w.v9 * (16 : F))) + (w.v10 * (32 : F))) + (w.v11 * (64 : F))) + (w.v12 * (128 : F))) + (w.v13 * (256 : F))) + (w.v14 * (512 : F))) + (w.v15 * (1024 : F))) + (w.v16 * (2048 : F))) + (w.v17 * (4096 : F))) + (w.v18 * (8192 : F))) + (w.v19 * (16384 : F))) + (w.v20 * (32768 : F))) + (w.v21 * (65536 : F))) + (w.v22 * (131072 : F))) + (w.v23 * (262144 : F))) + (w.v24 * (524288 : F))) + (w.v25 * (1048576 : F))) + (w.v26 * (2097152 : F))) + (w.v27 * (4194304 : F))) + (w.v28 * (8388608 : F))) + (w.v29 * (16777216 : F))) + (w.v30 * (33554432 : F))) + (w.v31 * (67108864 : F))) + (w.v32 * (134217728 : F))) + (w.v33 * (268435456 : F))) + (w.v34 * (536870912 : F))) + (w.v35 * (1073741824 : F))) + (w.v36 * (16777215 : F))) - w.v4)) = 0 ∧
  (w.v540 - (w.v147 * ((((((((((((((((((((((((((((((((w.v36 * w.v75) + (w.v35 * w.v74)) + (w.v34 * w.v73)) + (w.v33 * w.v72)) + (w.v32 * w.v71)) + (w.v31 * w.v70)) + (w.v30 * w.v69)) + (w.v29 * w.v68)) + (w.v28 * w.v67)) + (w.v27 * w.v66)) + (w.v26 * w.v65)) + (w.v25 * w.v64)) + (w.v24 * w.v63)) + (w.v23 * w.v62)) + (w.v22 * w.v61)) + (w.v21 * w.v60)) + (w.v20 * w.v59)) + (w.v19 * w.v58)) + (w.v18 * w.v57)) + (w.v17 * w.v56)) + (w.v16 * w.v55)) + (w.v15 * w.v54)) + (w.v14 * w.v53)) + (w.v13 * w.v52)) + (w.v12 * w.v51)) + (w.v11 * w.v50)) + (w.v10 * w.v49)) + (w.v9 * w.v48)) + (w.v8 * w.v47)) + (w.v7 * w.v46)) + (w.v6 * w.v45)) + (w.v5 * w.v44)))) = 0 ∧
  (w.v541 - (((((((((((((((((((((((((((((((((w.v107 * w.v75) + (w.v106 * w.v74)) + (w.v105 * w.v73)) + (w.v104 * w.v72)) + (w.v103 * w.v71)) + (w.v102 * w.v70)) + (w.v101 * w.v69)) + (w.v100 * w.v68)) + (w.v99 * w.v67)) + (w.v98 * w.v66)) + (w.v97 * w.v65)) + (w.v96 * w.v64)) + (w.v95 * w.v63)) + (w.v94 * w.v62)) + (w.v93 * w.v61)) + (w.v92 * w.v60)) + (w.v91 * w.v59)) + (w.v90 * w.v58)) + (w.v89 * w.v57)) + (w.v88 * w.v56)) + (w.v87 * w.v55)) + (w.v86 * w.v54)) + (w.v85 * w.v53)) + (w.v84 * w.v52)) + (w.v83 * w.v51)) + (w.v82 * w.v50)) + (w.v81 * w.v49)) + (w.v80 * w.v48)) + (w.v79 * w.v47)) + (w.v78 * w.v46)) + (w.v77 * w.v45)) + (w.v76 * w.v44)) - (1 : F))) = 0 ∧
  (w.v542 - (((((((w.v114 + (w.v115 * (2 : F))) + (w.v116 * (4 : F))) + (w.v117 * (8 : F))) + (w.v118 * (16 : F))) + (w.v119 * (32 : F))) + (w.v120 * (64 : F))) + (w.v121 * (128 : F)))) = 0 ∧
  (w.v543 - (((((((w.v122 + (w.v123 * (2 : F))) + (w.v124 * (4 : F))) + (w.v125 * (8 : F))) + (w.v126 * (16 : F))) + (w.v127 * (32 : F))) + (w.v128 * (64 : F))) + (w.v129 * (128 : F)))) = 0 ∧
  (w.v544 - (((((((w.v130 + (w.v131 * (2 : F))) + (w.v132 * (4 : F))) + (w.v133 * (8 : F))) + (w.v134 * (16 : F))) + (w.v135 * (32 : F))) + (w.v136 * (64 : F))) + (w.v137 * (128 : F)))) = 0 ∧
  (w.v545 - (((((((w.v138 + (w.v139 * (2 : F))) + (w.v140 * (4 : F))) + (w.v141 * (8 : F))) + (w.v142 * (16 : F))) + (w.v143 * (32 : F))) + (w.v144 * (64 : F))) + (w.v145 * (128 : F)))) = 0 ∧
  (w.v546 - (w.v3 + (1 : F))) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w ∧
  constraints_2 w ∧
  constraints_3 w ∧
  constraints_4 w

/-- Interface provenance (which lookup each port comes from).
  inputs:  v3 = memoryglobalfinalizecontrol_recv[0], v4 = memoryglobalfinalizecontrol_recv[1], v43 = memoryglobalfinalizecontrol_recv[2]
  outputs: v0 = global_send[0], v1 = global_send[1], v2 = global_send[2], v542 = global_send[3], v543 = global_send[4], v544 = global_send[5], v545 = global_send[6], v546 = memoryglobalfinalizecontrol_send[0], v147 = memoryglobalfinalizecontrol_send[2] -/
def input_origins : List String := ["memoryglobalfinalizecontrol_recv[0]", "memoryglobalfinalizecontrol_recv[1]", "memoryglobalfinalizecontrol_recv[2]"]
def output_origins : List String := ["global_send[0]", "global_send[1]", "global_send[2]", "global_send[3]", "global_send[4]", "global_send[5]", "global_send[6]", "memoryglobalfinalizecontrol_send[0]", "memoryglobalfinalizecontrol_send[2]"]
def in_memoryglobalfinalizecontrol_recv (w : W) : List F := [w.v3, w.v4, w.v43]
def out_global_send (w : W) : List F := [w.v0, w.v1, w.v2, w.v542, w.v543, w.v544, w.v545]
def out_memoryglobalfinalizecontrol_send (w : W) : List F := [w.v546, w.v147]

def inputs (w : W) : List F :=
  [w.v3, w.v4, w.v43]
def outputs (w : W) : List F :=
  [w.v0, w.v1, w.v2, w.v542, w.v543, w.v544, w.v545, w.v546, w.v147]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1, constraints_2, constraints_3, constraints_4]

end MemoryGlobalFinalize

end ZirenDet.Chips.MemoryGlobalFinalize
