/-
  Generated by `cargo run -p zkm-picus -- --chip MovCond --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

namespace ZirenDet.Chips.MovCond

open ZirenDet

/-! ### Module `MovCond__is_meq` -/
namespace MovCond_is_meq

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `c_eq_lo_2` -/
  v2 : F
  /-- `c_eq_lo_inv_3` -/
  v3 : F
  /-- `c_eq_hi_4` -/
  v4 : F
  /-- `c_eq_hi_inv_5` -/
  v5 : F
  /-- `c_eq_0_6` -/
  v6 : F
  /-- `sel_moved_7` -/
  v7 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `frame_42` -/
  v42 : F
  /-- `frame_43` -/
  v43 : F
  /-- `frame_44` -/
  v44 : F
  /-- `frame_45` -/
  v45 : F
  /-- `frame_46` -/
  v46 : F
  /-- `frame_47` -/
  v47 : F
  /-- `frame_48` -/
  v48 : F
  v355 : F
  v356 : F
  v357 : F
  v358 : F
  v359 : F
  v360 : F
  v361 : F
  v362 : F
  v363 : F
  v364 : F
  v365 : F
  v366 : F
  v367 : F
  v368 : F
  v369 : F
  v370 : F
  v371 : F
  v372 : F
  v373 : F
  v374 : F
  v375 : F
  v376 : F
  v377 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints (w : W) : Prop :=
  (w.v14 - (50 : F)) = 0 ∧
  (w.v25 * (w.v37 - w.v16)) = 0 ∧
  (w.v25 * (w.v38 - w.v17)) = 0 ∧
  (w.v25 * (w.v39 - w.v18)) = 0 ∧
  (w.v25 * (w.v40 - w.v19)) = 0 ∧
  (w.v26 * (w.v43 - w.v20)) = 0 ∧
  (w.v26 * (w.v44 - w.v21)) = 0 ∧
  (w.v26 * (w.v45 - w.v22)) = 0 ∧
  (w.v26 * (w.v46 - w.v23)) = 0 ∧
  (((1 : F) - w.v25) * (((1 : F) - w.v25) - (1 : F))) = 0 ∧
  (((1 : F) - w.v26) * (((1 : F) - w.v26) - (1 : F))) = 0 ∧
  (w.v24 * w.v31) = 0 ∧
  (w.v24 * w.v32) = 0 ∧
  (w.v24 * w.v33) = 0 ∧
  (w.v24 * w.v34) = 0 ∧
  (w.v2 * (w.v43 + (w.v44 * (256 : F)))) = 0 ∧
  (w.v2 - ((1 : F) - ((w.v43 + (w.v44 * (256 : F))) * w.v3))) = 0 ∧
  (w.v4 * (w.v45 + (w.v46 * (256 : F)))) = 0 ∧
  (w.v4 - ((1 : F) - ((w.v45 + (w.v46 * (256 : F))) * w.v5))) = 0 ∧
  (w.v6 - (w.v2 * w.v4)) = 0 ∧
  (w.v7 - w.v6) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v31 - w.v37))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v32 - w.v38))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v33 - w.v39))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v34 - w.v40))) = 0 ∧
  (((1 : F) - w.v7) * (w.v31 - w.v27)) = 0 ∧
  (((1 : F) - w.v7) * (w.v32 - w.v28)) = 0 ∧
  (((1 : F) - w.v7) * (w.v33 - w.v29)) = 0 ∧
  (((1 : F) - w.v7) * (w.v34 - w.v30)) = 0 ∧
  (w.v11).val ≤ ((65535 : F)).val ∧
  (w.v12).val ≤ ((65535 : F)).val ∧
  (w.v13).val ≤ ((511 : F)).val ∧
  ((w.v42 * ((1 : F) - w.v25))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (2 : F)) - w.v41) - (1 : F)) - w.v42) * (2130673921 : F)) * ((1 : F) - w.v25))).val ≤ ((511 : F)).val ∧
  (w.v355 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v356 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v357 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v358 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v359 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v40 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  ((w.v48 * ((1 : F) - w.v26))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (1 : F)) - w.v47) - (1 : F)) - w.v48) * (2130673921 : F)) * ((1 : F) - w.v26))).val ≤ ((511 : F)).val ∧
  (w.v360 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v361 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v43 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v362 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v44 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v363 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v45 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v364 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v46 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v13 * (65536 : F)) + w.v12) + (3 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v365 - (((w.v13 * (65536 : F)) + w.v12) + (5 : F))) = 0 ∧
  (w.v366 - (w.v1 + (4 : F))) = 0 ∧
  (w.v367 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v368 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  (w.v369 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  (w.v370 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  (w.v371 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  (w.v372 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v373 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  (w.v374 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  (w.v375 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  (w.v376 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  (w.v377 - ((w.v13 * (65536 : F)) + w.v12)) = 0

def inputs (w : W) : List F :=
  [w.v0, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v20, w.v21, w.v22, w.v23, w.v24, w.v25, w.v26, w.v355, w.v356, w.v357, w.v358, w.v359, w.v360, w.v361, w.v362, w.v363, w.v364, w.v27, w.v28, w.v29, w.v30, w.v11, w.v377, w.v1]
def outputs (w : W) : List F :=
  [w.v11, w.v365, w.v1, w.v366, w.v367, w.v368, w.v369, w.v370, w.v371, w.v372, w.v373, w.v374, w.v375, w.v376, w.v15, w.v31, w.v32, w.v33, w.v34]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det

end MovCond_is_meq

/-! ### Module `MovCond__is_mne` -/
namespace MovCond_is_mne

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `c_eq_lo_2` -/
  v2 : F
  /-- `c_eq_lo_inv_3` -/
  v3 : F
  /-- `c_eq_hi_4` -/
  v4 : F
  /-- `c_eq_hi_inv_5` -/
  v5 : F
  /-- `c_eq_0_6` -/
  v6 : F
  /-- `sel_moved_7` -/
  v7 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `frame_42` -/
  v42 : F
  /-- `frame_43` -/
  v43 : F
  /-- `frame_44` -/
  v44 : F
  /-- `frame_45` -/
  v45 : F
  /-- `frame_46` -/
  v46 : F
  /-- `frame_47` -/
  v47 : F
  /-- `frame_48` -/
  v48 : F
  v332 : F
  v333 : F
  v334 : F
  v335 : F
  v336 : F
  v337 : F
  v338 : F
  v339 : F
  v340 : F
  v341 : F
  v342 : F
  v343 : F
  v344 : F
  v345 : F
  v346 : F
  v347 : F
  v348 : F
  v349 : F
  v350 : F
  v351 : F
  v352 : F
  v353 : F
  v354 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints (w : W) : Prop :=
  (w.v14 - (51 : F)) = 0 ∧
  (w.v25 * (w.v37 - w.v16)) = 0 ∧
  (w.v25 * (w.v38 - w.v17)) = 0 ∧
  (w.v25 * (w.v39 - w.v18)) = 0 ∧
  (w.v25 * (w.v40 - w.v19)) = 0 ∧
  (w.v26 * (w.v43 - w.v20)) = 0 ∧
  (w.v26 * (w.v44 - w.v21)) = 0 ∧
  (w.v26 * (w.v45 - w.v22)) = 0 ∧
  (w.v26 * (w.v46 - w.v23)) = 0 ∧
  (((1 : F) - w.v25) * (((1 : F) - w.v25) - (1 : F))) = 0 ∧
  (((1 : F) - w.v26) * (((1 : F) - w.v26) - (1 : F))) = 0 ∧
  (w.v24 * w.v31) = 0 ∧
  (w.v24 * w.v32) = 0 ∧
  (w.v24 * w.v33) = 0 ∧
  (w.v24 * w.v34) = 0 ∧
  (w.v2 * (w.v43 + (w.v44 * (256 : F)))) = 0 ∧
  (w.v2 - ((1 : F) - ((w.v43 + (w.v44 * (256 : F))) * w.v3))) = 0 ∧
  (w.v4 * (w.v45 + (w.v46 * (256 : F)))) = 0 ∧
  (w.v4 - ((1 : F) - ((w.v45 + (w.v46 * (256 : F))) * w.v5))) = 0 ∧
  (w.v6 - (w.v2 * w.v4)) = 0 ∧
  (w.v7 - ((1 : F) - w.v6)) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v31 - w.v37))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v32 - w.v38))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v33 - w.v39))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v34 - w.v40))) = 0 ∧
  (((1 : F) - w.v7) * (w.v31 - w.v27)) = 0 ∧
  (((1 : F) - w.v7) * (w.v32 - w.v28)) = 0 ∧
  (((1 : F) - w.v7) * (w.v33 - w.v29)) = 0 ∧
  (((1 : F) - w.v7) * (w.v34 - w.v30)) = 0 ∧
  (w.v11).val ≤ ((65535 : F)).val ∧
  (w.v12).val ≤ ((65535 : F)).val ∧
  (w.v13).val ≤ ((511 : F)).val ∧
  ((w.v42 * ((1 : F) - w.v25))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (2 : F)) - w.v41) - (1 : F)) - w.v42) * (2130673921 : F)) * ((1 : F) - w.v25))).val ≤ ((511 : F)).val ∧
  (w.v332 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v333 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v334 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v335 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v336 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v40 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  ((w.v48 * ((1 : F) - w.v26))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (1 : F)) - w.v47) - (1 : F)) - w.v48) * (2130673921 : F)) * ((1 : F) - w.v26))).val ≤ ((511 : F)).val ∧
  (w.v337 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v338 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v43 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v339 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v44 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v340 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v45 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v341 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v46 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v13 * (65536 : F)) + w.v12) + (3 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v342 - (((w.v13 * (65536 : F)) + w.v12) + (5 : F))) = 0 ∧
  (w.v343 - (w.v1 + (4 : F))) = 0 ∧
  (w.v344 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v345 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  (w.v346 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  (w.v347 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  (w.v348 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  (w.v349 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v350 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  (w.v351 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  (w.v352 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  (w.v353 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  (w.v354 - ((w.v13 * (65536 : F)) + w.v12)) = 0

def inputs (w : W) : List F :=
  [w.v0, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v20, w.v21, w.v22, w.v23, w.v24, w.v25, w.v26, w.v332, w.v333, w.v334, w.v335, w.v336, w.v337, w.v338, w.v339, w.v340, w.v341, w.v27, w.v28, w.v29, w.v30, w.v11, w.v354, w.v1]
def outputs (w : W) : List F :=
  [w.v11, w.v342, w.v1, w.v343, w.v344, w.v345, w.v346, w.v347, w.v348, w.v349, w.v350, w.v351, w.v352, w.v353, w.v15, w.v31, w.v32, w.v33, w.v34]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det

end MovCond_is_mne

/-! ### Module `MovCond__is_wsbh` -/
namespace MovCond_is_wsbh

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `sel_moved_7` -/
  v7 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `frame_42` -/
  v42 : F
  /-- `frame_43` -/
  v43 : F
  /-- `frame_44` -/
  v44 : F
  /-- `frame_45` -/
  v45 : F
  /-- `frame_46` -/
  v46 : F
  /-- `frame_47` -/
  v47 : F
  /-- `frame_48` -/
  v48 : F
  v378 : F
  v379 : F
  v380 : F
  v381 : F
  v382 : F
  v383 : F
  v384 : F
  v385 : F
  v386 : F
  v387 : F
  v388 : F
  v389 : F
  v390 : F
  v391 : F
  v392 : F
  v393 : F
  v394 : F
  v395 : F
  v396 : F
  v397 : F
  v398 : F
  v399 : F
  v400 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints (w : W) : Prop :=
  (w.v14 - (52 : F)) = 0 ∧
  (w.v25 * (w.v37 - w.v16)) = 0 ∧
  (w.v25 * (w.v38 - w.v17)) = 0 ∧
  (w.v25 * (w.v39 - w.v18)) = 0 ∧
  (w.v25 * (w.v40 - w.v19)) = 0 ∧
  (w.v26 * (w.v43 - w.v20)) = 0 ∧
  (w.v26 * (w.v44 - w.v21)) = 0 ∧
  (w.v26 * (w.v45 - w.v22)) = 0 ∧
  (w.v26 * (w.v46 - w.v23)) = 0 ∧
  (((1 : F) - w.v25) * (((1 : F) - w.v25) - (1 : F))) = 0 ∧
  (((1 : F) - w.v26) * (((1 : F) - w.v26) - (1 : F))) = 0 ∧
  (w.v24 * w.v31) = 0 ∧
  (w.v24 * w.v32) = 0 ∧
  (w.v24 * w.v33) = 0 ∧
  (w.v24 * w.v34) = 0 ∧
  w.v7 = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v31 - w.v37))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v32 - w.v38))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v33 - w.v39))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v34 - w.v40))) = 0 ∧
  (((0 : F) - w.v7) * (w.v31 - w.v27)) = 0 ∧
  (((0 : F) - w.v7) * (w.v32 - w.v28)) = 0 ∧
  (((0 : F) - w.v7) * (w.v33 - w.v29)) = 0 ∧
  (((0 : F) - w.v7) * (w.v34 - w.v30)) = 0 ∧
  (w.v31 - (((1 : F) - w.v24) * w.v38)) = 0 ∧
  (w.v32 - (((1 : F) - w.v24) * w.v37)) = 0 ∧
  (w.v33 - (((1 : F) - w.v24) * w.v40)) = 0 ∧
  (w.v34 - (((1 : F) - w.v24) * w.v39)) = 0 ∧
  (w.v11).val ≤ ((65535 : F)).val ∧
  (w.v12).val ≤ ((65535 : F)).val ∧
  (w.v13).val ≤ ((511 : F)).val ∧
  ((w.v42 * ((1 : F) - w.v25))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (2 : F)) - w.v41) - (1 : F)) - w.v42) * (2130673921 : F)) * ((1 : F) - w.v25))).val ≤ ((511 : F)).val ∧
  (w.v378 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v379 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v37 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v380 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v38 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v381 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v39 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  (w.v382 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  ((w.v40 * ((1 : F) - w.v25))).val ≤ ((255 : F)).val ∧
  ((w.v48 * ((1 : F) - w.v26))).val ≤ ((65535 : F)).val ∧
  (((((((((w.v13 * (65536 : F)) + w.v12) + (1 : F)) - w.v47) - (1 : F)) - w.v48) * (2130673921 : F)) * ((1 : F) - w.v26))).val ≤ ((511 : F)).val ∧
  (w.v383 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v384 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v43 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v385 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v44 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v386 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v45 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v387 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  ((w.v46 * ((1 : F) - w.v26))).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((65535 : F)).val ∧
  ((((((((w.v13 * (65536 : F)) + w.v12) + (3 : F)) - w.v35) - (1 : F)) - w.v36) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v28).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v388 - (((w.v13 * (65536 : F)) + w.v12) + (5 : F))) = 0 ∧
  (w.v389 - (w.v1 + (4 : F))) = 0 ∧
  (w.v390 - (w.v16 * ((1 : F) - w.v25))) = 0 ∧
  (w.v391 - (w.v37 * ((1 : F) - w.v25))) = 0 ∧
  (w.v392 - (w.v38 * ((1 : F) - w.v25))) = 0 ∧
  (w.v393 - (w.v39 * ((1 : F) - w.v25))) = 0 ∧
  (w.v394 - (w.v40 * ((1 : F) - w.v25))) = 0 ∧
  (w.v395 - (w.v20 * ((1 : F) - w.v26))) = 0 ∧
  (w.v396 - (w.v43 * ((1 : F) - w.v26))) = 0 ∧
  (w.v397 - (w.v44 * ((1 : F) - w.v26))) = 0 ∧
  (w.v398 - (w.v45 * ((1 : F) - w.v26))) = 0 ∧
  (w.v399 - (w.v46 * ((1 : F) - w.v26))) = 0 ∧
  (w.v400 - ((w.v13 * (65536 : F)) + w.v12)) = 0

def inputs (w : W) : List F :=
  [w.v0, w.v14, w.v15, w.v16, w.v17, w.v18, w.v19, w.v20, w.v21, w.v22, w.v23, w.v24, w.v25, w.v26, w.v378, w.v379, w.v380, w.v381, w.v382, w.v383, w.v384, w.v385, w.v386, w.v387, w.v27, w.v28, w.v29, w.v30, w.v11, w.v400, w.v1]
def outputs (w : W) : List F :=
  [w.v11, w.v388, w.v1, w.v389, w.v390, w.v391, w.v392, w.v393, w.v394, w.v395, w.v396, w.v397, w.v398, w.v399, w.v15, w.v31, w.v32, w.v33, w.v34]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det

end MovCond_is_wsbh

/-! ### Module `top` -/
namespace top

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `c_eq_lo_2` -/
  v2 : F
  /-- `c_eq_lo_inv_3` -/
  v3 : F
  /-- `c_eq_hi_4` -/
  v4 : F
  /-- `c_eq_hi_inv_5` -/
  v5 : F
  /-- `c_eq_0_6` -/
  v6 : F
  /-- `sel_moved_7` -/
  v7 : F
  /-- `is_mne_8` -/
  v8 : F
  /-- `is_meq_9` -/
  v9 : F
  /-- `is_wsbh_10` -/
  v10 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_43` -/
  v43 : F
  /-- `frame_44` -/
  v44 : F
  /-- `frame_45` -/
  v45 : F
  /-- `frame_46` -/
  v46 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints (w : W) : Prop :=
  (((1 : F) - ((w.v8 + w.v9) + w.v10)) * ((1 : F) - w.v25)) = 0 ∧
  (((1 : F) - ((w.v8 + w.v9) + w.v10)) * ((1 : F) - w.v26)) = 0 ∧
  (((w.v8 + w.v9) + w.v10) * (w.v14 - (((w.v9 * (50 : F)) + (w.v8 * (51 : F))) + (w.v10 * (52 : F))))) = 0 ∧
  (w.v25 * (w.v37 - w.v16)) = 0 ∧
  (w.v25 * (w.v38 - w.v17)) = 0 ∧
  (w.v25 * (w.v39 - w.v18)) = 0 ∧
  (w.v25 * (w.v40 - w.v19)) = 0 ∧
  (w.v26 * (w.v43 - w.v20)) = 0 ∧
  (w.v26 * (w.v44 - w.v21)) = 0 ∧
  (w.v26 * (w.v45 - w.v22)) = 0 ∧
  (w.v26 * (w.v46 - w.v23)) = 0 ∧
  (((1 : F) - w.v25) * (((1 : F) - w.v25) - (1 : F))) = 0 ∧
  (((1 : F) - w.v26) * (((1 : F) - w.v26) - (1 : F))) = 0 ∧
  (w.v24 * w.v31) = 0 ∧
  (w.v24 * w.v32) = 0 ∧
  (w.v24 * w.v33) = 0 ∧
  (w.v24 * w.v34) = 0 ∧
  (((w.v8 + w.v9) + w.v10) * (((w.v8 + w.v9) + w.v10) - (1 : F))) = 0 ∧
  ((w.v8 + w.v9) * (w.v2 * (w.v43 + (w.v44 * (256 : F))))) = 0 ∧
  ((w.v8 + w.v9) * (w.v2 - ((1 : F) - ((w.v43 + (w.v44 * (256 : F))) * w.v3)))) = 0 ∧
  ((w.v8 + w.v9) * (w.v4 * (w.v45 + (w.v46 * (256 : F))))) = 0 ∧
  ((w.v8 + w.v9) * (w.v4 - ((1 : F) - ((w.v45 + (w.v46 * (256 : F))) * w.v5)))) = 0 ∧
  ((w.v8 + w.v9) * (w.v6 - (w.v2 * w.v4))) = 0 ∧
  (w.v7 - ((w.v9 * w.v6) + (w.v8 * ((1 : F) - w.v6)))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v31 - w.v37))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v32 - w.v38))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v33 - w.v39))) = 0 ∧
  (w.v7 * ((w.v24 - (1 : F)) * (w.v34 - w.v40))) = 0 ∧
  (((w.v8 + w.v9) - w.v7) * (w.v31 - w.v27)) = 0 ∧
  (((w.v8 + w.v9) - w.v7) * (w.v32 - w.v28)) = 0 ∧
  (((w.v8 + w.v9) - w.v7) * (w.v33 - w.v29)) = 0 ∧
  (((w.v8 + w.v9) - w.v7) * (w.v34 - w.v30)) = 0 ∧
  (w.v10 * (w.v31 - (((1 : F) - w.v24) * w.v38))) = 0 ∧
  (w.v10 * (w.v32 - (((1 : F) - w.v24) * w.v37))) = 0 ∧
  (w.v10 * (w.v33 - (((1 : F) - w.v24) * w.v40))) = 0 ∧
  (w.v10 * (w.v34 - (((1 : F) - w.v24) * w.v39))) = 0 ∧
  (w.v8 * (w.v8 - (1 : F))) = 0 ∧
  (w.v9 * (w.v9 - (1 : F))) = 0 ∧
  (w.v10 * (w.v10 - (1 : F))) = 0 ∧
  (((w.v8 + w.v9) + w.v10) * (((w.v8 + w.v9) + w.v10) - (1 : F))) = 0

def inputs (_w : W) : List F := []
def outputs (w : W) : List F :=
  [w.v8, w.v9, w.v10]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det

/-- Selector-shape / bit postconditions implied by the constraints. -/
theorem postconditions (w : W) (hw : constraints w) :
    (w.v8 * (w.v8 - (1 : F))) = 0 ∧
    (w.v9 * (w.v9 - (1 : F))) = 0 ∧
    (w.v10 * (w.v10 - (1 : F))) = 0 ∧
    (((w.v8 + w.v9) + w.v10)).val < ((2 : F)).val := by
  picus_det

end top

end ZirenDet.Chips.MovCond
