/-
  Generated by `cargo run -p zkm-picus -- --chip ShaExtendControl --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

namespace ZirenDet.Chips.ShaExtendControl

open ZirenDet

/-! ### Module `ShaExtendControl` -/
namespace ShaExtendControl

/-- Abstract helper: 3 input(s), 3 output(s).  Its relation is left opaque; every
caller takes its determinism as a hypothesis. -/
opaque rel : List F → List F → Prop

end ShaExtendControl

end ZirenDet.Chips.ShaExtendControl
