/-
  Generated by `cargo run -p zkm-picus -- --chip ShiftLeftImm --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

set_option maxRecDepth 4000000
set_option maxHeartbeats 8000000
set_option linter.dupNamespace false

namespace ZirenDet.Chips.ShiftLeftImm

open ZirenDet

/-! ### Module `ShiftLeftImm` -/
namespace ShiftLeftImm

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `pc_0` -/
  v0 : F
  /-- `next_pc_1` -/
  v1 : F
  /-- `c_least_sig_byte_2` -/
  v2 : F
  /-- `c_least_sig_byte_3` -/
  v3 : F
  /-- `c_least_sig_byte_4` -/
  v4 : F
  /-- `c_least_sig_byte_5` -/
  v5 : F
  /-- `c_least_sig_byte_6` -/
  v6 : F
  /-- `bit_shift_multiplier_7` -/
  v7 : F
  /-- `bit_shift_result_8` -/
  v8 : F
  /-- `bit_shift_result_9` -/
  v9 : F
  /-- `bit_shift_result_10` -/
  v10 : F
  /-- `bit_shift_result_11` -/
  v11 : F
  /-- `bit_shift_result_carry_12` -/
  v12 : F
  /-- `bit_shift_result_carry_13` -/
  v13 : F
  /-- `bit_shift_result_carry_14` -/
  v14 : F
  /-- `bit_shift_result_carry_15` -/
  v15 : F
  /-- `shift_by_n_bytes_16` -/
  v16 : F
  /-- `shift_by_n_bytes_17` -/
  v17 : F
  /-- `shift_by_n_bytes_18` -/
  v18 : F
  /-- `shift_by_n_bytes_19` -/
  v19 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `frame_30` -/
  v30 : F
  /-- `frame_31` -/
  v31 : F
  /-- `frame_32` -/
  v32 : F
  /-- `frame_33` -/
  v33 : F
  /-- `frame_34` -/
  v34 : F
  /-- `frame_35` -/
  v35 : F
  /-- `frame_36` -/
  v36 : F
  /-- `frame_37` -/
  v37 : F
  /-- `frame_38` -/
  v38 : F
  /-- `frame_39` -/
  v39 : F
  /-- `frame_40` -/
  v40 : F
  /-- `frame_41` -/
  v41 : F
  /-- `frame_42` -/
  v42 : F
  /-- `frame_43` -/
  v43 : F
  /-- `frame_44` -/
  v44 : F
  v324 : F
  v325 : F
  v326 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints_0 (w : W) : Prop :=
  (((((w.v2 + (w.v3 * (2 : F))) + (w.v4 * (4 : F))) + (w.v5 * (8 : F))) + (w.v6 * (16 : F))) - w.v27) = 0 ∧
  (w.v7 - ((((1 : F) + w.v2) * ((1 : F) + (w.v3 * (3 : F)))) * ((1 : F) + (w.v4 * (15 : F))))) = 0 ∧
  (w.v8 - ((w.v39 * w.v7) - (w.v12 * (256 : F)))) = 0 ∧
  (w.v9 - (((w.v40 * w.v7) - (w.v13 * (256 : F))) + w.v12)) = 0 ∧
  (w.v10 - (((w.v41 * w.v7) - (w.v14 * (256 : F))) + w.v13)) = 0 ∧
  (w.v11 - (((w.v42 * w.v7) - (w.v15 * (256 : F))) + w.v14)) = 0 ∧
  (w.v16 * (w.v5 + (w.v6 * (2 : F)))) = 0 ∧
  (w.v17 * ((w.v5 + (w.v6 * (2 : F))) - (1 : F))) = 0 ∧
  (w.v18 * ((w.v5 + (w.v6 * (2 : F))) - (2 : F))) = 0 ∧
  (w.v19 * ((w.v5 + (w.v6 * (2 : F))) - (3 : F))) = 0 ∧
  (w.v16 * (w.v33 - (((1 : F) - w.v28) * w.v8))) = 0 ∧
  (w.v16 * (w.v34 - (((1 : F) - w.v28) * w.v9))) = 0 ∧
  (w.v16 * (w.v35 - (((1 : F) - w.v28) * w.v10))) = 0 ∧
  (w.v16 * (w.v36 - (((1 : F) - w.v28) * w.v11))) = 0 ∧
  (w.v17 * w.v33) = 0 ∧
  (w.v17 * (w.v34 - (((1 : F) - w.v28) * w.v8))) = 0 ∧
  (w.v17 * (w.v35 - (((1 : F) - w.v28) * w.v9))) = 0 ∧
  (w.v17 * (w.v36 - (((1 : F) - w.v28) * w.v10))) = 0 ∧
  (w.v18 * w.v33) = 0 ∧
  (w.v18 * w.v34) = 0 ∧
  (w.v18 * (w.v35 - (((1 : F) - w.v28) * w.v8))) = 0 ∧
  (w.v18 * (w.v36 - (((1 : F) - w.v28) * w.v9))) = 0 ∧
  (w.v19 * w.v33) = 0 ∧
  (w.v19 * w.v34) = 0 ∧
  (w.v19 * w.v35) = 0 ∧
  (w.v19 * (w.v36 - (((1 : F) - w.v28) * w.v8))) = 0 ∧
  (w.v2 * (w.v2 - (1 : F))) = 0 ∧
  (w.v3 * (w.v3 - (1 : F))) = 0 ∧
  (w.v4 * (w.v4 - (1 : F))) = 0 ∧
  (w.v5 * (w.v5 - (1 : F))) = 0 ∧
  (w.v6 * (w.v6 - (1 : F))) = 0 ∧
  (w.v16 * (w.v16 - (1 : F))) = 0 ∧
  (w.v17 * (w.v17 - (1 : F))) = 0 ∧
  (w.v18 * (w.v18 - (1 : F))) = 0 ∧
  (w.v19 * (w.v19 - (1 : F))) = 0 ∧
  ((((w.v16 + w.v17) + w.v18) + w.v19) - (1 : F)) = 0 ∧
  (w.v24 - (9 : F)) = 0 ∧
  (w.v28 * w.v33) = 0 ∧
  (w.v28 * w.v34) = 0 ∧
  (w.v28 * w.v35) = 0 ∧
  (w.v28 * w.v36) = 0 ∧
  (w.v8).val ≤ ((255 : F)).val ∧
  (w.v9).val ≤ ((255 : F)).val ∧
  (w.v10).val ≤ ((255 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val

def constraints_1 (w : W) : Prop :=
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((65535 : F)).val ∧
  (w.v22).val ≤ ((65535 : F)).val ∧
  (w.v23).val ≤ ((511 : F)).val ∧
  (w.v44).val ≤ ((65535 : F)).val ∧
  ((((((((w.v23 * (65536 : F)) + w.v22) + (2 : F)) - w.v43) - (1 : F)) - w.v44) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v39).val ≤ ((255 : F)).val ∧
  (w.v40).val ≤ ((255 : F)).val ∧
  (w.v41).val ≤ ((255 : F)).val ∧
  (w.v42).val ≤ ((255 : F)).val ∧
  (w.v38).val ≤ ((65535 : F)).val ∧
  ((((((((w.v23 * (65536 : F)) + w.v22) + (3 : F)) - w.v37) - (1 : F)) - w.v38) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v29).val ≤ ((255 : F)).val ∧
  (w.v30).val ≤ ((255 : F)).val ∧
  (w.v31).val ≤ ((255 : F)).val ∧
  (w.v32).val ≤ ((255 : F)).val ∧
  (w.v33).val ≤ ((255 : F)).val ∧
  (w.v34).val ≤ ((255 : F)).val ∧
  (w.v35).val ≤ ((255 : F)).val ∧
  (w.v36).val ≤ ((255 : F)).val ∧
  (w.v324 - (((w.v23 * (65536 : F)) + w.v22) + (5 : F))) = 0 ∧
  (w.v325 - (w.v1 + (4 : F))) = 0 ∧
  (w.v326 - ((w.v23 * (65536 : F)) + w.v22)) = 0

def constraints (w : W) : Prop :=
  constraints_0 w ∧
  constraints_1 w

def inputs (w : W) : List F :=
  [w.v0, w.v24, w.v25, w.v26, w.v27, w.v28, w.v39, w.v40, w.v41, w.v42, w.v29, w.v30, w.v31, w.v32, w.v21, w.v326, w.v1]
def outputs (w : W) : List F :=
  [w.v21, w.v324, w.v1, w.v325, w.v26, w.v39, w.v40, w.v41, w.v42, w.v25, w.v33, w.v34, w.v35, w.v36]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det [constraints_0, constraints_1]

end ShiftLeftImm

end ZirenDet.Chips.ShiftLeftImm
