/-
  Generated by `cargo run -p zkm-picus -- --chip SyscallInstrs --format lean`.
  Do not edit: regenerate after any change to the chip's AIR.
-/
import ZirenDet.Basic

namespace ZirenDet.Chips.SyscallInstrs

open ZirenDet

/-! ### Module `SyscallInstrs` -/
namespace SyscallInstrs

/-- The witness row: one field element per variable the module mentions. -/
structure W where
  /-- `frame_0` -/
  v0 : F
  /-- `frame_1` -/
  v1 : F
  /-- `frame_2` -/
  v2 : F
  /-- `frame_3` -/
  v3 : F
  /-- `frame_4` -/
  v4 : F
  /-- `frame_5` -/
  v5 : F
  /-- `frame_6` -/
  v6 : F
  /-- `frame_7` -/
  v7 : F
  /-- `frame_8` -/
  v8 : F
  /-- `frame_9` -/
  v9 : F
  /-- `frame_10` -/
  v10 : F
  /-- `frame_11` -/
  v11 : F
  /-- `frame_12` -/
  v12 : F
  /-- `frame_13` -/
  v13 : F
  /-- `frame_14` -/
  v14 : F
  /-- `frame_15` -/
  v15 : F
  /-- `frame_16` -/
  v16 : F
  /-- `frame_17` -/
  v17 : F
  /-- `frame_18` -/
  v18 : F
  /-- `frame_19` -/
  v19 : F
  /-- `frame_20` -/
  v20 : F
  /-- `frame_21` -/
  v21 : F
  /-- `frame_22` -/
  v22 : F
  /-- `frame_23` -/
  v23 : F
  /-- `frame_24` -/
  v24 : F
  /-- `frame_25` -/
  v25 : F
  /-- `frame_26` -/
  v26 : F
  /-- `frame_27` -/
  v27 : F
  /-- `frame_28` -/
  v28 : F
  /-- `frame_29` -/
  v29 : F
  /-- `pc_30` -/
  v30 : F
  /-- `next_pc_31` -/
  v31 : F
  /-- `num_extra_cycles_32` -/
  v32 : F
  /-- `state_recv_next_pc_33` -/
  v33 : F
  /-- `is_halt_34` -/
  v34 : F
  /-- `is_sys_linux_35` -/
  v35 : F
  /-- `is_prev_a1_zero_36` -/
  v36 : F
  /-- `is_prev_a1_zero_37` -/
  v37 : F
  /-- `syscall_id_38` -/
  v38 : F
  /-- `op_a_value_39` -/
  v39 : F
  /-- `op_a_value_40` -/
  v40 : F
  /-- `op_a_value_41` -/
  v41 : F
  /-- `op_a_value_42` -/
  v42 : F
  /-- `is_enter_unconstrained_43` -/
  v43 : F
  /-- `is_enter_unconstrained_44` -/
  v44 : F
  /-- `is_hint_len_45` -/
  v45 : F
  /-- `is_hint_len_46` -/
  v46 : F
  /-- `is_halt_check_47` -/
  v47 : F
  /-- `is_halt_check_48` -/
  v48 : F
  /-- `is_exit_group_check_49` -/
  v49 : F
  /-- `is_exit_group_check_50` -/
  v50 : F
  /-- `is_commit_51` -/
  v51 : F
  /-- `is_commit_52` -/
  v52 : F
  /-- `is_commit_deferred_proofs_53` -/
  v53 : F
  /-- `is_commit_deferred_proofs_54` -/
  v54 : F
  /-- `index_bitmap_55` -/
  v55 : F
  /-- `index_bitmap_56` -/
  v56 : F
  /-- `index_bitmap_57` -/
  v57 : F
  /-- `index_bitmap_58` -/
  v58 : F
  /-- `index_bitmap_59` -/
  v59 : F
  /-- `index_bitmap_60` -/
  v60 : F
  /-- `index_bitmap_61` -/
  v61 : F
  /-- `index_bitmap_62` -/
  v62 : F
  /-- `op_b_range_check_63` -/
  v63 : F
  /-- `op_c_range_check_64` -/
  v64 : F
  /-- `op_b_check_65` -/
  v65 : F
  /-- `op_c_check_66` -/
  v66 : F
  /-- `pv_0` -/
  v138 : F
  /-- `pv_1` -/
  v139 : F
  /-- `pv_2` -/
  v140 : F
  /-- `pv_3` -/
  v141 : F
  /-- `pv_4` -/
  v142 : F
  /-- `pv_5` -/
  v143 : F
  /-- `pv_6` -/
  v144 : F
  /-- `pv_7` -/
  v145 : F
  /-- `pv_8` -/
  v146 : F
  /-- `pv_9` -/
  v147 : F
  /-- `pv_10` -/
  v148 : F
  /-- `pv_11` -/
  v149 : F
  /-- `pv_12` -/
  v150 : F
  /-- `pv_13` -/
  v151 : F
  /-- `pv_14` -/
  v152 : F
  /-- `pv_15` -/
  v153 : F
  /-- `pv_16` -/
  v154 : F
  /-- `pv_17` -/
  v155 : F
  /-- `pv_18` -/
  v156 : F
  /-- `pv_19` -/
  v157 : F
  /-- `pv_20` -/
  v158 : F
  /-- `pv_21` -/
  v159 : F
  /-- `pv_22` -/
  v160 : F
  /-- `pv_23` -/
  v161 : F
  /-- `pv_24` -/
  v162 : F
  /-- `pv_25` -/
  v163 : F
  /-- `pv_26` -/
  v164 : F
  /-- `pv_27` -/
  v165 : F
  /-- `pv_28` -/
  v166 : F
  /-- `pv_29` -/
  v167 : F
  /-- `pv_30` -/
  v168 : F
  /-- `pv_31` -/
  v169 : F
  /-- `pv_32` -/
  v170 : F
  /-- `pv_33` -/
  v171 : F
  /-- `pv_34` -/
  v172 : F
  /-- `pv_35` -/
  v173 : F
  /-- `pv_36` -/
  v174 : F
  /-- `pv_37` -/
  v175 : F
  /-- `pv_38` -/
  v176 : F
  /-- `pv_39` -/
  v177 : F
  /-- `pv_42` -/
  v180 : F
  v370 : F
  v371 : F
  v372 : F
  v373 : F
  v374 : F
  v375 : F
  v376 : F
  v377 : F
  v378 : F
  v379 : F
  v380 : F
  v381 : F

/-- Every polynomial identity, range fact and helper-module call of the module. -/
def constraints (w : W) : Prop :=
  (((1 : F) - (w.v47 * (w.v8 + (w.v9 * (256 : F))))) - w.v48) = 0 ∧
  (w.v48 * (w.v48 - (1 : F))) = 0 ∧
  (w.v48 * (w.v8 + (w.v9 * (256 : F)))) = 0 ∧
  (((1 : F) - (w.v49 * ((w.v8 + (w.v9 * (256 : F))) - (4246 : F)))) - w.v50) = 0 ∧
  (w.v50 * (w.v50 - (1 : F))) = 0 ∧
  (w.v50 * ((w.v8 + (w.v9 * (256 : F))) - (4246 : F))) = 0 ∧
  (w.v34 - (w.v48 + w.v50)) = 0 ∧
  (w.v3 - (30 : F)) = 0 ∧
  (w.v7 * w.v12) = 0 ∧
  (w.v7 * w.v13) = 0 ∧
  (w.v7 * w.v14) = 0 ∧
  (w.v7 * w.v15) = 0 ∧
  ((w.v33 - w.v31) - (w.v34 * ((w.v30 + (4 : F)) - w.v31))) = 0 ∧
  ((w.v7 - (1 : F)) * (w.v39 - w.v12)) = 0 ∧
  ((w.v7 - (1 : F)) * (w.v40 - w.v13)) = 0 ∧
  ((w.v7 - (1 : F)) * (w.v41 - w.v14)) = 0 ∧
  ((w.v7 - (1 : F)) * (w.v42 - w.v15)) = 0 ∧
  (w.v32 - w.v11) = 0 ∧
  (w.v10 * (w.v10 - (1 : F))) = 0 ∧
  (w.v35 * (w.v35 - (1 : F))) = 0 ∧
  ((w.v35 + w.v10) * ((w.v35 + w.v10) - (1 : F))) = 0 ∧
  (((1 : F) - (w.v36 * w.v9)) - w.v37) = 0 ∧
  (w.v37 * (w.v37 - (1 : F))) = 0 ∧
  (w.v37 * w.v9) = 0 ∧
  (w.v35 - ((1 : F) - w.v37)) = 0 ∧
  (w.v65 * (w.v65 - (1 : F))) = 0 ∧
  (w.v66 * (w.v66 - (1 : F))) = 0 ∧
  (w.v10 * (w.v65 - (1 : F))) = 0 ∧
  (w.v34 * (w.v65 - (1 : F))) = 0 ∧
  (w.v10 * (w.v66 - (1 : F))) = 0 ∧
  (w.v54 * (w.v66 - (1 : F))) = 0 ∧
  (w.v63 * (w.v63 - (1 : F))) = 0 ∧
  ((w.v65 - (1 : F)) * w.v63) = 0 ∧
  (w.v63 * (w.v21 - (127 : F))) = 0 ∧
  (w.v63 * ((w.v18 + w.v19) + w.v20)) = 0 ∧
  (w.v64 * (w.v64 - (1 : F))) = 0 ∧
  ((w.v66 - (1 : F)) * w.v64) = 0 ∧
  (w.v64 * (w.v27 - (127 : F))) = 0 ∧
  (w.v64 * ((w.v24 + w.v25) + w.v26)) = 0 ∧
  (((1 : F) - (w.v43 * ((w.v8 + (w.v9 * (256 : F))) - (3 : F)))) - w.v44) = 0 ∧
  (w.v44 * (w.v44 - (1 : F))) = 0 ∧
  (w.v44 * ((w.v8 + (w.v9 * (256 : F))) - (3 : F))) = 0 ∧
  ((w.v44 - (1 : F)) * (w.v38 - (w.v8 + (w.v9 * (256 : F))))) = 0 ∧
  (w.v44 * (w.v38 - (4 : F))) = 0 ∧
  (((1 : F) - (w.v45 * ((w.v8 + (w.v9 * (256 : F))) - (240 : F)))) - w.v46) = 0 ∧
  (w.v46 * (w.v46 - (1 : F))) = 0 ∧
  (w.v46 * ((w.v8 + (w.v9 * (256 : F))) - (240 : F))) = 0 ∧
  (w.v44 * w.v39) = 0 ∧
  (w.v44 * w.v40) = 0 ∧
  (w.v44 * w.v41) = 0 ∧
  (w.v44 * w.v42) = 0 ∧
  ((((w.v44 + w.v46) + w.v35) - (1 : F)) * (w.v39 - w.v8)) = 0 ∧
  ((((w.v44 + w.v46) + w.v35) - (1 : F)) * (w.v40 - w.v9)) = 0 ∧
  ((((w.v44 + w.v46) + w.v35) - (1 : F)) * (w.v41 - w.v10)) = 0 ∧
  ((((w.v44 + w.v46) + w.v35) - (1 : F)) * (w.v42 - w.v11)) = 0 ∧
  (((1 : F) - (w.v51 * ((w.v8 + (w.v9 * (256 : F))) - (16 : F)))) - w.v52) = 0 ∧
  (w.v52 * (w.v52 - (1 : F))) = 0 ∧
  (w.v52 * ((w.v8 + (w.v9 * (256 : F))) - (16 : F))) = 0 ∧
  (((1 : F) - (w.v53 * ((w.v8 + (w.v9 * (256 : F))) - (26 : F)))) - w.v54) = 0 ∧
  (w.v54 * (w.v54 - (1 : F))) = 0 ∧
  (w.v54 * ((w.v8 + (w.v9 * (256 : F))) - (26 : F))) = 0 ∧
  (w.v55 * (w.v55 - (1 : F))) = 0 ∧
  (w.v56 * (w.v56 - (1 : F))) = 0 ∧
  (w.v57 * (w.v57 - (1 : F))) = 0 ∧
  (w.v58 * (w.v58 - (1 : F))) = 0 ∧
  (w.v59 * (w.v59 - (1 : F))) = 0 ∧
  (w.v60 * (w.v60 - (1 : F))) = 0 ∧
  (w.v61 * (w.v61 - (1 : F))) = 0 ∧
  (w.v62 * (w.v62 - (1 : F))) = 0 ∧
  ((w.v52 + w.v54) * ((((((((w.v55 + w.v56) + w.v57) + w.v58) + w.v59) + w.v60) + w.v61) + w.v62) - (1 : F))) = 0 ∧
  (((1 : F) - (w.v52 + w.v54)) * (((((((w.v55 + w.v56) + w.v57) + w.v58) + w.v59) + w.v60) + w.v61) + w.v62)) = 0 ∧
  (w.v55 * w.v18) = 0 ∧
  (w.v56 * (w.v18 - (1 : F))) = 0 ∧
  (w.v57 * (w.v18 - (2 : F))) = 0 ∧
  (w.v58 * (w.v18 - (3 : F))) = 0 ∧
  (w.v59 * (w.v18 - (4 : F))) = 0 ∧
  (w.v60 * (w.v18 - (5 : F))) = 0 ∧
  (w.v61 * (w.v18 - (6 : F))) = 0 ∧
  (w.v62 * (w.v18 - (7 : F))) = 0 ∧
  ((w.v52 + w.v54) * w.v19) = 0 ∧
  ((w.v52 + w.v54) * w.v20) = 0 ∧
  ((w.v52 + w.v54) * w.v21) = 0 ∧
  (w.v52 * (((((((((w.v138 * w.v55) + (w.v142 * w.v56)) + (w.v146 * w.v57)) + (w.v150 * w.v58)) + (w.v154 * w.v59)) + (w.v158 * w.v60)) + (w.v162 * w.v61)) + (w.v166 * w.v62)) - w.v24)) = 0 ∧
  (w.v52 * (((((((((w.v139 * w.v55) + (w.v143 * w.v56)) + (w.v147 * w.v57)) + (w.v151 * w.v58)) + (w.v155 * w.v59)) + (w.v159 * w.v60)) + (w.v163 * w.v61)) + (w.v167 * w.v62)) - w.v25)) = 0 ∧
  (w.v52 * (((((((((w.v140 * w.v55) + (w.v144 * w.v56)) + (w.v148 * w.v57)) + (w.v152 * w.v58)) + (w.v156 * w.v59)) + (w.v160 * w.v60)) + (w.v164 * w.v61)) + (w.v168 * w.v62)) - w.v26)) = 0 ∧
  (w.v52 * (((((((((w.v141 * w.v55) + (w.v145 * w.v56)) + (w.v149 * w.v57)) + (w.v153 * w.v58)) + (w.v157 * w.v59)) + (w.v161 * w.v60)) + (w.v165 * w.v61)) + (w.v169 * w.v62)) - w.v27)) = 0 ∧
  (w.v54 * (((((((((w.v170 * w.v55) + (w.v171 * w.v56)) + (w.v172 * w.v57)) + (w.v173 * w.v58)) + (w.v174 * w.v59)) + (w.v175 * w.v60)) + (w.v176 * w.v61)) + (w.v177 * w.v62)) - (((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))))) = 0 ∧
  (w.v34 * w.v31) = 0 ∧
  (w.v34 * ((((w.v18 + (w.v19 * (256 : F))) + (w.v20 * (65536 : F))) + (w.v21 * (16777216 : F))) - w.v180)) = 0 ∧
  (w.v0).val ≤ ((65535 : F)).val ∧
  (w.v1).val ≤ ((65535 : F)).val ∧
  (w.v2).val ≤ ((511 : F)).val ∧
  (w.v23).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (2 : F)) - w.v22) - (1 : F)) - w.v23) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v18).val ≤ ((255 : F)).val ∧
  (w.v19).val ≤ ((255 : F)).val ∧
  (w.v20).val ≤ ((255 : F)).val ∧
  (w.v21).val ≤ ((255 : F)).val ∧
  (w.v29).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (1 : F)) - w.v28) - (1 : F)) - w.v29) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v24).val ≤ ((255 : F)).val ∧
  (w.v25).val ≤ ((255 : F)).val ∧
  (w.v26).val ≤ ((255 : F)).val ∧
  (w.v27).val ≤ ((255 : F)).val ∧
  (w.v17).val ≤ ((65535 : F)).val ∧
  ((((((((w.v2 * (65536 : F)) + w.v1) + (3 : F)) - w.v16) - (1 : F)) - w.v17) * (2130673921 : F))).val ≤ ((511 : F)).val ∧
  (w.v8).val ≤ ((255 : F)).val ∧
  (w.v9).val ≤ ((255 : F)).val ∧
  (w.v10).val ≤ ((255 : F)).val ∧
  (w.v11).val ≤ ((255 : F)).val ∧
  (w.v12).val ≤ ((255 : F)).val ∧
  (w.v13).val ≤ ((255 : F)).val ∧
  (w.v14).val ≤ ((255 : F)).val ∧
  (w.v15).val ≤ ((255 : F)).val ∧
  (w.v370 - ((((w.v2 * (65536 : F)) + w.v1) + (5 : F)) + w.v32)) = 0 ∧
  (w.v371 - (w.v31 + (4 : F))) = 0 ∧
  (w.v21).val < ((127 : F)).val ∧
  (w.v27).val < ((127 : F)).val ∧
  (w.v372 - ((w.v8 + (w.v9 * (256 : F))) * (w.v35 + w.v10))) = 0 ∧
  (w.v373 - ((((w.v18 + (w.v19 * (256 : F))) + (w.v20 * (65536 : F))) + (w.v21 * (16777216 : F))) * (w.v35 + w.v10))) = 0 ∧
  (w.v374 - ((((w.v24 + (w.v25 * (256 : F))) + (w.v26 * (65536 : F))) + (w.v27 * (16777216 : F))) * (w.v35 + w.v10))) = 0 ∧
  (w.v375 - ((w.v39 + (w.v40 * (256 : F))) * w.v35)) = 0 ∧
  (w.v376 - ((w.v41 + (w.v42 * (256 : F))) * w.v35)) = 0 ∧
  (w.v377 - ((w.v18 + (w.v19 * (256 : F))) * w.v35)) = 0 ∧
  (w.v378 - ((w.v20 + (w.v21 * (256 : F))) * w.v35)) = 0 ∧
  (w.v379 - ((w.v24 + (w.v25 * (256 : F))) * w.v35)) = 0 ∧
  (w.v380 - ((w.v26 + (w.v27 * (256 : F))) * w.v35)) = 0 ∧
  (((w.v18 + (w.v19 * (256 : F))) * w.v35)).val ≤ ((65535 : F)).val ∧
  (((w.v20 + (w.v21 * (256 : F))) * w.v35)).val ≤ ((65535 : F)).val ∧
  (((w.v24 + (w.v25 * (256 : F))) * w.v35)).val ≤ ((65535 : F)).val ∧
  (((w.v26 + (w.v27 * (256 : F))) * w.v35)).val ≤ ((65535 : F)).val ∧
  (w.v381 - ((w.v2 * (65536 : F)) + w.v1)) = 0

def inputs (w : W) : List F :=
  [w.v30, w.v3, w.v4, w.v5, w.v6, w.v7, w.v18, w.v19, w.v20, w.v21, w.v24, w.v25, w.v26, w.v27, w.v8, w.v9, w.v10, w.v11, w.v377, w.v378, w.v379, w.v380, w.v0, w.v381, w.v33]
def outputs (w : W) : List F :=
  [w.v0, w.v370, w.v31, w.v371, w.v372, w.v373, w.v374, w.v375, w.v376, w.v5, w.v18, w.v19, w.v20, w.v21, w.v6, w.v24, w.v25, w.v26, w.v27, w.v4, w.v12, w.v13, w.v14, w.v15]
def assumed (_w : W) : List F := []

/-- The module as a relation between its input and output lists. -/
def rel (ins outs : List F) : Prop :=
  ∃ w : W, constraints w ∧ inputs w = ins ∧ outputs w = outs

/-- Determinism: equal inputs (and equal assumed-deterministic values) force equal outputs. -/
theorem deterministic
    (w w' : W) (hw : constraints w) (hw' : constraints w')
    (hin : inputs w = inputs w') (hassume : assumed w = assumed w') :
    outputs w = outputs w' := by
  picus_det

end SyscallInstrs

end ZirenDet.Chips.SyscallInstrs
